const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {createEngine,selectAudience,verifyWebhook}=require('../functions/campaign-engine');
function database(seed={}){
 const data=new Map(Object.entries(seed)),clone=x=>x===undefined?undefined:structuredClone(x);let tail=Promise.resolve();
 const merge=(path,value,keep)=>{const old=keep?data.get(path)||{}:{};const next={...old};for(const [k,v]of Object.entries(value))next[k]=v&&v.increment!==undefined?(next[k]||0)+v.increment:clone(v);data.set(path,next)};
 const ref=path=>({id:path.split('/').at(-1),path,get:async()=>snap(path),set:async(v,o)=>merge(path,v,o?.merge),update:async v=>merge(path,v,true)});
 const snap=path=>({id:path.split('/').at(-1),exists:data.has(path),data:()=>clone(data.get(path)),ref:ref(path)});
 const query=(name,filters=[],sort='',max=Infinity)=>({doc:id=>ref(name+'/'+id),where:(key,op,v)=>query(name,[...filters,[key,op,v]],sort,max),orderBy:key=>query(name,filters,key,max),limit:n=>query(name,filters,sort,n),get:async()=>{let docs=[...data.keys()].filter(k=>k.startsWith(name+'/')&&k.split('/').length===2).map(snap).filter(s=>filters.every(([k,op,v])=>op==='=='?s.data()[k]===v:s.data()[k]<=v));if(sort)docs.sort((a,b)=>a.data()[sort]-b.data()[sort]);return {docs:docs.slice(0,max)}}});
 return {data,collection:name=>query(name),runTransaction:fn=>{const result=tail.then(async()=>{const writes=[];const value=await fn({get:r=>r.get(),set:(r,v,o)=>writes.push(()=>merge(r.path,v,o?.merge)),update:(r,v)=>writes.push(()=>merge(r.path,v,true))});writes.forEach(f=>f());return value});tail=result.catch(()=>{});return result}};
}
function setup(count=2){
 const seed={'email_campaigns/c':{name:'Campaign',subject:'Hello',html:'<body>Message</body>',status:'draft',audience:{}}};for(let i=0;i<count;i++)seed['subscribers/s'+i]={email:`person${i}@example.com`,status:'active',source:'footer',market:'za'};
 const db=database(seed),requests=[];let clock=Date.now(),error;
 const env={RESEND_API_KEY:'test',RESEND_WEBHOOK_SECRET:'whsec_'+Buffer.from('test-signing-secret').toString('base64')};
 const engine=createEngine({db,FieldValue:{serverTimestamp:()=>({seconds:1}),increment:n=>({increment:n})},requireAdmin:async req=>{if(!req.admin)throw Object.assign(Error('Forbidden'),{status:403})},cors:()=>false,env,now:()=>clock,send:async(messages,key)=>{requests.push({messages,key});if(error)throw error;return messages.map((_,i)=>({id:'mail-'+requests.length+'-'+i}))}});
 const call=async(fn,body={},admin=true)=>{const res={status(code){this.code=code;return this},json(body){this.body=body;return this},send(body){this.body=body;return this}};await engine[fn]({method:'POST',body,admin},res);return res};
 return {db,engine,call,requests,env,time:n=>clock+=n,fail:e=>error=e,job:()=>db.collection('campaign_jobs').doc([...db.data.keys()].find(k=>k.startsWith('campaign_jobs/')).split('/')[1])};
}
test('audience filters agree with the browser and deduplicate consented addresses',async()=>{
 const subs=[{id:'1',email:'ONE@example.com',source:'footer',market:'za'},{id:'2',email:'one@example.com',source:'footer',market:'za'},{id:'3',email:'pending@example.com',status:'pending'},{id:'4',email:'bad@example.com',suppressed:true}],orders=[{customer:{email:'one@example.com'},paymentStatus:'paid',status:'shipped'}],f={source:'footer',market:'za',purchase:'buyers',orderStatus:'shipped'};
 assert.equal(selectAudience(subs,orders,f).length,1);const {campaignAudience}=await import('../src/utils/campaignAudience.js');assert.deepEqual(selectAudience(subs,orders,f).map(s=>s.email),campaignAudience(subs,orders,f).map(s=>s.email.trim().toLowerCase()));
});
test('scheduled campaign waits, rejects duplicate queueing and accepts more than 5,000 recipients',async()=>{
 const app=setup(5001),when=new Date(Date.now()+3600000).toISOString();assert.equal((await app.call('enqueue',{campaignId:'c',scheduledAt:when})).code,200);assert.equal(app.db.data.get('email_campaigns/c').totalBatches,51);assert.equal((await app.call('enqueue',{campaignId:'c'})).code,409);await app.engine.processJob(app.job());assert.equal(app.requests.length,0);app.time(3601000);await app.engine.processJob(app.job());assert.equal(app.requests.length,1);assert.equal(app.requests[0].messages.length,100);assert.equal(app.db.data.get('email_campaigns/c').acceptedCount,100);
});
test('concurrent workers only submit a batch once and recheck unsubscribe and suppression',async()=>{
 const app=setup(3);await app.call('enqueue',{campaignId:'c'});app.db.data.get('subscribers/s1').status='unsubscribed';app.db.data.set('email_suppressions/'+crypto.createHash('sha256').update('person2@example.com').digest('hex'),{reason:'bounced'});await Promise.all([app.engine.processJob(app.job()),app.engine.processJob(app.job())]);assert.equal(app.requests.length,1);assert.equal(app.requests[0].messages.length,1);assert.match(app.requests[0].messages[0].html,/Unsubscribe/);assert.equal(app.db.data.get('email_campaigns/c').skippedCount,2);
});
test('cancelled schedules do not send and non-admins cannot queue',async()=>{const app=setup();assert.equal((await app.call('enqueue',{campaignId:'c'},false)).code,403);await app.call('enqueue',{campaignId:'c'});await app.call('cancel',{campaignId:'c'});await app.engine.processJob(app.job());assert.equal(app.requests.length,0);assert.equal(app.db.data.get('email_campaigns/c').status,'cancelled');});
test('uncertain batches require explicit provider evidence before retry',async()=>{
 const app=setup();await app.call('enqueue',{campaignId:'c'});app.fail(Object.assign(Error('Network interrupted'),{unknown:true}));await app.engine.processJob(app.job());assert.equal(app.db.data.get('email_campaigns/c').status,'delivery_unknown');await app.engine.processJob(app.job());assert.equal(app.requests.length,1);assert.equal((await app.call('reconcile',{campaignId:'c',batchIndex:0,decision:'not_accepted'})).code,400);await app.call('reconcile',{campaignId:'c',batchIndex:0,decision:'not_accepted',note:'Provider logs confirm no accepted mail'});app.fail(null);await app.engine.processJob(app.job());assert.equal(app.requests.length,2);assert.equal(app.requests[0].key,app.requests[1].key);assert.deepEqual(app.requests[0].messages,app.requests[1].messages);
});
test('webhook rejects tampering, old timestamps and invalid signatures',()=>{
 const secret='whsec_'+Buffer.from('secret').toString('base64'),raw=Buffer.from('{"type":"email.delivered"}'),timestamp=String(Math.floor(Date.now()/1000)),id='evt1',signature='v1,'+crypto.createHmac('sha256',Buffer.from('secret')).update(id+'.'+timestamp+'.').update(raw).digest('base64'),headers={'svix-id':id,'svix-timestamp':timestamp,'svix-signature':signature};assert.equal(verifyWebhook(raw,headers,secret).type,'email.delivered');assert.throws(()=>verifyWebhook(Buffer.from('{}'),headers,secret));assert.throws(()=>verifyWebhook(raw,headers,secret,Date.now()+360000));
});
test('delivery webhooks count once, tolerate early events and suppress bounces',async()=>{
 const app=setup(1);await app.call('enqueue',{campaignId:'c'});
 const event=async(type,id)=>{const body=Buffer.from(JSON.stringify({type,data:{email_id:'mail-1-0',to:['person0@example.com']}})),ts=String(Math.floor(Date.now()/1000)),headers={'svix-id':id,'svix-timestamp':ts,'svix-signature':'v1,'+crypto.createHmac('sha256',Buffer.from('test-signing-secret')).update(id+'.'+ts+'.').update(body).digest('base64')},r={status(c){this.code=c;return this},send(){}};await app.engine.webhook({method:'POST',rawBody:body,get:k=>headers[k]},r);assert.equal(r.code,200);};
 await event('email.delivered','early');await app.engine.processJob(app.job());assert.equal(app.db.data.get('email_campaigns/c').deliveredCount,1);await event('email.delivered','early');await event('email.delivered','second');assert.equal(app.db.data.get('email_campaigns/c').deliveredCount,1);await event('email.bounced','bounce');assert.equal(app.db.data.get('email_campaigns/c').bouncedCount,1);assert.equal(app.db.data.get('subscribers/s0').suppressed,true);
});

test('order notices only target affected customers and never run as advertisements',async()=>{
 const app=setup(0);app.db.data.set('orders/o1',{customer:{email:'affected@example.com'},status:'shipped',market:'za'});app.db.data.set('orders/o2',{customer:{email:'other@example.com'},status:'processing',market:'za'});Object.assign(app.db.data.get('email_campaigns/c'),{category:'advertisement',audience:{kind:'order_customers',orderStatus:'shipped'}});assert.equal((await app.call('enqueue',{campaignId:'c'})).code,400);app.db.data.get('email_campaigns/c').category='update';await app.call('enqueue',{campaignId:'c'});await app.engine.processJob(app.job());assert.deepEqual(app.requests[0].messages[0].to,['affected@example.com']);assert.equal(app.requests[0].messages[0].headers,undefined);
});
test('confirmed acceptance reconciliation does not send again or resume a cancelled campaign',async()=>{
 const app=setup();await app.call('enqueue',{campaignId:'c'});app.fail(Object.assign(Error('Timeout'),{unknown:true}));await app.engine.processJob(app.job());const result=await app.call('reconcile',{campaignId:'c',batchIndex:0,decision:'accepted',note:'Provider records checked',providerIds:['confirmed-1','confirmed-2']});assert.equal(result.code,200);assert.equal(app.db.data.get('email_campaigns/c').acceptedCount,2);await app.engine.processJob(app.job());assert.equal(app.requests.length,1);
 const cancelled=setup();await cancelled.call('enqueue',{campaignId:'c'});cancelled.fail(Object.assign(Error('Timeout'),{unknown:true}));await cancelled.engine.processJob(cancelled.job());await cancelled.call('cancel',{campaignId:'c'});assert.equal((await cancelled.call('reconcile',{campaignId:'c',batchIndex:0,decision:'not_accepted',note:'Checked'})).code,409);
});

test('non-variant inventory is reserved atomically and restored once',async()=>{
 const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync('functions/index.js','utf8');
 const db=database({'products/tee':{name:'Tee',price:250,stock:3,active:true}});let sequence=0;const collection=db.collection;db.collection=name=>{const q=collection(name),doc=q.doc;q.doc=id=>doc(id||'generated-'+(++sequence));return q};
 const context={Map,Number,Date,Math,Error,require,admin:{firestore:()=>db},FieldValue:{serverTimestamp:()=>1},marketConfig:()=>({country:'South Africa',currency:'ZAR'}),marketRate:async()=>1,productAvailableInMarket:()=>true,convertMoney:(v,r)=>v*r};
 const begin=source.indexOf('async function createOrderIdempotent('),end=source.indexOf('\nexports.adminInventoryAdjust',begin);vm.runInNewContext(source.slice(begin,end),context);
 const restoreBegin=source.indexOf('async function restoreOrderInventory('),restoreEnd=source.indexOf('\nexports.verifyYocoPayment',restoreBegin);vm.runInNewContext(source.slice(restoreBegin,restoreEnd),context);
 const args={user:{uid:'u'},customer:{email:'buyer@example.com',firstName:'Buyer',lastName:'Test',phone:'0712345678',address:'Main Road',city:'Cape Town',postalCode:'7700',province:'Western Cape'},quote:{items:[{productId:'tee',quantity:2,unitPrice:250,lineTotal:500}],subtotal:500,shipping:70,total:570},paymentMethod:'bank',idempotencyKey:'first',market:'za'};
 const first=await context.createOrderIdempotent(args);assert.equal(db.data.get('products/tee').stock,1);await context.createOrderIdempotent(args);assert.equal(db.data.get('products/tee').stock,1);await assert.rejects(context.createOrderIdempotent({...args,idempotencyKey:'second'}),/Stock changed/);await context.restoreOrderInventory(first.orderRef);assert.equal(db.data.get('products/tee').stock,3);await context.restoreOrderInventory(first.orderRef);assert.equal(db.data.get('products/tee').stock,3);
});

test('a late uncertain response preserves campaign cancellation',async()=>{const app=setup();await app.call('enqueue',{campaignId:'c'});app.fail(Object.assign(Error('Timeout'),{unknown:true}));await app.engine.processJob(app.job());await app.call('cancel',{campaignId:'c'});app.db.data.get(app.job().path).status='processing';app.db.data.get(app.job().path).startedAt=0;await app.engine.tick();assert.equal(app.db.data.get('email_campaigns/c').status,'cancelled');assert.equal(app.requests.length,1);});

test('free backend batches one recipient and defers quota exhaustion without failed deliveries',async()=>{
 const app=setup(2);Object.assign(app.env,{CAMPAIGN_BATCH_SIZE:'1',CAMPAIGN_TICK_LIMIT:'1',CAMPAIGN_AUDIENCE_LIMIT:'1000'});await app.call('enqueue',{campaignId:'c'});assert.equal(app.db.data.get('email_campaigns/c').totalBatches,2);app.fail(Object.assign(Error('Daily quota reached'),{deferred:true}));await app.engine.processJob(app.job());assert.equal((await app.job().get()).data().status,'pending');assert.equal(app.db.data.get('email_campaigns/c').status,'queued');assert.equal(app.db.data.get('email_campaigns/c').failedCount,0);app.fail(null);app.time(3600001);await app.engine.processJob(app.job());assert.equal(app.requests.at(-1).messages.length,1);
});
