const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {modules,fixture}=require('./admin.cjs');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH,args:['--no-sandbox']}:{})}),context=await browser.newContext(),calls=[];let signupFails=false,testFails=false;
 await context.addInitScript(()=>{if(window===window.top)localStorage.setItem('drixel_market','za')});
 const data={...fixture,email_campaigns:[...fixture.email_campaigns,{id:'scheduled-check',name:'Scheduled notice',subject:'Schedule',category:'update',status:'scheduled'},{id:'uncertain-check',name:'Uncertain notice',subject:'Check delivery',category:'update',status:'delivery_unknown',lastError:'Batch 0: uncertain',recipientCount:2}],subscribers:[...fixture.subscribers,{id:'pending',email:'pending@example.com',status:'pending'},{id:'left',email:'left@example.com',status:'unsubscribed'}]};
 await context.route('**/*',async route=>{
  const url=new URL(route.request().url()),match=url.pathname.match(/firebase_(app|auth|firestore)\.js$/);
  if(match){let code=modules[match[1]];if(match[1]==='firestore')code=code.replace(JSON.stringify(fixture),JSON.stringify(data));return route.fulfill({contentType:'application/javascript',body:code});}
  if(url.pathname==='/api/admin/security/status')return route.fulfill({json:{available:true,verified:true,enrolled:true,expiresAt:Date.now()+900000}});if(url.pathname.startsWith('/api/')){
   const body=route.request().postDataJSON();calls.push({path:url.pathname,body});
   if(url.pathname==='/api/subscribe'){if(signupFails)return route.fulfill({contentType:'application/json',body:'<!doctype html>fallback'});const address=body.email.trim().toLowerCase();if(!data.subscribers.some(s=>s.email===address))data.subscribers.push({id:'signup',email:address,status:'active',source:body.source});return route.fulfill({contentType:'application/json',body:JSON.stringify({success:true,message:"You're on the list."})});}
   if(url.pathname==='/api/send-email')return route.fulfill({status:testFails?503:200,contentType:'application/json',body:JSON.stringify(testFails?{success:false,message:'Sending domain is not verified.'}:{success:true,data:'provider-test-id'})});
   return route.fulfill({contentType:'application/json',body:JSON.stringify(url.pathname==='/api/queue-campaign'?{success:true,queued:true,recipientCount:2}:url.pathname==='/api/cancel-campaign'?{success:true,cancelled:true}:url.pathname==='/api/reconcile-campaign'?{success:true,reconciled:true}:{rate:1})});
  }
  if(url.hostname==='127.0.0.1'&&/^\/assets\/campaigns\/campaign-\d+\.jpeg$/.test(url.pathname))return route.continue();
  if(/\.(png|jpg|jpeg)$/i.test(url.pathname))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="640" height="700"><rect width="640" height="700" fill="#ccc"/><text x="40" y="300" font-size="64">DRIXEL</text></svg>'});
  if(url.hostname==='127.0.0.1')return route.continue();return route.fulfill({body:''});
 });
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/za');const form=page.locator('form.dx-newsletter').first();await form.locator('input[type=email]').fill('new-person@example.com');await form.getByRole('button',{name:'Join the list'}).click();await form.getByRole('status').filter({hasText:"You're on the list"}).waitFor();
 await page.goto('http://127.0.0.1:5173/za/admin/marketing/subscribers');await page.getByText('new-person@example.com',{exact:true}).waitFor();assert.equal(data.subscribers.filter(s=>s.email==='new-person@example.com').length,1);
 await page.goto('http://127.0.0.1:5173/za/admin/marketing/updates');await page.locator('.mk-designed-card').first().waitFor();assert.equal(await page.locator('.mk-designed-card').count(),16);await page.getByRole('button',{name:'Delivery',exact:true}).click();assert.equal(await page.locator('.mk-designed-card').count(),3);await page.getByLabel('Search templates').fill('weather');assert.equal(await page.locator('.mk-designed-card').count(),1);await page.locator('.mk-designed-card').click();await page.getByLabel('Internal campaign name').fill('Weather notice');await page.getByLabel('Announcement message').fill('Confirmed weather delay in Cape Town.');await page.getByLabel('Details / dates / next steps').fill('Next update: tomorrow at 09:00 SAST.');await page.frameLocator('.mk-preview iframe').getByText('Confirmed weather delay in Cape Town.',{exact:true}).waitFor();await page.getByRole('button',{name:'Mobile',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.mk-preview iframe').getBoundingClientRect().width<=390);
 await page.getByLabel('Preview recipient').fill('preview@example.com');await page.getByRole('button',{name:'Send test email',exact:true}).click();await page.locator('.dx-dialog-message').filter({hasText:'Preview accepted'}).waitFor();assert.equal(calls.at(-1).path,'/api/send-email');assert.deepEqual(calls.at(-1).body.to,['preview@example.com']);assert.equal(calls.filter(c=>c.path==='/api/send-campaign').length,0);await page.getByRole('button',{name:'Close',exact:true}).click();
 testFails=true;await page.getByRole('button',{name:'Send test email',exact:true}).click();await page.locator('.dx-dialog-message').filter({hasText:'domain is not verified'}).waitFor();await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.locator('.dx-dialog-message').filter({hasText:'draft saved'}).waitFor();await page.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await page.evaluate(()=>window.__adminWrites.at(-1).payload.category),'update');assert.match(await page.getByRole('button',{name:'Send to 2',exact:true}).innerText(),/2/);
 await page.getByRole('combobox',{name:/Signup source/}).selectOption('checkout');
 assert.equal(await page.getByRole('button',{name:'Send to 0',exact:true}).isDisabled(),true);
 await page.getByRole('combobox',{name:/Signup source/}).selectOption('');
 const scheduledLocal=new Date(Date.now()+86400000+7200000).toISOString().slice(0,16);await page.getByLabel('Send time (SAST, optional)').fill(scheduledLocal);
 await page.getByRole('button',{name:'Send to 2',exact:true}).click();
 await page.locator('.dx-dialog-message').filter({hasText:'Scheduled for'}).waitFor();
 await page.getByRole('button',{name:'Send campaign',exact:true}).click();
 await page.locator('.dx-dialog-message').filter({hasText:'scheduled for 2 recipients'}).waitFor();
 const queued=calls.find(c=>c.path==='/api/queue-campaign');assert.equal(queued.body.scheduledAt,new Date(scheduledLocal+':00+02:00').toISOString());
 assert.equal((await page.evaluate(()=>window.__adminWrites.at(-1).payload.audience.purchase)),'all');
 await page.getByRole('button',{name:'Close',exact:true}).click();

 await page.getByRole('button',{name:'Campaigns',exact:true}).click();
 await page.locator('.mk-result-list article').filter({hasText:'Scheduled notice'}).getByRole('button',{name:'Cancel remaining send'}).click();await page.getByRole('button',{name:'Cancel campaign',exact:true}).click();await page.locator('.dx-dialog-message').filter({hasText:'batches cancelled'}).waitFor();assert.equal(calls.at(-1).body.campaignId,'scheduled-check');await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Reconcile batch'}).click();await page.getByLabel('Batch index (shown in the error)').fill('0');await page.getByRole('combobox',{name:/Provider result/}).selectOption('not_accepted');await page.getByLabel('Evidence / provider log reference').fill('Controlled provider logs checked');await page.setViewportSize({width:320,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true);await page.getByRole('button',{name:'Save reconciliation'}).click();await page.locator('.dx-dialog-message').filter({hasText:'Batch reconciled'}).waitFor();assert.equal(calls.at(-1).body.decision,'not_accepted');await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Composer',exact:true}).click();
 for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true);const overflow=await page.frameLocator('.mk-preview iframe').locator('body').evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert.equal(overflow,false);}
 if(process.env.SCREENSHOT_DIR){await page.setViewportSize({width:1440,height:1100});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:process.env.SCREENSHOT_DIR+'/marketing-update-composer.png',fullPage:false});}
 await page.goto('http://127.0.0.1:5173/za/admin/marketing/email');await page.locator('.mk-designed-card').first().waitFor();assert.equal(await page.locator('.mk-designed-card').count(),18);
 for(const frame of page.frames().filter(f=>f.parentFrame())){await frame.waitForFunction(()=>[...document.images].every(img=>img.complete&&img.naturalWidth>0));const srcs=await frame.locator('img').evaluateAll(imgs=>imgs.map(img=>img.src));assert.equal(srcs.every(src=>src.startsWith('http://127.0.0.1:5173/')),true);}
 await page.getByRole('button',{name:'New Season',exact:false}).click();await page.frameLocator('.mk-preview iframe').locator('img').first().waitFor();await page.frameLocator('.mk-preview iframe').locator('body').evaluate(async()=>{await Promise.all([...document.images].map(img=>img.decode()))});
 await page.getByLabel('Preview recipient').fill('preview@example.com');testFails=false;await page.getByRole('button',{name:'Send test email',exact:true}).click();await page.locator('.dx-dialog-message').filter({hasText:'Preview accepted'}).waitFor();assert.doesNotMatch(calls.at(-1).body.html,/127\.0\.0\.1|localhost/);assert.match(calls.at(-1).body.html,/https:\/\/raw.githubusercontent.com\/andziboyrsa702-spec\/drixelsa.github.io\/768eb98e781d23c7223bad847b988c4093548ea8\/public\/assets\/campaigns/);await page.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Templates',exact:true}).click();
 if(process.env.SCREENSHOT_DIR){await page.setViewportSize({width:1440,height:1100});await page.evaluate(()=>window.scrollTo(0,0));await page.frameLocator('.mk-designed-card iframe').first().getByRole('heading',{name:'THE NEXT CHAPTER.'}).waitFor();await page.screenshot({path:process.env.SCREENSHOT_DIR+'/marketing-template-library.png',fullPage:false});await page.setViewportSize({width:390,height:900});await page.waitForFunction(()=>getComputedStyle(document.querySelector('.ra-sidebar')).visibility==='hidden');await page.screenshot({path:process.env.SCREENSHOT_DIR+'/marketing-template-library-mobile.png',fullPage:false});}
 signupFails=true;await page.goto('http://127.0.0.1:5173/za');const again=page.locator('form.dx-newsletter').first();await again.locator('input[type=email]').fill('failed@example.com');await again.getByRole('button',{name:'Join the list'}).click();await again.getByRole('status').filter({hasText:'did not confirm'}).waitFor();assert.equal(data.subscribers.some(s=>s.email==='failed@example.com'),false);
 const {EMAIL_TEMPLATES,emailHtml}=await import('../src/admin-react/marketingTemplates.js');for(const width of [320,640]){await page.setViewportSize({width,height:900});for(const t of EMAIL_TEMPLATES){await page.setContent(emailHtml(t));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true,t.id+' email overflow at '+width);}}
 await browser.close();assert.deepEqual(errors,[]);console.log('Marketing flows passed: signup → audience, 34 templates, update filtering/composition, mobile email render, test email success/failure, schedule/audience controls, cancellation/reconciliation, save category, pending exclusion, false signup success prevented.');
})().catch(e=>{console.error(e);process.exit(1)});
