const {chromium}=require('playwright'),assert=require('node:assert/strict'),{fixture,modules}=require('./admin.cjs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox']}),context=await browser.newContext(),page=await context.newPage(),errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));
 const bank={enabled:true,bankName:'Test Bank',bankAccountHolder:'Drixel Example',bankAccountNumber:'123456789',bankBranchCode:'123456',bankAccountType:'Business'};
 const data={...fixture,orders:[{...fixture.orders[0],id:'order1',orderNumber:'DX-TEST',customer:{uid:'admin1'},paymentStatus:'pending',paymentMethod:'bank',bankInstructions:bank}],settings:fixture.settings.map(x=>x.id==='store'?{...x,...bank,bankTransferEnabled:true}:x)};
 let reject=true,payment='pending';await context.addInitScript(()=>localStorage.setItem('drixel_cart',JSON.stringify([{productId:'tee',sku:'TEE-BLK-M',name:'Drixel Tee',size:'M',color:'Black',quantity:1,price:250}])));
 await context.route('**/*',route=>{const u=new URL(route.request().url()),m=u.pathname.match(/firebase_(app|auth|firestore)\.js$/);if(m){let code=modules[m[1]];if(m[1]==='firestore')code=code.replace(JSON.stringify(fixture),JSON.stringify(data)).replace('String(row[f.field])','String(f.field.split(".").reduce((value,key)=>value?.[key],row))');return route.fulfill({contentType:'application/javascript',body:code});}if(u.pathname==='/api/payments/config')return route.fulfill({json:{bank,yoco:{enabled:true,mode:'test'},snapscan:{enabled:true,snapCode:'DRIXEL1'}}});if(u.pathname==='/api/checkout-quote')return route.fulfill({json:{items:[{productId:'tee',name:'Drixel Tee',quantity:1,lineTotal:250}],total:320,subtotal:250,shipping:70}});if(u.pathname==='/api/create-order'){calls.push(JSON.parse(route.request().postData()));return route.fulfill(reject?{status:503,json:{message:'Payment service unavailable. Your bag is saved.'}}:{status:201,json:{orderNumber:'DX-TEST',orderId:'order1'}});}if(u.pathname==='/api/payments/yoco/verify')return route.fulfill({json:{paid:payment==='paid',testPaid:payment==='test_paid',paymentStatus:payment,orderNumber:'DX-TEST'}});if(u.pathname==='/api/admin/security/authenticator/status')return route.fulfill({json:{available:true,verified:true,enrolled:true,expiresAt:Date.now()+900000}});if(u.pathname.startsWith('/api/'))return route.fulfill({json:{rate:1,countryCode:'ZA'}});if(u.hostname==='127.0.0.1')return route.continue();return route.fulfill({body:''});});
 for(let attempt=0;attempt<50;attempt++){try{await fetch('http://127.0.0.1:5173/');break;}catch{await new Promise(resolve=>setTimeout(resolve,100));}}
 await page.goto('http://127.0.0.1:5173/za/checkout');await page.getByRole('radio',{name:/Bank transfer/}).waitFor();await page.getByRole('radio',{name:/Card payment/}).check();assert.equal(await page.getByRole('button',{name:'Continue to secure payment'}).count(),1);await page.getByRole('radio',{name:'SnapScan',exact:false}).check();assert.equal(await page.getByRole('button',{name:'Continue to SnapScan'}).count(),1);await page.getByRole('radio',{name:/Bank transfer/}).check();
 for(const width of [360,768,1440]){await page.setViewportSize({width,height:1000});if(process.env.SCREENSHOT_DIR)await page.screenshot({path:process.env.SCREENSHOT_DIR+"/payment-checkout-"+width+".png",fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`Checkout overflow at ${width}`);}
 for(const [label,value] of [['First name','Test'],['Last name','Buyer'],['Phone','0610000000'],['Street address','10 Main Road'],['City','Cape Town'],['Postal / ZIP code','7700']])await page.getByLabel(label,{exact:true}).fill(value);await page.locator('select[name=province]').selectOption({label:'Western Cape'});
 await page.getByRole('button',{name:'Place bank-transfer order'}).click();await page.getByText('Payment service unavailable. Your bag is saved.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('drixel_cart')).length),1);reject=false;await page.getByRole('button',{name:'Place bank-transfer order'}).click();await page.waitForURL('**/order-confirmation/DX-TEST');await page.getByRole('heading',{name:'What happens next'}).waitFor();await page.getByText('123456789',{exact:true}).waitFor();assert.equal(calls[0].idempotencyKey,calls[1].idempotencyKey);assert.equal(calls[1].paymentMethod,'bank');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('drixel_cart')).length===0);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('drixel_cart')).length),0);
 await page.goto('http://127.0.0.1:5173/za/payment/yoco/cancel?order=order1');await page.getByText(/Payment was cancelled/).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('drixel_cart')).length),1);payment='test_paid';await page.getByRole('button',{name:'Check confirmation again'}).click();await page.waitForURL('**/order-confirmation/DX-TEST');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('drixel_cart')).length===0);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('drixel_cart')).length),0);
 await page.goto('http://127.0.0.1:5173/za/admin/settings/store');await page.getByLabel('Account number',{exact:true}).waitFor();assert.equal(await page.getByLabel('Account number',{exact:true}).inputValue(),'123456789');for(const width of [360,768,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`Admin overflow at ${width}`);}assert.deepEqual(errors,[]);await browser.close();console.log('Payment browser checks passed: mobile layout, method choices, failed retry preserves bag and key, bank instructions, cancellation, test confirmation, admin bank details.');})().catch(e=>{console.error(e);process.exit(1)});
