const {chromium}=require('playwright'),assert=require('node:assert/strict'),{fixture,modules}=require('./admin.cjs'),crypto=require('node:crypto');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox']}),context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let enrolled=false,verified=false,confirmSession=true,credentialId,passwordAttempts=0;
 await context.route('**/*',async route=>{const u=new URL(route.request().url()),m=u.pathname.match(/firebase_(app|auth|firestore)\.js$/);
  if(m){let code=modules[m[1]];if(m[1]==='auth'){code=code.replace('export const signInWithCustomToken=async()=>({user});', 'export const signInWithCustomToken=async()=>{user={...makeUser(),getIdTokenResult:async()=>({claims:{admin:true,drixel_admin_verified_at:Math.floor(Date.now()/1000),drixel_admin_key_version:\"current\"}}),getIdToken:async()=>\"verified-token\"};return{user}};');code=code.replace('export const signInWithEmailAndPassword=async()=>{','export const signInWithEmailAndPassword=async()=>{if(localStorage.getItem("security-fail-login"))throw Object.assign(Error("Wrong password"),{code:"auth/invalid-credential"});');}return route.fulfill({contentType:'application/javascript',body:code});}
  if(u.pathname==='/api/admin/security/status')return route.fulfill({json:{available:true,enrolled,verified:verified&&confirmSession&&route.request().headers().authorization==='Bearer verified-token',expiresAt:Date.now()+900000}});
  if(u.pathname==='/api/admin/security/options'){const {kind}=route.request().postDataJSON(),challenge=crypto.randomBytes(32).toString('base64url');return route.fulfill({json:{challengeId:crypto.randomUUID(),optionsJSON:kind==='register'?{challenge,rp:{name:'Drixel SA Admin',id:'localhost'},user:{id:Buffer.from('admin1').toString('base64url'),name:'admin@example.com',displayName:'Admin'},pubKeyCredParams:[{alg:-7,type:'public-key'}],authenticatorSelection:{userVerification:'required',residentKey:'preferred'},attestation:'none',timeout:60000}:{challenge,rpId:'localhost',allowCredentials:[{id:credentialId,type:'public-key'}],userVerification:'required',timeout:60000}}});}
  if(u.pathname==='/api/admin/security/verify'){const body=route.request().postDataJSON();assert.equal(body.credential.type,'public-key');credentialId=body.credential.id;enrolled=true;verified=true;return route.fulfill({json:{verified:true,customToken:'mock-token',recoveryCodes:body.kind==='register'?['a'.repeat(32), 'b'.repeat(32)]:[]}});}
  if(u.pathname.startsWith('/api/'))return route.fulfill({json:{success:true}});
  if(/\.(png|jpe?g|webp)$/i.test(u.pathname))return route.fulfill({body:''});
  if(['127.0.0.1','localhost'].includes(u.hostname))return route.continue();return route.fulfill({body:''});
 });
 const cdp=await context.newCDPSession(page);await cdp.send('WebAuthn.enable');await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 await page.goto('http://localhost:5173/za/admin');await page.getByRole('button',{name:'Register passkey',exact:true}).click();await page.getByRole('heading',{name:'Save your recovery codes'}).waitFor().catch(async e=>{console.error(await page.locator('body').innerText());throw e});assert.equal(await page.locator('.admin-recovery-codes code').count(),2);await page.getByRole('button',{name:'I saved my codes — continue'}).click();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();
 verified=false;confirmSession=false;await page.reload();await page.getByRole('button',{name:'Verify passkey',exact:true}).click();await page.getByRole('alert').filter({hasText:'administrator session was not confirmed'}).waitFor();confirmSession=true;await page.getByRole('button',{name:'Verify passkey',exact:true}).click();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();
 await context.route('**/api/admin/security/status',route=>route.fulfill({status:404,json:{message:'Security service unavailable'}}));await page.reload();await page.getByRole('alert').filter({hasText:'Security service unavailable'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Dashboard',exact:true}).count(),0);await context.unroute('**/api/admin/security/status');
 await page.evaluate(()=>{localStorage.setItem('admin-auth' ,'signed-out');localStorage.setItem('security-fail-login','true')});await page.goto('http://localhost:5173/za/member/login');await page.locator('[name=email]').fill('wrong@example.com');await page.locator('[name=password]').fill('wrong-password');for(let i=0;i<3;i++){await page.getByRole('button',{name:'Sign in',exact:true}).last().click();await page.waitForTimeout(100)}await page.getByRole('button',{name:'Sign-in paused',exact:true}).waitFor();assert.ok(await page.getByRole('button',{name:'Sign-in paused',exact:true}).isDisabled());await page.reload();assert.ok(await page.getByRole('button',{name:'Sign-in paused',exact:true}).isDisabled());assert.equal(errors.length,0,JSON.stringify(errors));await browser.close();console.log('Security browser passed: device registration, recovery-code acknowledgement, device verification and three-attempt persistent login pause.');
})().catch(e=>{console.error(e);process.exit(1)});
