const {chromium}=require('playwright'),assert=require('node:assert/strict'),{modules}=require('./admin.cjs');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let enrolled=false,verified=false,confirmSession=true,account='admin1',setupAccount;
 await context.route('**/*',async route=>{const u=new URL(route.request().url()),m=u.pathname.match(/firebase_(app|auth|firestore)\.js$/);
  if(m){let code=modules[m[1]];if(m[1]==='auth'){code=code.replace('export const signInWithCustomToken=async()=>({user});', 'export const signInWithCustomToken=async()=>{user={...makeUser(),getIdToken:async()=>"verified-token"};return{user}};');code=code.replace('export const signInWithEmailAndPassword=async()=>{','export const signInWithEmailAndPassword=async()=>{if(localStorage.getItem("security-fail-login"))throw Object.assign(Error("Wrong password"),{code:"auth/invalid-credential"});');}return route.fulfill({contentType:'application/javascript',body:code});}
  if(u.pathname==='/api/admin/security/authenticator/status')return route.fulfill({json:{available:true,enrolled:enrolled&&account===setupAccount,verified:verified&&confirmSession&&account===setupAccount&&route.request().headers().authorization==='Bearer verified-token',expiresAt:Date.now()+900000}});
  if(u.pathname==='/api/admin/security/authenticator/setup'){setupAccount=account;return route.fulfill({json:{challengeId:'setup',secret:'JBSWY3DPEHPK3PXP',account:'admin@example.com',issuer:'Drixel SA Admin'}});}
  if(u.pathname==='/api/admin/security/authenticator/verify'){const body=route.request().postDataJSON();if(body.code!=='123456')return route.fulfill({status:403,json:{message:'The code is incorrect or expired.'}});const first=!enrolled;enrolled=true;verified=true;return route.fulfill({json:{customToken:'mock-token',recoveryCodes:first?['a'.repeat(32),'b'.repeat(32)]:[]}});}
  if(u.pathname==='/api/admin/security/authenticator/recover'){assert.equal(route.request().postDataJSON().code,'a'.repeat(32));verified=true;return route.fulfill({json:{customToken:'mock-token'}});}
  if(u.pathname.startsWith('/api/'))return route.fulfill({json:{success:true}});
  if(/\.(png|jpe?g|webp)$/i.test(u.pathname))return route.fulfill({body:''});
  if(['127.0.0.1','localhost'].includes(u.hostname))return route.continue();return route.fulfill({body:''});
 });
 await page.goto('http://127.0.0.1:5173/za/admin');await page.getByRole('button',{name:'Start authenticator setup',exact:true}).click();await page.getByText('JBSWY3DPEHPK3PXP',{exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'Dashboard',exact:true}).count(),0);
 await page.getByLabel('Authenticator code',{exact:true}).fill('000000');await page.getByRole('button',{name:'Confirm authenticator setup',exact:true}).click();await page.getByRole('alert').filter({hasText:'incorrect'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Dashboard',exact:true}).count(),0);
 await page.getByLabel('Authenticator code',{exact:true}).fill('123456');await page.getByRole('button',{name:'Confirm authenticator setup',exact:true}).click();await page.getByRole('heading',{name:'Save your recovery codes'}).waitFor();assert.equal(await page.locator('.admin-recovery-codes code').count(),2);await page.getByRole('button',{name:'I saved my codes — continue'}).click();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();
 verified=false;confirmSession=false;await page.reload();await page.getByLabel('Authenticator code',{exact:true}).fill('123456');await page.getByRole('button',{name:'Verify and continue',exact:true}).click();await page.getByRole('alert').filter({hasText:'session could not be confirmed'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Dashboard',exact:true}).count(),0);confirmSession=true;await page.getByLabel('Authenticator code',{exact:true}).fill('123456');await page.getByRole('button',{name:'Verify and continue',exact:true}).click();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();
 verified=false;await page.reload();await page.getByRole('button',{name:'Use a recovery code',exact:true}).click();await page.getByLabel('Recovery code',{exact:true}).fill('a'.repeat(32));await page.getByRole('button',{name:'Verify and continue',exact:true}).click();await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();
 account='second-admin';verified=false;await page.reload();await page.getByRole('button',{name:'Start authenticator setup',exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'Dashboard',exact:true}).count(),0);
 await context.route('**/api/admin/security/authenticator/status',route=>route.fulfill({status:404,json:{message:'Security service unavailable'}}));await page.reload();await page.getByRole('alert').filter({hasText:'Security service unavailable'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Dashboard',exact:true}).count(),0);
 await page.evaluate(()=>{localStorage.setItem('admin-auth','signed-out');localStorage.setItem('security-fail-login','true')});await page.goto('http://127.0.0.1:5173/za/member/login');await page.locator('[name=email]').fill('wrong@example.com');await page.locator('[name=password]').fill('wrong-password');for(let i=0;i<3;i++){await page.getByRole('button',{name:'Sign in',exact:true}).last().click();await page.waitForTimeout(100)}await page.getByRole('button',{name:'Sign-in paused',exact:true}).waitFor();await page.reload();assert.ok(await page.getByRole('button',{name:'Sign-in paused',exact:true}).isDisabled());assert.equal(errors.length,0,JSON.stringify(errors));await browser.close();console.log('Security browser passed: authenticator enrollment, invalid code denial, recovery, new account setup, session confirmation and unavailable security denial.');
})().catch(e=>{console.error(e);process.exit(1)});
