const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {mockStorefront}=require('./browser-fixtures.cjs');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH,args:['--no-sandbox']} : {})});
 const context=await browser.newContext({viewport:{width:1280,height:900}});
 await mockStorefront(context);
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR:',e.message)});
 await page.goto('http://127.0.0.1:8765/checkout.html');
 await page.waitForFunction(()=>window.firebaseAuthInitialized===true);
 const values={firstName:'Alice',lastName:'Buyer',email:'alice@example.com',phone:'0123456789',address:'10 Main Road',city:'Cape Town',postalCode:'7700'};
 for(const [id,value] of Object.entries(values))await page.locator('#'+id).fill(value);
 await page.locator('#province').selectOption({label:'Western Cape'});
 await page.locator('#cookieConsent').evaluate(el=>el.remove());
 await page.locator('.btn-place-order').click();
 await page.waitForFunction(()=>document.getElementById('checkoutFeedback').textContent.includes('Review your confirmed total'));
 assert.equal(await page.locator('#payYoco').isDisabled(),true);
 assert.equal(await page.locator('#newsletterSubscription').isChecked(),false);
 assert.equal(await page.locator('#cardNumber').count(),0);
 await page.screenshot({path:process.env.SCREENSHOT_DIR ? process.env.SCREENSHOT_DIR+'/checkout-desktop.png' : '/tmp/checkout-desktop.png',fullPage:true});
 await page.locator('.btn-place-order').click();await page.waitForURL('**/orderConfirmation.html?order=order123',{waitUntil:'domcontentloaded',timeout:10000}).catch(async error=>{console.error('CHECKOUT DIAGNOSTIC',await page.evaluate(()=>({url:location.href,feedback:document.getElementById('checkoutFeedback')?.textContent,calls:window.__calls})));throw error;});
 await page.waitForFunction(()=>document.getElementById('confirmationMessage').textContent.includes('awaiting payment'));
 assert(!(await page.locator('#confirmationMessage').innerText()).includes('Payment verified'));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:process.env.SCREENSHOT_DIR ? process.env.SCREENSHOT_DIR+'/order-mobile.png' : '/tmp/order-mobile.png',fullPage:true});
 const guest=await context.newPage();guest.on('pageerror',e=>errors.push(e.message));await guest.addInitScript(()=>{window.__guest=true;});await guest.goto('http://127.0.0.1:8765/cart.html');await guest.waitForFunction(()=>window.firebaseAuthInitialized===true);assert(guest.url().endsWith('/cart.html'));
 await guest.goto('http://127.0.0.1:8765/index.html');await guest.waitForFunction(()=>window.firebaseAuthInitialized===true);
 assert(await guest.locator('h2').allTextContents().then(a=>a.findIndex(s=>s.includes('Featured Streetwear'))<a.findIndex(s=>s.includes('Seasonal Campaigns'))));
 const newsletter=guest.locator('#newsletterEmailInput');await newsletter.fill('subscriber@example.com');await guest.locator('#newsletterForm button').click();await guest.waitForFunction(()=>document.getElementById('newsletterMessage').textContent.includes('Check your inbox'));
 await guest.goto('http://127.0.0.1:8765/product.html?id=tee');await guest.waitForFunction(()=>window.PRODUCTS_DATA?.some(p=>p.id==='tee'));
 console.log(JSON.stringify({errors,checkout:'review then confirm',payment:'pending until verified',guestCart:true,newsletter:true}));
 await browser.close();assert.deepEqual(errors,[]);
})().catch(e=>{console.error(e);process.exit(1)});
