import {randomUUID} from 'node:crypto';
import {getFirestore} from './firestore.mjs';
import {adminUser} from './auth.mjs';
import {isOwner,ownerEmails,normalizedEmail,accessId} from './admin-membership.mjs';
import {apiError,consumeRateLimit} from './security.mjs';
export function createAdminTeamHandlers({db=getFirestore,authenticate=adminUser,now=Date.now}={}){
 async function context(req,write=false){const actor=await authenticate(req),database=db();if(write&&!isOwner(actor))throw apiError('Only a store owner can change administrator access.',403);if(write&&(!Number.isFinite(actor.drixel_admin_verified_at)||now()/1000-actor.drixel_admin_verified_at>300))throw apiError('For security, sign out and sign in with your authenticator again, then retry this access change.',401);await consumeRateLimit(database,{identity:actor.uid,bucket:'admin-team',limit:20,windowMs:300000,now:now()});return {actor,database};}
 async function list(req,res){const {actor,database}=await context(req);if(!isOwner(actor))return res.json({canManage:false,members:[]});const result=await database.collection('admin_access').orderBy('updatedAt','desc').limit(101).get();return res.json({canManage:true,members:await Promise.all(result.docs.slice(0,100).map(async d=>{const p=d.data(),profile=p.uid?(await database.doc('users/'+p.uid).get()).data()||{}:{};return {id:d.id,email:p.email,name:profile.name||'',photoURL:profile.photoURL??profile.providerPhotoURL??'',active:p.active===true,status:p.active===true?(p.uid?'Active':'Awaiting first sign-in'):'Removed',updatedAt:p.updatedAt||0};})),limited:result.size>100});}
 async function grant(req,res){const {actor,database}=await context(req,true),email=normalizedEmail(req.body.email);if(email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw apiError('Enter a valid email address.',400);if(ownerEmails.has(email))throw apiError('This address already belongs to a protected store owner.',409);const id=accessId(email),ref=database.doc('admin_access/'+id);await database.runTransaction(async tx=>{const old=(await tx.get(ref)).data();if(old?.active)return;tx.set(ref,{email,active:true,version:randomUUID(),uid:old?.uid||null,createdAt:old?.createdAt||now(),updatedAt:now(),updatedBy:actor.uid});tx.set(database.doc('security_events/'+randomUUID()),{actor:actor.uid,action:'admin_access_granted',target:id,at:now()});});return res.json({success:true,id,email,message:'Admin access added. Ask this person to sign in with this email, verify it and set up their authenticator.'});}
 async function remove(req,res){const {actor,database}=await context(req,true),id=String(req.body.id||'');if(!/^[a-f0-9]{64}$/.test(id))throw apiError('Choose an administrator from the list.',400);const ref=database.doc('admin_access/'+id);await database.runTransaction(async tx=>{const old=(await tx.get(ref)).data();if(!old)throw apiError('Administrator not found.',404);if(old.uid===actor.uid||old.email===normalizedEmail(actor.email)||ownerEmails.has(old.email))throw apiError('You cannot remove your own access or a protected store owner.',403);if(!old.active)return;const policyRef=old.uid?database.doc('admin_security/'+old.uid):null,policy=policyRef?(await tx.get(policyRef)).data():null;if(policy?.enabled)tx.update(policyRef,{version:randomUUID(),updatedAt:now()});tx.update(ref,{active:false,version:randomUUID(),updatedAt:now(),updatedBy:actor.uid});tx.set(database.doc('security_events/'+randomUUID()),{actor:actor.uid,action:'admin_access_removed',target:id,at:now()});});return res.json({success:true,message:'Administrator access removed. Their customer account is unchanged.'});}
 return {list,grant,remove};
}
export const adminTeamHandlers=createAdminTeamHandlers();
