import {createHash} from 'node:crypto';
import {getFirestore,FieldValue} from './firestore.mjs';
import {sendMail} from './email.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function orderMail(order,id,event){const url=(process.env.STORE_URL||'https://drixelsa.co.za')+'/'+(order.market||'za')+'/member/orders/'+encodeURIComponent(id);return {to:[order.customer.email],subject:`Drixel SA — ${order.orderNumber}: ${event}`,html:`<!doctype html><html><body style="margin:0;background:#f3f3ef;font:15px/1.7 Arial,sans-serif;color:#111"><table role="presentation" style="max-width:600px;margin:32px auto;background:white;width:100%;border-collapse:collapse"><tr><td style="padding:36px"><p style="font-size:28px;letter-spacing:4px;font-weight:bold">DRIXEL</p><p style="font-size:12px;letter-spacing:2px">ORDER UPDATE</p><h1 style="font-size:32px;line-height:1.2">${esc(event)}</h1><p>Order <strong>${esc(order.orderNumber)}</strong></p><p>Payment: ${esc(order.paymentStatus)} · Fulfilment: ${esc(order.status)}</p><p style="font-size:22px">${esc(order.displayCurrency||'ZAR')} ${Number(order.displayTotal??order.total).toFixed(2)}</p><p>${order.paymentStatus==='test_paid'?'TEST PAYMENT — no funds were collected. Do not dispatch this order.':order.paymentStatus==='paid'?'Your payment has been verified.':'Please follow the payment instructions provided at checkout. Dispatch begins after payment verification.'}</p>${order.paymentMethod==='bank'&&order.bankInstructions&&order.paymentStatus!=='paid'?'<h2>Bank transfer details</h2><p>'+['bankName','bankAccountHolder','bankAccountNumber','bankBranchCode','bankAccountType'].map(k=>esc(order.bankInstructions[k])).join('<br>')+'<br>Reference: <strong>'+esc(order.orderNumber)+'</strong><br>Amount: ZAR '+Number(order.total).toFixed(2)+'</p>':''}${order.paymentMethod==='snapscan'&&order.paymentStatus!=='paid'?'<h2>Pay with SnapScan</h2><p>Open your order below to scan its QR code or pay on your phone. The payment amount and reference are linked to this order.</p>':''}<p><a href="${esc(url)}" style="display:inline-block;background:#111;color:white;text-decoration:none;padding:14px 24px">View your order</a></p><p style="font-size:12px;color:#777">Sign in with the email used at checkout to view your order.</p></td></tr></table></body></html>`};}
export function reserveReceipt(tx,order,id){tx.set(getFirestore().doc('mail_jobs/'+hash('order/'+id+'/received')),{...orderMail(order,id,'Order received'),status:'queued',createdAt:FieldValue.serverTimestamp()});}
export async function queueOrderUpdate(id,event){const db=getFirestore(),snap=await db.doc('orders/'+id).get();if(!snap.exists)return;const order=snap.data(),ref=db.doc('mail_jobs/'+hash('order/'+id+'/'+event));try{await ref.create({...orderMail(order,id,event),status:'queued',createdAt:FieldValue.serverTimestamp()});}catch(e){if(e.code!=='ALREADY_EXISTS')throw e;}}
export async function tickOrderMail(){const db=getFirestore(),stale=await db.collection('mail_jobs').where('status','==','sending').limit(1).get();if(stale.docs[0]&&(stale.docs[0].data().firstAttemptAt||0)<Date.now()-900000)await stale.docs[0].ref.update({status:'needs_review',lastError:'Worker interrupted. Check Resend logs before retrying.'});const pending=await db.collection('mail_jobs').where('status','==','queued').limit(1).get();if(pending.empty)return false;const ref=pending.docs[0].ref;let mail;await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(snap.data()?.status!=='queued')return;mail=snap.data();tx.update(ref,{status:'sending',firstAttemptAt:Date.now()});});if(!mail)return true;try{const providerId=await sendMail(mail,'order-mail/'+ref.id);await ref.update({status:'sent',providerId,sentAt:FieldValue.serverTimestamp()});}catch(e){await ref.update({status:e.deferred?'queued':'needs_review',lastError:e.message});}return true;}
