import {snapscanConfig} from './snapscan.mjs';
import {createHash,createHmac,timingSafeEqual} from 'node:crypto';
import {getFirestore,FieldValue} from './firestore.mjs';
import {verifyIdToken,adminUser} from './auth.mjs';
import {orderMail} from './order-mail.mjs';
const fail=(message,status=409)=>{throw Object.assign(Error(message),{status});};
const hash=s=>createHash('sha256').update(s).digest('hex');
export function cardConfig(env=process.env){const mode=env.YOCO_MODE;return {enabled:env.CARD_PAYMENTS_ENABLED==='true'&&['test','live'].includes(mode)&&String(env.YOCO_SECRET_KEY||'').startsWith('sk_'+mode+'_')&&String(env.YOCO_WEBHOOK_SECRET||'').startsWith('whsec_'),mode:mode==='live'?'live':'test'};}
export function bankConfig(settings={}){const fields=['bankName','bankAccountHolder','bankAccountNumber','bankBranchCode','bankAccountType'];const details=Object.fromEntries(fields.map(k=>[k,String(settings[k]||'').trim().slice(0,100)]));return {enabled:settings.bankTransferEnabled===true&&fields.every(k=>details[k]),...details};}
export async function paymentConfig(req,res){if(req.method!=='GET')return res.status(405).json({message:'Use GET.'});const settings=(await getFirestore().doc('settings/store').get()).data(),bank=bankConfig(settings),card=cardConfig(),snapscan=snapscanConfig(settings);if(card.enabled&&card.mode==='test'){try{await adminUser(req);}catch{card.enabled=false;}}return res.json({bank,yoco:card,snapscan});}
export function returnOrigin(req){const base=new URL(process.env.STORE_URL||'https://drixelsa.co.za');if(base.protocol!=='https:')fail('STORE_URL must use HTTPS.',503);const supplied=req.get('Origin');if(process.env.YOCO_MODE==='test'&&supplied&&process.env.ALLOW_LOCAL_ORIGINS==='true'&&/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(supplied))return supplied;return base.href.replace(/\/$/,'');}
export function checkoutUrl(value){const url=new URL(value);if(url.protocol!=='https:'||url.hostname!=='c.yoco.com'||url.username||url.password)fail('Unexpected payment provider URL.',502);return url.href;}
export async function startCheckout({orderId,req},{db=getFirestore(),request=fetch}={}){const config=cardConfig();if(!config.enabled)fail('Card payments are not connected yet. Choose bank transfer.',409);const ref=db.doc('orders/'+orderId),snap=await ref.get(),order=snap.data();if(!order||order.paymentMethod!=='yoco'||order.inventoryStatus!=='reserved'||order.status==='cancelled')fail('This order is no longer payable.');if(order.paymentMode&&order.paymentMode!==config.mode)fail('This checkout belongs to a different payment mode. Contact Drixel before paying.');if(order.paymentStatus==='paid'||order.paymentStatus==='test_paid')fail('This order has already been paid. Open your orders.');if(order.yocoCheckoutId&&order.yocoRedirectUrl)return {id:order.yocoCheckoutId,redirectUrl:checkoutUrl(order.yocoRedirectUrl)};
 const amount=Math.round(Number(order.total)*100);if(!Number.isSafeInteger(amount)||amount<=0||order.currency!=='ZAR')fail('Invalid order amount.');const origin=returnOrigin(req),path=result=>origin+'/za/payment/yoco/'+result+'?order='+encodeURIComponent(orderId);
 // Store the mode before the provider call; uncertain failures keep the reservation.
 await ref.update({paymentMode:config.mode,paymentProvider:'yoco',updatedAt:FieldValue.serverTimestamp()});
 let response;try{response=await request('https://payments.yoco.com/api/checkouts',{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+process.env.YOCO_SECRET_KEY,'Content-Type':'application/json','Idempotency-Key':hash('yoco/'+orderId)},body:JSON.stringify({amount,currency:'ZAR',successUrl:path('success'),cancelUrl:path('cancel'),failureUrl:path('failure'),metadata:{orderId,orderNumber:order.orderNumber},externalId:orderId})});}catch{fail('Payment setup could not be confirmed. Your bag and reservation are saved; retry the same checkout.',503);}
 const data=await response.json().catch(()=>({}));if(!response.ok){const candidate=data.errorCode||data.code||data.error?.code;const code=typeof candidate==='string'&&/^[A-Za-z0-9_-]{1,80}$/.test(candidate)?candidate:'unspecified';console.error('Yoco checkout rejected',JSON.stringify({status:response.status,code,mode:config.mode,returnOrigin:origin}));fail('Yoco could not start payment (provider HTTP '+response.status+'). Your reservation is saved; retry or contact Drixel with your order reference.',502);}if(!data.id||data.amount!==amount||data.currency!=='ZAR'||data.processingMode!==config.mode)fail('Yoco returned an unexpected checkout. Contact Drixel before retrying.',502);const redirectUrl=checkoutUrl(data.redirectUrl);
 await db.runTransaction(async tx=>{const current=(await tx.get(ref)).data();if(current.yocoCheckoutId&&current.yocoCheckoutId!==data.id)fail('Checkout reference changed.');if(current.inventoryStatus!=='reserved'||current.status==='cancelled')fail('This order requires payment review.');tx.update(ref,{yocoCheckoutId:data.id,yocoRedirectUrl:redirectUrl,updatedAt:FieldValue.serverTimestamp()});});return {id:data.id,redirectUrl};}
export function verifySignature(headers,raw,secret,now=Date.now()){const id=headers['webhook-id'],stamp=headers['webhook-timestamp'];if(!id||!/^\d+$/.test(stamp||'')||Math.abs(now/1000-Number(stamp))>180||!secret?.startsWith('whsec_'))return false;const expected=createHmac('sha256',Buffer.from(secret.slice(6),'base64')).update(id+'.'+stamp+'.').update(raw).digest();return String(headers['webhook-signature']||'').split(' ').some(part=>{const [v,s]=part.split(',');if(v!=='v1'||!s)return false;const actual=Buffer.from(s,'base64');return actual.length===expected.length&&timingSafeEqual(actual,expected);});}
export function paymentPatch(order,event){const p=event.payload;if(event.type!=='payment.succeeded')return null;if(!p||p.status!=='succeeded'||p.amount!==Math.round(Number(order.total)*100)||p.currency!=='ZAR'||p.mode!==order.paymentMode||p.metadata?.checkoutId!==order.yocoCheckoutId||typeof p.id!=='string'||!p.id)fail('Payment does not match the order.',400);if(['paid','test_paid'].includes(order.paymentStatus)){if(order.yocoPaymentId!==p.id)fail('Unexpected additional payment.',409);return null;}const released=order.inventoryStatus!=='reserved'||order.status==='cancelled';return {paymentStatus:p.mode==='live'?'paid':'test_paid',yocoPaymentId:p.id,status:released?'payment_review':p.mode==='test'?'payment_test':'processing',paidAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()};}
export async function processEvent(event,{db=getFirestore()}={}){if(event.type!=='payment.succeeded')return {ignored:true};const checkoutId=event.payload?.metadata?.checkoutId;if(typeof checkoutId!=='string'||checkoutId.length>150)fail('Missing checkout reference.',400);const matches=await db.collection('orders').where('yocoCheckoutId','==',checkoutId).limit(2).get();if(matches.empty)fail('Checkout has not been recorded yet.',503);if(matches.docs.length!==1)fail('Ambiguous checkout reference.',409);const ref=matches.docs[0].ref;let duplicate=false;await db.runTransaction(async tx=>{const snap=await tx.get(ref),order=snap.data();if(order.paymentMethod!=='yoco')fail('Unexpected payment method.',400);const patch=paymentPatch(order,event);if(!patch){duplicate=true;return;}const updated={...order,...patch};tx.update(ref,patch);tx.set(db.doc('mail_jobs/'+hash('order/'+ref.id+'/yoco-paid')),{...orderMail(updated,ref.id,patch.paymentStatus==='test_paid'?'Test payment received — do not dispatch':'Payment received'),status:'queued',createdAt:FieldValue.serverTimestamp()});});return {received:true,duplicate};}
export async function yocoWebhook(req,res){if(req.method!=='POST')return res.status(405).json({message:'Use POST.'});if(!process.env.YOCO_WEBHOOK_SECRET)return res.status(503).json({message:'Webhook not configured.'});if(!verifySignature(req.headers,req.rawBody,process.env.YOCO_WEBHOOK_SECRET))return res.status(403).json({message:'Invalid webhook signature.'});return res.json(await processEvent(req.body));}
export async function verifyPayment(req,res){if(req.method!=='POST')return res.status(405).json({message:'Use POST.'});const token=req.get('Authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token)fail('Sign in to check your payment.',401);let user;try{user=await verifyIdToken(token);}catch{fail('Sign in to check your payment.',401);}const id=String(req.body?.orderId||'');if(!/^[A-Za-z0-9_-]{1,100}$/.test(id))fail('Invalid order reference.',400);const snap=await getFirestore().doc('orders/'+id).get(),o=snap.data();if(!snap.exists)fail('Order not found.',404);if(o.customer?.uid!==user.uid)fail('This order does not belong to your account.',403);if(o.paymentMethod!=='yoco')fail('This is not a card order.');return res.json({paid:o.paymentStatus==='paid',testPaid:o.paymentStatus==='test_paid',review:o.status==='payment_review',orderNumber:o.orderNumber,paymentStatus:o.paymentStatus,checkoutUrl:o.paymentStatus==="pending"&&o.yocoRedirectUrl?checkoutUrl(o.yocoRedirectUrl):null});}

export async function resumePayment(req,res){if(req.method!=='POST')return res.status(405).json({message:'Use POST.'});const token=req.get('Authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token)fail('Sign in to resume payment.',401);let user;try{user=await verifyIdToken(token);}catch{fail('Sign in to resume payment.',401);}const id=String(req.body?.orderId||'');if(!/^[A-Za-z0-9_-]{1,100}$/.test(id))fail('Invalid order reference.',400);const snap=await getFirestore().doc('orders/'+id).get();if(!snap.exists)fail('Order not found.',404);if(snap.data().customer?.uid!==user.uid)fail('This order does not belong to your account.',403);if(cardConfig().mode==='test')await adminUser(req);return res.json(await startCheckout({orderId:id,req}));}
