import {createHash,createHmac,timingSafeEqual} from 'node:crypto';
import {getFirestore,FieldValue} from './firestore.mjs';
import {verifyIdToken} from './auth.mjs';
import {orderMail} from './order-mail.mjs';
const fail=(message,status=409)=>{throw Object.assign(Error(message),{status});};
const hash=value=>createHash('sha256').update(value).digest('hex');
const validId=value=>typeof value==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(value);
export function snapscanConfig(settings={},env=process.env){const snapCode=String(settings.snapscanCode||'').trim();return {enabled:settings.snapscanEnabled===true&&/^[A-Za-z0-9_-]{1,100}$/.test(snapCode)&&Boolean(env.SNAPSCAN_API_KEY&&env.SNAPSCAN_WEBHOOK_AUTH_KEY),snapCode};}
export function snapscanUrls(order,id,validationKey=process.env.SNAPSCAN_QR_VALIDATION_KEY){const amount=Math.round(Number(order.total)*100),code=order.snapscanCode,reference=order.snapscanReference;if(order.paymentMethod!=='snapscan'||order.currency!=='ZAR'||!validId(code)||!validId(id)||reference!==id||!Number.isSafeInteger(amount)||amount<=0)fail('Invalid SnapScan order.');const query=new URLSearchParams({id:reference,amount:String(amount),strict:'true'});if(validationKey)query.set('signature',createHmac('sha256',validationKey).update(`${validationKey}||${amount}||${reference}`,'utf8').digest('hex'));return {paymentUrl:`https://pos.snapscan.io/qr/${code}?${query}`,qrUrl:`https://pos.snapscan.io/qr/${code}.svg?${query}&snap_code_size=220`,amount:amount/100,reference};}
export function snapscanSignature(authorization,raw,key){if(!key||typeof authorization!=='string'||!/^SnapScan signature=[a-f0-9]{64}$/.test(authorization))return false;const expected=createHmac('sha256',key).update(raw).digest(),actual=Buffer.from(authorization.slice('SnapScan signature='.length),'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);}
export async function snapscanRequest(path,{request=fetch,key=process.env.SNAPSCAN_API_KEY}={}){if(!key)fail('SnapScan merchant API has not been configured.',503);let r;try{r=await request('https://pos.snapscan.io/merchant/api/v1/payments'+path,{redirect:'error',headers:{Authorization:'Basic '+Buffer.from(key+':').toString('base64')},signal:AbortSignal.timeout(12000)});}catch{fail('SnapScan could not confirm payment. Check your order before paying again.',503);}if(!r.ok)fail(r.status===429?'SnapScan is busy. Wait before checking again.':'SnapScan payment confirmation is temporarily unavailable.',503);let data;try{data=await r.json();}catch{fail('SnapScan returned an invalid payment response.',502);}return data;}
export function snapscanPatch(order,payment){if(payment.status!=='completed')return null;const amount=Math.round(Number(order.total)*100);if(order.paymentMethod!=='snapscan'||order.currency!=='ZAR'||payment.merchantReference!==order.snapscanReference||payment.snapCode!==order.snapscanCode||!Number.isSafeInteger(payment.id)||payment.id<=0||payment.transactionType!=='payment'||payment.totalAmount!==amount||payment.requiredAmount!==amount||Number(payment.tipAmount||0)!==0||payment.isVoucher===true||payment.isVoucherRedemption===true)fail('SnapScan payment does not match the order. Contact Drixel for review.');if(order.paymentStatus==='paid'&&order.snapscanPaymentId===payment.id)return null;const review=order.inventoryStatus!=='reserved'||order.status==='cancelled'||order.status==='payment_review'||order.paymentStatus==='refunded'||order.paymentStatus==='paid';return {paymentStatus:'paid',paymentProvider:'snapscan',snapscanPaymentId:order.snapscanPaymentId||payment.id,status:review?'payment_review':'processing',...(review?{snapscanReviewPaymentId:payment.id}:{}),paidAt:order.paidAt||FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()};}
// The input here must come from the authenticated merchant API, never a browser or raw webhook.
export async function settleSnapscanPayment(payment,{db=getFirestore()}={}){if(payment?.status!=='completed'||!validId(payment?.merchantReference))return {ignored:true};const ref=db.doc('orders/'+payment.merchantReference),eventRef=db.doc('payment_events/snapscan_'+payment.id);let outcome={};await db.runTransaction(async tx=>{const snap=await tx.get(ref),seen=await tx.get(eventRef);if(!snap.exists||snap.data().paymentMethod!=='snapscan'){outcome={ignored:true};return;}const order=snap.data(),patch=snapscanPatch(order,payment);if(seen.exists){if(seen.data().orderId!==ref.id)fail('This payment was already assigned to another order.');outcome={received:true,duplicate:true};return;}tx.set(eventRef,{orderId:ref.id,paymentId:payment.id,createdAt:FieldValue.serverTimestamp()});if(patch){const updated={...order,...patch};tx.update(ref,patch);tx.set(db.doc('mail_jobs/'+hash('order/'+ref.id+'/snapscan/'+payment.id)),{...orderMail(updated,ref.id,patch.status==='payment_review'?'Payment received — order review required':'Payment received'),status:'queued',createdAt:FieldValue.serverTimestamp()});}outcome={received:true,duplicate:!patch,review:patch?.status==='payment_review'};});return outcome;}
export async function ownedSnapscanOrder(req,{db=getFirestore(),authenticate=verifyIdToken}={}){if(req.method!=='POST')fail('Use POST.',405);const token=req.get('Authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token)fail('Sign in to view your SnapScan order.',401);let user;try{user=await authenticate(token);}catch{fail('Sign in to view your SnapScan order.',401);}const id=String(req.body?.orderId||'');if(!validId(id))fail('Invalid order reference.',400);const ref=db.doc('orders/'+id),snap=await ref.get();if(!snap.exists)fail('Order not found.',404);const order=snap.data();if(order.customer?.uid!==user.uid)fail('This order does not belong to your account.',403);if(order.paymentMethod!=='snapscan')fail('This is not a SnapScan order.');return {ref,order,user};}
export async function snapscanCheckout(req,res){const {ref,order}=await ownedSnapscanOrder(req);if(order.paymentStatus==='paid'||order.status==='payment_review')return res.json({paid:order.paymentStatus==='paid',review:order.status==='payment_review'});if(order.inventoryStatus!=='reserved'||order.status==='cancelled')fail('This order is no longer payable.');const settings=(await getFirestore().doc('settings/store').get()).data();if(!snapscanConfig(settings).enabled)fail('SnapScan is not available. Contact Drixel before paying.');return res.json(snapscanUrls(order,ref.id));}
export async function verifySnapscan(req,res){const db=getFirestore(),{ref,order,user}=await ownedSnapscanOrder(req,{db});if(order.paymentStatus==='paid'||order.status==='payment_review')return res.json({paid:order.paymentStatus==='paid',review:order.status==='payment_review'});if(order.status==='cancelled'||order.inventoryStatus!=='reserved')fail('This order requires payment review.');const limit=db.doc('api_limits/'+hash('snapscan/'+user.uid+'/'+Math.floor(Date.now()/3600000)));await db.runTransaction(async tx=>{const s=await tx.get(limit),count=s.data()?.count||0;if(count>=30)fail('You have checked payment repeatedly. Wait or contact Drixel before paying again.',429);tx.set(limit,{count:count+1,expiresAt:new Date(Date.now()+7200000)});});const query=new URLSearchParams({merchantReference:order.snapscanReference,snapCode:order.snapscanCode,status:'completed'}),payments=await snapscanRequest('?'+query);if(!Array.isArray(payments))fail('Unexpected SnapScan payment response.',502);if(payments.length>2)fail('Multiple SnapScan payments need an order review. Contact Drixel before paying again.',409);for(const p of payments){if(p.merchantReference!==order.snapscanReference||p.snapCode!==order.snapscanCode)fail('SnapScan returned an unexpected order reference.',502);await settleSnapscanPayment(p,{db});}const current=(await ref.get()).data();return res.json({paid:current.paymentStatus==='paid',review:current.status==='payment_review'});}
export async function snapscanWebhook(req,res){if(req.method!=='POST')return res.status(405).json({message:'Use POST.'});if(!process.env.SNAPSCAN_WEBHOOK_AUTH_KEY)return res.status(503).json({message:'SnapScan webhook is not configured.'});if(!snapscanSignature(req.get('Authorization'),req.rawBody,process.env.SNAPSCAN_WEBHOOK_AUTH_KEY))return res.status(403).json({message:'Invalid SnapScan webhook signature.'});let payload;try{payload=JSON.parse(req.body?.payload);}catch{fail('Invalid SnapScan payload.',400);}if(payload?.status!=='completed')return res.json({ignored:true});if(!Number.isSafeInteger(payload.id)||payload.id<=0)fail('Invalid SnapScan payment ID.',400);const payment=await snapscanRequest('/'+payload.id);if(payment.id!==payload.id)fail('SnapScan returned an unexpected payment ID.',502);return res.json(await settleSnapscanPayment(payment));}
