import React,{useState} from 'react';
import {signInWithCustomToken,signOut} from 'firebase/auth';
import {auth} from '../config/firebase-react.js';
import AdminDeviceVerification,{adminSecurityRequest} from './AdminDeviceVerification.jsx';
export default function AdminAuthenticatorVerification({enrolled,legacyEnrolled,legacyVerified:alreadyVerified=false,onVerified}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[setup,setSetup]=useState(null),[code,setCode]=useState(''),[recovery,setRecovery]=useState(false),[codes,setCodes]=useState([]),[token,setToken]=useState(''),[legacyVerified,setLegacyVerified]=useState(false);
 async function finish(customToken){if(!customToken)throw Error('A verified session was not returned. Try again.');const result=await signInWithCustomToken(auth,customToken);const status=await adminSecurityRequest('authenticator/status',{},result.user);if(status.verified!==true)throw Error('Your session could not be confirmed. Sign out and try again.');onVerified();}
 async function perform(action){if(busy)return;setBusy(true);setError('');try{await action()}catch(e){setError(e.message||'Verification failed. Try again.')}finally{setBusy(false)}}
 if(legacyEnrolled&&!legacyVerified&&!alreadyVerified)return <div><div className="admin-gate"><h1>Switch to an authenticator</h1><p>This account already has passkey protection. Verify it once, or use its recovery code, before setting up your authenticator.</p></div><AdminDeviceVerification enrolled onVerified={()=>setLegacyVerified(true)}/></div>;
 return <div className="admin-gate admin-device-gate"><strong>DRIXEL</strong><h1>{codes.length?'Save your recovery codes':enrolled?'Enter your authenticator code':'Set up your authenticator'}</h1>
 {codes.length?<><p>Save these codes privately before continuing. Each can be used once if you cannot access your authenticator. They will not be shown again.</p><div className="admin-recovery-codes">{codes.map(c=><code key={c}>{c}</code>)}</div><button disabled={busy} onClick={()=>perform(async()=>{await navigator.clipboard.writeText(codes.join('\n'));setError('Recovery codes copied. Save them privately.');})}>Copy recovery codes</button><button disabled={busy} onClick={()=>perform(()=>finish(token))}>I saved my codes — continue</button></>:<>
 {!enrolled&&!setup?<><p>Add this admin account to an authenticator app, such as Google Authenticator or Microsoft Authenticator. Each admin account needs its own setup.</p><button disabled={busy} onClick={()=>perform(async()=>{setSetup(await adminSecurityRequest('authenticator/setup'));setCode('');})}>{busy?'Preparing…':'Start authenticator setup'}</button></>:<>
 {setup&&<><p>In your authenticator app, choose to add an account manually. Select a time-based code and enter these details. Keep the setup key private.</p><dl><dt>Account</dt><dd>{setup.account}</dd><dt>Issuer</dt><dd>{setup.issuer}</dd><dt>Setup key</dt><dd><code style={{overflowWrap:'anywhere'}}>{setup.secret}</code></dd></dl><button disabled={busy} onClick={()=>perform(async()=>{await navigator.clipboard.writeText(setup.secret);setError('Setup key copied. Keep it private.');})}>Copy setup key</button><p>Enter a six-digit code to confirm setup within five minutes.</p></>}
 {enrolled&&<p>{recovery?'Enter one of your saved recovery codes.':'Open the authenticator entry for this admin account and enter its current six-digit code. A new device uses the same account entry.'}</p>}
 <form onSubmit={e=>{e.preventDefault();perform(async()=>{const result=await adminSecurityRequest(recovery?'authenticator/recover':'authenticator/verify',{code:code.trim(),...(setup?{challengeId:setup.challengeId}:{})});setCode('');setSetup(null);if(result.recoveryCodes?.length){setCodes(result.recoveryCodes);setToken(result.customToken);}else await finish(result.customToken);});}}><label>{recovery?'Recovery code':'Authenticator code'}<input autoFocus autoComplete={recovery?'off':'one-time-code'} inputMode={recovery?'text':'numeric'} pattern={recovery?'[a-f0-9]{32}':'[0-9]{6}'} maxLength={recovery?32:6} required value={code} onChange={e=>setCode(e.target.value)} /></label><button disabled={busy}>{busy?'Verifying…':setup?'Confirm authenticator setup':'Verify and continue'}</button></form>
 {setup&&<button disabled={busy} onClick={()=>{setSetup(null);setCode('');setError('');}}>Restart setup</button>}
 {enrolled&&<button disabled={busy} onClick={()=>{setRecovery(!recovery);setCode('');setError('');}}>{recovery?'Use authenticator code':'Use a recovery code'}</button>}
 </>}
 </>}
 {error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>perform(()=>signOut(auth))}>Sign out</button></div>;
}
