import UserAvatar from '../components/UserAvatar.jsx';
import React,{useEffect,useState} from 'react';
import {adminSecurityRequest} from './AdminDeviceVerification.jsx';
import {useDialog} from '../components/DialogProvider.jsx';
import {useMarket} from '../context/MarketContext.jsx';
export default function AdminTeam(){
 const dialog=useDialog(),{market}=useMarket(),[data,setData]=useState(null),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){try{setData(await adminSecurityRequest('team/list'));setError('')}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function grant(e){e.preventDefault();if(busy)return;const address=email.trim().toLowerCase();setBusy(true);setError('');setMessage('');try{const result=await adminSecurityRequest('team/grant',{email:address});setMessage(result.message);setEmail('');setData(current=>({...current,members:[{id:result.id||address,email:address,active:true,status:'Awaiting first sign-in'},...(current?.members||[]).filter(x=>x.email!==address)]}));await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(member){if(busy||!await dialog.confirm({title:'Remove administrator access?',message:'Remove '+member.email+' from store management? Their customer account and orders will remain.',confirmLabel:'Remove access',danger:true}))return;setBusy(true);setError('');setMessage('');try{const result=await adminSecurityRequest('team/remove',{id:member.id});setMessage(result.message);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="ra-panel"><p className="ra-eyebrow">STORE ACCESS</p><h2>Admin team</h2>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!data?<><p>Loading administrator access…</p>{error&&<button onClick={load}>Retry</button>}</>:!data.canManage?<p>Only a store owner can add or remove administrators. Ask your store owner for access changes.</p>:<><p>Adding an administrator gives them access to products, orders, customers and campaigns. Add a trusted team member by email. Each person uses their own account and authenticator. Your owner accounts remain protected.</p><form className="ra-filter-bar" onSubmit={grant}><label>Admin email<input type="email" autoComplete="off" maxLength={254} required value={email} onChange={e=>setEmail(e.target.value)}/></label><button type="submit" disabled={busy}>{busy?'Saving…':'Add admin'}</button></form><p>Share this sign-in link with the person you add: <a href={`/${market}/member/login?next=/${market}/admin`}>{typeof location!=='undefined'?location.origin:''}/{market}/admin</a>. No invitation email is sent automatically. They can create an account or use Google sign-in, verify their email, then set up their authenticator.</p><div className="ra-table-wrap"><table><thead><tr><th>Email</th><th>Status</th><th>Access</th></tr></thead><tbody>{data.members.map(member=><tr key={member.id}><td style={{overflowWrap:'anywhere'}}><UserAvatar user={member}/> {member.email}</td><td>{member.status}</td><td>{member.active?<button disabled={busy} onClick={()=>remove(member)}>Remove access</button>:<span>Removed</span>}</td></tr>)}</tbody></table></div>{!data.members.length&&<p>No additional administrators have been added yet.</p>}{data.limited&&<p>The first 100 administrator records are shown.</p>}</> }</section>;
}
