const artwork=n=>`/assets/campaigns/campaign-${String(n).padStart(2,'0')}.jpeg`;
const shop='https://drixelsa.co.za/za/w/new-featured';
const advert=(id,name,group,layout,headline,body,n=1,extra={})=>({id,name,group,layout,category:'advertisement',tone:group,subject:name+' / Drixel SA',preheader:body,headline,body,imageUrl:artwork(n),ctaLabel:'Explore the edit',ctaUrl:shop,kicker:group.toUpperCase(),...extra});
const update=(id,name,group,headline,body,extra={})=>({id,name,group,category:'update',tone:group,layout:'notice',subject:name+' / Drixel SA',preheader:body,headline,body,imageUrl:'',ctaLabel:'Contact our team',ctaUrl:'https://drixelsa.co.za/za/contact',kicker:'SERVICE UPDATE',statusLabel:'Update',detailLabel:'What happens next',detail:'Add the confirmed next step and the time of your next update before sending.',...extra});
export const EMAIL_TEMPLATES=[
 advert('drop','Product Drop','Launch','poster','THE NEXT CHAPTER.','A new Drixel release. Heavyweight fabric, deliberate proportions and a fresh point of view.',1),
 advert('editorial','Campaign Story','Editorial','editorial','IN OUR OWN LANE.','A closer look at the people, places and textures behind the latest collection.',2),
 advert('restock','Restock Alert','Stock','split','YOUR SIZE. BACK IN ROTATION.','Selected favourites have returned. Explore current size and colour availability.',3,{ctaLabel:'See what is back'}),
 advert('members','Members First','Community','dark','BEFORE EVERYONE ELSE.','An invitation for the Drixel list. Discover the release before the wider launch.',4),
 advert('lookbook','Season Lookbook','Editorial','gallery','A STUDY IN MOVEMENT.','New layers. Familiar streets. Discover the complete lookbook and build your next rotation.',5),
 advert('weekend','Weekend Edit','Collection','split','OFF DUTY. ON POINT.','A focused edit of tees, layers and accessories for the days that belong to you.',6),
 advert('lastcall','Last Sizes','Stock','poster','THE FINAL FEW.','Selected sizes are running low. Check the live product page for current availability.',7,{ctaLabel:'Check available sizes'}),
 advert('journal','Brand Journal','Editorial','editorial','BUILT WITH INTENT.','Notes from inside Drixel: the work, the inspiration and the details behind the pieces.',8),
 advert('thankyou','Community Thank You','Community','letter','YOU MAKE THIS MOVE.','Every order, share and message helps shape the next chapter. Thank you for moving with us.',9,{signature:'The Drixel team'}),
 advert('sale','Private Offer','Promotion','offer','AN INVITATION. JUST FOR YOU.','A subscriber offer on selected pieces. Add the confirmed promotion details before sending.',1,{offer:'YOUR OFFER',code:'ADD CODE',detailLabel:'Offer terms',detail:'Add valid dates, eligible products and exclusions.'}),
 advert('newseason','New Season','Launch','gallery','A NEW SEASON. A NEW STANDARD.','A considered collection for changing weather, long days and the streets after dark.',4),
 advert('plain','Founder Letter','Community','letter','A NOTE FROM DRIXEL.','A direct message for the people closest to the brand. Share the update that matters.',1,{imageUrl:'',signature:'The Drixel team'}),
 advert('essentials','Everyday Essentials','Collection','split','THE EVERYDAY STANDARD.','Reliable pieces. Refined details. Build a rotation around the essentials.',2),
 advert('hoodies','Heavyweight Layers','Collection','dark','WEIGHT YOU CAN FEEL.','Explore heavyweight layers, considered fits and the details that make the difference.',3),
 advert('accessories','Finishing Details','Collection','gallery','THE DETAILS DO THE WORK.','Complete the rotation with a considered selection of accessories.',6),
 advert('gift','Gift Edit','Promotion','offer','SOMETHING WITH INTENT.','A selection for the people you know best. Check delivery timing before placing your order.',8,{offer:'THE GIFT EDIT',code:'',detailLabel:'Delivery reminder',detail:'Add the confirmed order cut-off and delivery estimate.'}),
 advert('launchdate','Launch Announcement','Launch','poster','MARK THE DATE.','A new release is on the way. Add the confirmed launch date, time and access details.',9,{detailLabel:'Launch details',detail:'Date / time / South African Standard Time'}),
 advert('styled','How We Wear It','Editorial','editorial','ONE PIECE. YOUR WAY.','A closer look at styling, layering and making the collection your own.',5),
 update('outage','Website Unavailable','Website','WE ARE WORKING ON IT.','Our website is temporarily unavailable. The team is investigating and working to restore access.',{statusLabel:'Service interruption',ctaLabel:'Get support'}),
 update('maintenance','Scheduled Maintenance','Website','A SHORT PAUSE. A BETTER EXPERIENCE.','We are planning maintenance on the website. Add the confirmed maintenance window and services affected.',{statusLabel:'Scheduled maintenance',detailLabel:'Maintenance window'}),
 update('restored','Website Restored','Website','BACK ONLINE. READY WHEN YOU ARE.','Website access has been restored. Thank you for your patience while we worked on the issue.',{statusLabel:'Service restored',ctaLabel:'Visit the store',ctaUrl:shop,detail:'Check your account and contact us if you still need help.'}),
 update('soldout','Collection Sold Out','Stock','THIS EDIT HAS SOLD OUT.','The current collection is sold out. We will share confirmed restock information as soon as it is available.',{statusLabel:'Stock update',detail:'Stay on the list for availability announcements. No restock date is confirmed yet.'}),
 update('stockdelay','Restock Delayed','Stock','A LITTLE LONGER. THE SAME STANDARD.','Our expected restock has been delayed. Add the affected products and the revised timing, if confirmed.',{statusLabel:'Restock update'}),
 update('shippingdelay','Delivery Delays','Delivery','YOUR ORDER STILL MATTERS.','Some deliveries are taking longer than expected. Add the affected region, dates and the support process.',{statusLabel:'Delivery notice',detailLabel:'Affected deliveries'}),
 update('dispatchpause','Dispatch Pause','Delivery','A TEMPORARY DISPATCH PAUSE.','Dispatch is temporarily paused. Existing orders remain recorded. Add the reason and confirmed resumption date.',{statusLabel:'Dispatch update'}),
 update('paymentissue','Payment Interruption','Payments','A PAYMENT SERVICE UPDATE.','One of our payment services is temporarily unavailable. Please avoid repeating a payment if your bank has already charged you.',{statusLabel:'Payment notice',detail:'Contact support with your order reference if you were charged. Add available payment options after verifying them.'}),
 update('orderissue','Order Processing Delay','Orders','AN UPDATE ON PROCESSING.','Some orders are taking longer to process. Add the affected order period and the next step our team is taking.',{statusLabel:'Order update'}),
 update('holiday','Holiday Trading Hours','Operations','OUR UPCOMING SCHEDULE.','Our support and dispatch schedule will change during the holiday period. Add the dates and hours below.',{statusLabel:'Trading hours',detailLabel:'Support and dispatch schedule'}),
 update('weather','Weather Disruption','Delivery','SAFETY FIRST. WE WILL KEEP YOU UPDATED.','Weather conditions are affecting some deliveries. Add the confirmed areas and carrier guidance.',{statusLabel:'Delivery interruption'}),
 update('correction','Campaign Correction','Announcements','A CORRECTION FROM OUR TEAM.','An earlier message included incorrect information. State exactly what was incorrect and provide the corrected details below.',{statusLabel:'Correction',detailLabel:'Correct information'}),
 update('productnotice','Product Notice','Stock','AN IMPORTANT PRODUCT UPDATE.','We need to share an update about a product. Add the affected product or batch, the issue and clear action customers should take.',{statusLabel:'Product notice',detailLabel:'Customer action'}),
 update('support','Support Availability','Operations','OUR TEAM WILL BE BACK.','Customer support availability is temporarily changing. Add the period, alternative contact channel and response time.',{statusLabel:'Support update'}),
 update('policy','Policy Update','Announcements','A CLEARER WAY FORWARD.','We are updating a store policy. Explain what changes, when it takes effect and where customers can read the full policy.',{statusLabel:'Policy update'}),
 update('community','Community Announcement','Announcements','FROM OUR TEAM TO YOU.','Share a brand milestone, community event or important company update with the Drixel list.',{statusLabel:'Community update'})
];
export const emailAssetUrl=(value,baseUrl='https://drixelsa.co.za')=>{if(!String(value||'').trim())return '';try{const url=new URL(String(value).trim(),baseUrl);return ['https:','http:'].includes(url.protocol)?url.href:''}catch{return ''}};
// Pin bundled artwork to a publicly verified repository revision. This keeps
// campaign emails independent of whether the custom site has deployed assets.
const campaignAssetRoot='https://raw.githubusercontent.com/andziboyrsa702-spec/drixelsa.github.io/768eb98e781d23c7223bad847b988c4093548ea8/public';
export function emailImageUrl(value,previewOrigin){
 if(previewOrigin)return emailAssetUrl(value,previewOrigin);
 const url=emailAssetUrl(value);
 if(!url)return '';
 const parsed=new URL(url);
 if(['drixelsa.co.za','www.drixelsa.co.za'].includes(parsed.hostname)&&/^\/assets\/campaigns\/campaign-0[1-9]\.jpeg$/.test(parsed.pathname)){const managed=import.meta.env?.VITE_EMAIL_ASSET_BASE_URL;if(managed&&/^https:\/\//.test(managed)&&!new URL(managed).hostname.match(/^(localhost|127\.)/))return managed.replace(/\/$/,'')+parsed.pathname;return campaignAssetRoot+parsed.pathname;}
 return url;
}
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const text=s=>esc(s).replace(/\n/g,'<br>');
export function emailHtml(d,{assetBaseUrl}={}){
 const dark=d.layout==='dark',notice=d.layout==='notice',letter=['letter','minimal'].includes(d.layout),fg=dark?'#ffffff':'#111111',muted=dark?'#b8b8b8':'#626262',bg=dark?'#111111':'#ffffff';
 const image=emailImageUrl(d.imageUrl,assetBaseUrl),image2=emailImageUrl(d.secondaryImageUrl,assetBaseUrl);
 const art=(url,width=640)=>url?`<img src="${esc(url)}" width="${width}" alt="${esc(d.imageAlt||'Drixel campaign')}" style="display:block;width:100%;height:auto;border:0">`:'';
 const kicker=`<p style="margin:0 0 18px;font:700 11px Arial,Helvetica,sans-serif;letter-spacing:2px;color:${muted}">${esc(d.kicker||'DRIXEL / CAMPAIGN')}</p>`;
 const heading=`<h1 style="margin:0 0 24px;font-family:${d.layout==='editorial'?'Georgia,serif':'Arial,Helvetica,sans-serif'};font-size:${letter?38:notice?42:52}px;line-height:1.06;letter-spacing:-1.5px;font-weight:${d.layout==='editorial'?400:700};overflow-wrap:break-word">${esc(d.headline)}</h1>`;
 const body=`<p style="margin:0;font:400 16px/1.75 Arial,Helvetica,sans-serif;color:${muted}">${text(d.body)}</p>`;
 const details=d.detail?`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:28px;border-top:1px solid ${dark?'#444':'#dddddd'}"><tr><td style="padding-top:20px;color:${fg}"><p style="margin:0 0 8px;font:700 11px Arial;letter-spacing:1px;text-transform:uppercase">${esc(d.detailLabel||'Details')}</p><p style="margin:0;font:14px/1.7 Arial;color:${muted}">${text(d.detail)}</p></td></tr></table>`:'';
 const copy=kicker+heading+body+details;
 let main='';
 if(d.layout==='split'&&image)main=`<tr><td><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td class="stack" width="46%" valign="top">${art(image,294)}</td><td class="stack inset" valign="middle" style="padding:32px">${copy}</td></tr></table></td></tr>`;
 else if(d.layout==='poster')main=`<tr><td class="inset" style="padding:44px 40px 32px;color:${fg}">${copy}</td></tr><tr><td>${art(image)}</td></tr>`;
 else if(d.layout==='offer')main=`<tr><td>${art(image)}</td></tr><tr><td class="inset" style="padding:40px;color:${fg}">${kicker}<p style="margin:0 0 20px;font:700 58px/1 Arial;letter-spacing:-2px">${esc(d.offer||'PRIVATE ACCESS')}</p>${heading}${body}${d.code?`<p style="display:inline-block;margin:24px 0 0;padding:14px 24px;border:1px dashed #111;font:700 20px Arial;letter-spacing:3px">${esc(d.code)}</p>`:''}${details}</td></tr>`;
 else if(notice)main=`${image?`<tr><td>${art(image)}</td></tr>`:''}<tr><td class="inset" style="padding:40px;color:${fg}"><p style="margin:0 0 32px;padding:12px 16px;background:#f1f1ef;border-left:3px solid #111;font:700 11px Arial;letter-spacing:1px;text-transform:uppercase">${esc(d.statusLabel||'Service update')}</p>${copy}</td></tr>`;
 else if(letter)main=`${image?`<tr><td>${art(image)}</td></tr>`:''}<tr><td class="inset" style="padding:44px 40px;color:${fg}">${copy}<p style="margin:32px 0 0;font:italic 20px Georgia,serif">${esc(d.signature||'The Drixel team')}</p></td></tr>`;
 else main=`<tr><td>${art(image)}</td></tr><tr><td class="inset" style="padding:40px;color:${fg}">${copy}</td></tr>${d.layout==='gallery'&&image2?`<tr><td>${art(image2)}</td></tr>`:''}`;
 const cta=d.ctaLabel&&emailAssetUrl(d.ctaUrl)?`<tr><td class="inset" style="padding:24px 40px 40px"><table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="${dark?'#ffffff':'#111111'}" style="padding:16px 24px"><a href="${esc(emailAssetUrl(d.ctaUrl))}" style="font:700 13px Arial,Helvetica,sans-serif;color:${dark?'#111111':'#ffffff'};text-decoration:none">${esc(d.ctaLabel)} &nbsp;↗</a></td></tr></table></td></tr>`:'';
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(d.subject||'Drixel')}</title><style>@media(max-width:480px){.stack{display:block!important;width:100%!important;box-sizing:border-box!important}.inset{padding-left:24px!important;padding-right:24px!important}h1{font-size:34px!important;letter-spacing:-1px!important}.email-wrap{padding:12px 0!important}}</style></head><body style="margin:0;background:#efefed;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">${esc(d.preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td class="email-wrap" align="center" style="padding:32px 12px"><table role="presentation" width="640" cellspacing="0" cellpadding="0" style="width:100%;max-width:640px;table-layout:fixed;background:${bg};color:${fg}"><tr><td class="inset" style="padding:28px 40px;border-bottom:1px solid ${dark?'#333':'#e5e5e5'}"><table role="presentation" width="100%"><tr><td style="font:700 26px Arial;letter-spacing:-1px">DRIXEL</td><td align="right" style="font:10px Arial;letter-spacing:2px;color:${muted}">SOUTH AFRICA</td></tr></table></td></tr>${main}${d.videoUrl&&emailAssetUrl(d.videoUrl)?`<tr><td class="inset" style="padding:24px 40px"><a href="${esc(emailAssetUrl(d.videoUrl))}" style="font:700 14px Arial;color:${fg}">Watch the campaign video →</a></td></tr>`:""}${cta}<tr><td class="inset" style="padding:26px 40px;border-top:1px solid ${dark?'#333':'#e5e5e5'};font:11px/1.8 Arial;color:${muted}">DRIXEL SA · South African streetwear<br>You joined the Drixel list. A subscription preference link is included when this campaign is sent.</td></tr></table></td></tr></table></body></html>`;
}
