export const EMAIL_TEMPLATES=[
{id:"drop",name:"Product Drop",group:"Launch",tone:"High impact",subject:"The new Drixel drop is live.",preheader:"New silhouettes. Limited quantities.",headline:"THE DROP IS LIVE.",body:"The latest Drixel edit has landed. Built around heavyweight fabric, sharp proportions and pieces designed for the city.",ctaLabel:"Shop the drop",imageUrl:"/assets/campaigns/campaign-01.jpeg",layout:"split"},
{id:"editorial",name:"Editorial Story",group:"Brand",tone:"Magazine",subject:"Inside the new Drixel edit.",preheader:"A closer look at the campaign.",headline:"MADE FOR THE STREETS THAT MADE US.",body:"A study in movement, texture and everyday South African street culture. Explore the campaign and the pieces behind it.",ctaLabel:"View the story",imageUrl:"/assets/campaigns/campaign-02.jpeg",layout:"editorial"},
{id:"restock",name:"Restock Alert",group:"Commerce",tone:"Urgent",subject:"Back in stock.",preheader:"The pieces you asked for have returned.",headline:"BACK. NOT FOR LONG.",body:"Selected Drixel favourites are available again. Sizes are limited and stock moves quickly.",ctaLabel:"Shop restock",imageUrl:"/assets/campaigns/campaign-03.jpeg",layout:"poster"},
{id:"members",name:"Members First",group:"Community",tone:"Exclusive",subject:"You get first access.",preheader:"Subscriber access before everyone else.",headline:"FIRST ACCESS IS YOURS.",body:"You are on the Drixel list, so you are seeing this first. Explore the new release before the wider campaign goes live.",ctaLabel:"Enter early access",imageUrl:"/assets/campaigns/campaign-04.jpeg",layout:"dark"},
{id:"lookbook",name:"Lookbook",group:"Brand",tone:"Visual",subject:"Drixel Lookbook / 2026",preheader:"The latest campaign in full.",headline:"LOOKBOOK / 2026",body:"New layers, clean silhouettes and a sharper point of view. See the latest Drixel campaign.",ctaLabel:"Explore lookbook",imageUrl:"/assets/campaigns/campaign-05.jpeg",layout:"gallery"},
{id:"weekend",name:"Weekend Edit",group:"Commerce",tone:"Curated",subject:"The weekend edit.",preheader:"Four pieces. One rotation.",headline:"YOUR WEEKEND ROTATION.",body:"A focused selection for the next few days: easy layers, essential tees and pieces that work after dark.",ctaLabel:"Shop the edit",imageUrl:"/assets/campaigns/campaign-06.jpeg",layout:"split"},
{id:"lastcall",name:"Last Call",group:"Commerce",tone:"Urgent",subject:"Last call on this edit.",preheader:"Selected sizes are nearly gone.",headline:"LAST CALL.",body:"This is the final reminder for the current edit. Once these sizes move, they may not return.",ctaLabel:"Shop before it goes",imageUrl:"/assets/campaigns/campaign-07.jpeg",layout:"poster"},
{id:"journal",name:"Drixel Journal",group:"Brand",tone:"Story",subject:"Drixel Journal: what we are building.",preheader:"Notes from inside the brand.",headline:"BUILT WITH INTENT.",body:"Drixel is not only about a product release. This is a record of what we are building, what inspires the work and where the brand is going.",ctaLabel:"Read the journal",imageUrl:"/assets/campaigns/campaign-08.jpeg",layout:"editorial"},
{id:"thankyou",name:"Community Note",group:"Community",tone:"Personal",subject:"A note from Drixel.",preheader:"Thank you for being here.",headline:"THIS BRAND MOVES WITH YOU.",body:"Every order, share and message pushes Drixel forward. Thank you for being part of the people shaping what comes next.",ctaLabel:"Visit Drixel",imageUrl:"/assets/campaigns/campaign-09.jpeg",layout:"minimal"},
{id:"sale",name:"Private Offer",group:"Promotion",tone:"Direct",subject:"A private Drixel offer.",preheader:"Subscriber-only access.",headline:"PRIVATE ACCESS.",body:"A limited offer for the Drixel list. Use the campaign link while the promotion is active.",ctaLabel:"Unlock offer",imageUrl:"/assets/campaigns/campaign-01.jpeg",layout:"dark"},
{id:"newseason",name:"New Season",group:"Launch",tone:"Premium",subject:"A new season begins.",preheader:"Drixel enters its next chapter.",headline:"NEW SEASON. NEW ENERGY.",body:"A refined collection built for changing weather, long days and the streets after dark.",ctaLabel:"Discover the season",imageUrl:"/assets/campaigns/campaign-04.jpeg",layout:"gallery"},
{id:"plain",name:"Founder Note",group:"Community",tone:"Minimal",subject:"A message from Drixel.",preheader:"Direct from the brand.",headline:"A NOTE FROM DRIXEL.",body:"A simple message for the people closest to the brand. No noise. Just the update that matters.",ctaLabel:"Continue to Drixel",imageUrl:"",layout:"minimal"}
];
const esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
export function emailHtml(d){const dark=d.layout==="dark",bg=dark?"#050505":"#fff",fg=dark?"#fff":"#0a0a0a",muted=dark?"#aaa":"#606060",img=d.imageUrl?'<img src="'+esc(d.imageUrl)+'" width="680" style="display:block;width:100%;height:auto;max-height:720px;object-fit:cover" alt="">':"",imageFirst=d.layout!=="poster",titleFont=d.layout==="editorial"?"Georgia,serif":"Arial,Helvetica,sans-serif";return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#ededed;font-family:Arial,sans-serif"><div style="display:none;max-height:0;overflow:hidden">'+esc(d.preheader)+'</div><table width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:30px 12px"><table width="680" style="width:100%;max-width:680px;background:'+bg+'" cellspacing="0" cellpadding="0"><tr><td style="color:'+fg+';padding:26px 42px;border-bottom:1px solid '+(dark?"#242424":"#e5e5e5")+'"><b style="font-size:26px">DRIXEL</b><span style="float:right;font-size:10px;letter-spacing:2px;color:'+muted+'">SOUTH AFRICA</span></td></tr>'+(imageFirst&&img?'<tr><td>'+img+'</td></tr>':'')+'<tr><td style="color:'+fg+';padding:50px 42px"><div style="font-size:11px;letter-spacing:3px;font-weight:700">DRIXEL / '+esc(d.kicker||"CAMPAIGN")+'</div><h1 style="font-family:'+titleFont+';font-size:'+(d.layout==="minimal"?"42":"54")+'px;line-height:.94;letter-spacing:-2.5px;margin:17px 0 22px">'+esc(d.headline)+'</h1><p style="font-size:16px;line-height:1.7;color:'+muted+';margin:0">'+esc(d.body).replace(/\n/g,"<br>")+'</p></td></tr>'+(!imageFirst&&img?'<tr><td>'+img+'</td></tr>':'')+(d.ctaLabel&&d.ctaUrl?'<tr><td style="padding:0 42px 50px"><a href="'+esc(d.ctaUrl)+'" style="display:inline-block;background:'+(dark?"#fff":"#0a0a0a")+';color:'+(dark?"#050505":"#fff")+';text-decoration:none;padding:15px 24px;font-size:13px;font-weight:800">'+esc(d.ctaLabel)+'</a></td></tr>':'')+'<tr><td style="color:'+muted+';padding:26px 42px;border-top:1px solid '+(dark?"#242424":"#e5e5e5")+';font-size:11px;line-height:1.6">DRIXEL SA · South African streetwear<br>You are receiving this because you joined the Drixel list.</td></tr></table></td></tr></table></body></html>'}
