import {auth} from '../config/firebase-react.js';
import {apiUrl} from '../utils/api.js';
import React,{useState} from 'react';
import {collection,getDocsFromServer} from 'firebase/firestore';
import {db} from '../config/firebase-react.js';
import {useAdminData} from './useAdminData.js';
import AdminDataState from './AdminDataState.jsx';
const time=value=>value?.toMillis?value.toMillis():Number(value)||0;
const date=value=>time(value)?new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Johannesburg'}).format(time(value))+' SAST':'Not recorded';
export default function OperationsHealthAdmin(){
 const state=useAdminData(['operations_health','email_campaigns']),[fresh,setFresh]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function refresh(){setBusy(true);setNotice('');try{const names=['operations_health','email_campaigns'];const snapshots=await Promise.all(names.map(name=>getDocsFromServer(collection(db,name))));setFresh(Object.fromEntries(names.map((name,i)=>[name,snapshots[i].docs.map(d=>({...d.data(),id:d.id}))])));setNotice('Latest records loaded from the server. Refresh checks status; it does not restart a failed queue.');}catch(e){setNotice('Refresh failed: '+e.message);}finally{setBusy(false);}}
 async function index(repair){setBusy(true);setNotice('');try{const token=await auth.currentUser.getIdToken();const response=await fetch(apiUrl('/api/admin/campaign-index'),{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({repair})});const data=await response.json();if(!response.ok||!data.success)throw Error(data.message||'Index check failed');setNotice(data.message);}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 if(state.loading||state.error)return <AdminDataState {...state}/>;
 const data=fresh||state.data,campaigns=data.email_campaigns||[];
 return <section className="ra-panel"><div className="ra-panel-head"><div><p className="ra-eyebrow">OPERATIONS / SERVICE HEALTH</p><h2>Email service health</h2></div><button disabled={busy} onClick={refresh}>{busy?'Checking server…':'Refresh health'}</button></div>{notice&&<p role="status">{notice}</p>}<div className="ra-health-grid">{[['orderMail','Order receipts and updates'],['campaignWorker','Subscriber campaigns']].map(([id,label])=>{const worker=data.operations_health.find(x=>x.id===id),stale=!time(worker?.lastFinishedAt)||Date.now()-time(worker.lastFinishedAt)>15*60000;return <article key={id}><h3>{label}</h3><p>{!worker?'No run recorded':worker.status==='failed'?'Queue needs attention':stale?'No recent completed run':'Queue running normally'}</p><dl><dt>Last checked</dt><dd>{date(worker?.lastFinishedAt)}</dd><dt>Last failure</dt><dd>{date(worker?.lastFailedAt)}</dd></dl>{worker?.status==='failed'&&<p className="dx-error">{worker.lastError||'Check the Worker logs.'}</p>}{worker?.errorCode==='FAILED_PRECONDITION'&&<p>Deploy the Firestore indexes, then wait for the campaign_jobs Status / Due At index to show Enabled. The next scheduled run will retry pending jobs.</p>}</article>})}</div><div className="ra-filter-bar"><button disabled={busy} onClick={()=>index(false)}>Check queue index</button><button disabled={busy} onClick={()=>index(true)}>Create queue index</button></div><p>{campaigns.filter(c=>['queued','scheduled','sending'].includes(c.status)).length} campaigns waiting or sending · {campaigns.filter(c=>c.status==='delivery_unknown').length} need provider reconciliation</p><p>Submitted means the email provider accepted the message. Delivered means the recipient mail server accepted it; inbox placement is separate.</p></section>;
}
