import React,{useState} from 'react';
import MediaUpload from './MediaUpload.jsx';
import {productOptions} from '../utils/productOptions.js';
export default function ProductColourMedia({product:p,onChange,busy}){
 const [name,setName]=useState(''),[sizes,setSizes]=useState('S, M, L, XL'),[stock,setStock]=useState(0);
 const rows=Array.isArray(p.colorImages)?p.colorImages:[],existing=productOptions(p).colors;
 const saveRows=next=>onChange({colorImages:next,...(!p.variants?.length?{colors:[...new Set([...existing,...next.map(x=>x.color)])]}:{})});
 const add=names=>{const next=[...rows];for(const color of names.map(x=>x.trim()).filter(Boolean))if(!next.some(x=>x.color.toLowerCase()===color.toLowerCase()))next.push({color,frontImage:color===p.mainColor?p.frontImage||p.image||'':'',backImage:color===p.mainColor?p.backImage||'':''});saveRows(next);setName('')};
 const patch=(color,key,value)=>onChange(current=>({colorImages:(current.colorImages||[]).map(x=>x.color===color?{...x,[key]:value}:x)}));
 const generate=()=>{const ss=[...new Set(sizes.split(',').map(x=>x.trim()).filter(Boolean))];if(!ss.length||!Number.isSafeInteger(Number(stock))||Number(stock)<0)return;const vs=[...(p.variants||[])],used=new Set(vs.map(v=>v.sku));const code=x=>String(x).toUpperCase().replace(/[^A-Z0-9]+/g,'-').replace(/^-|-$/g,'');for(const row of rows)for(const size of ss)if(!vs.some(v=>v.color===row.color&&v.size===size)){const base=[code(p.urlCode||p.name||'PRODUCT'),code(row.color),code(size)].join('-');let sku=base,n=2;while(used.has(sku))sku=base+'-'+n++;used.add(sku);vs.push({color:row.color,size,sku,stock:Number(stock),price:''})}onChange({variants:vs})};
 return <section className="ra-colour-studio"><h3>Colour photography & sizes</h3><p>Upload the actual front and back photos for each colour. Customers see the selected colour; the main colour is used in the shop. Photos do not create stock.</p><div className="ra-form-two"><label>New colour<input value={name} onChange={e=>setName(e.target.value)} placeholder="For example, Black"/></label><button type="button" disabled={busy||!name.trim()} onClick={()=>add([name])}>Add colour</button></div><div className="ra-admin-actions"><button type="button" disabled={busy} onClick={()=>add(['Black','Blue','White','Red'])}>Add Black, Blue, White & Red</button>{existing.length>0&&<button type="button" disabled={busy} onClick={()=>add(existing)}>Use existing product colours</button>}</div><label>Main display colour<select value={p.mainColor||''} onChange={e=>onChange({mainColor:e.target.value})}><option value="">Existing main photos</option>{rows.map(r=><option key={r.color}>{r.color}</option>)}</select></label><div className="ra-colour-photo-grid">{rows.map(r=><section className="ra-colour-photo-card" key={r.color}><h4>{r.color}</h4><div className="ra-product-photography">{['frontImage','backImage'].map((key,i)=><div key={key}><h5>{i?'Back':'Front'} view</h5>{r[key]&&<img src={r[key]} alt={r.color+(i?' back':' front')+' preview'}/>}<MediaUpload purpose="product" label={'Upload '+r.color+(i?' back':' front')+' image'} accept="image/jpeg,image/png,image/webp" disabled={busy} onUploaded={a=>patch(r.color,key,a.url)}/><label>{r.color} {i?'back':'front'} image URL<input value={r[key]||''} onChange={e=>patch(r.color,key,e.target.value)}/></label></div>)}</div>{!r.frontImage||!r.backImage?<p>Upload both views before using this colour.</p>:null}<button type="button" disabled={busy} onClick={()=>{saveRows(rows.filter(x=>x.color!==r.color));if(p.mainColor===r.color)onChange({mainColor:''})}}>Remove {r.color} photos</button></section>)}</div>{rows.length>0&&<div className="ra-colour-size-builder"><h4>Add size combinations quickly</h4><p>Adds missing combinations for these colours. Existing SKUs and stock stay unchanged. Enter actual stock per new combination; zero means sold out.</p><div className="ra-form-two"><label>Sizes for new colour combinations<input value={sizes} onChange={e=>setSizes(e.target.value)}/></label><label>Stock per new combination<input type="number" min="0" step="1" value={stock} onChange={e=>setStock(e.target.value)}/></label></div><button type="button" disabled={busy||!sizes.trim()||!Number.isSafeInteger(Number(stock))||Number(stock)<0} onClick={generate}>Add missing colour & size variants</button></div>}</section>
}
