import React,{useMemo,useState} from 'react';
import {useAdminData} from './useAdminData.js';
import AdminDataState from './AdminDataState.jsx';
import {isActiveSubscriber} from '../utils/marketingApi.js';
const joined=value=>{const stamp=value?.seconds?value.seconds*1000:Date.parse(value||'');return Number.isFinite(stamp)?new Date(stamp).toLocaleDateString('en-ZA'):'—';};
export default function SubscribersAdmin(){
 const connection=useAdminData(['subscribers','users','orders']),subs=connection.data.subscribers||[],users=connection.data.users||[],orders=connection.data.orders||[];
 const [q,setQ]=useState(''),[status,setStatus]=useState('all');
 const active=subs.filter(isActiveSubscriber),pending=subs.filter(s=>s.status==='pending'),left=subs.filter(s=>s.status==='unsubscribed');
 const rows=useMemo(()=>{
  const customers=new Map(users.filter(u=>u.email).map(u=>[u.email.toLowerCase(),u])),paid=orders.filter(o=>o.paymentStatus==='paid');
  return subs.map(s=>{const email=String(s.email||'').toLowerCase(),u=customers.get(email),mine=paid.filter(o=>String(o.customer?.email||'').toLowerCase()===email);return {...s,status:s.suppressed?'suppressed':s.status||'active',name:u?.name||[u?.firstName,u?.lastName].filter(Boolean).join(' ')||'Drixel subscriber',orders:mine.length,spent:mine.reduce((n,o)=>n+Number(o.total||0),0)};}).filter(s=>(status==='all'||s.status===status)&&(!q||`${s.name} ${s.email} ${s.source||'website'}`.toLowerCase().includes(q.toLowerCase())));
 },[subs,users,orders,q,status]);
 if(connection.error||connection.loading)return <AdminDataState {...connection}/>;
 return <div className="mk-workspace mk-audience"><header className="mk-workspace-head"><div><p className="mk-overline">DRIXEL / OWNED AUDIENCE <span className="mk-release">MKT.02</span></p><h2>The people behind the list.</h2><p>Website signups appear here as they are saved. Only active subscribers receive campaigns and announcements.</p></div><div className="mk-summary"><div><strong>{active.length}</strong><span>Active subscribers</span></div><div><strong>{pending.length}</strong><span>Pending confirmation</span></div><div><strong>{left.length}</strong><span>Unsubscribed</span></div></div></header><section className="ra-panel mk-results"><div className="mk-library-tools"><input type="search" aria-label="Search subscribers" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search email, name or source…"/><div className="mk-filters" aria-label="Subscriber status">{[['all','Everyone'],['active','Active'],['pending','Pending'],['unsubscribed','Unsubscribed'],['suppressed','Suppressed']].map(([key,label])=><button key={key} aria-pressed={status===key} onClick={()=>setStatus(key)}>{label}</button>)}</div></div><div className="mk-audience-summary"><span>{rows.length} people</span><span>Updates automatically · signup sources are recorded</span></div><div className="ra-table-wrap"><table><thead><tr><th>Subscriber</th><th>Status</th><th>Signup source</th><th>Joined</th><th>Paid orders</th><th>Paid spend (ZAR)</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><br/><span className="mk-subscriber-email">{r.email}</span></td><td><span className={'mk-state mk-state-'+r.status}>{r.status}</span></td><td>{r.source||'website'}</td><td>{joined(r.subscribedAt||r.requestedAt)}</td><td>{r.orders}</td><td>{new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(r.spent)}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="ra-empty">{q||status!=='all'?'No subscribers match these filters.':'Your audience starts here. When someone joins through the website, their saved subscription will appear in this list.'}</div>}<p className="mk-field-note">Pending people have not completed confirmation. Bounced and complained addresses are suppressed. Unsubscribed people stay in the record and are excluded from every send.</p></section></div>;
}
