import{createUserWithEmailAndPassword,signInWithEmailAndPassword,GoogleAuthProvider,signInWithPopup,sendPasswordResetEmail,updateProfile,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/9.23.0/firebase-auth.js";import{doc,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore.js";import{auth,db}from"../config/firebase.js";
const $=id=>document.getElementById(id),message=$("authMessage"),params=new URLSearchParams(location.search);
const safeNext=()=>{const n=params.get("next");return n==="checkout"?"/checkout.html":n==="account"?"/account.html":"/account.html"};
function note(text){message.textContent=text;message.hidden=false}function busy(form,state){form.querySelectorAll("button,input").forEach(x=>x.disabled=state)}
async function syncUser(user,data={}){await setDoc(doc(db,"users",user.uid),{uid:user.uid,email:user.email,name:data.name||user.displayName||user.email?.split("@")[0]||"",phone:data.phone||"",role:"customer",lastLogin:serverTimestamp(),...(data.created?{createdAt:serverTimestamp()}:{} )},{merge:true});if(data.subscribe)fetch("/api/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:user.email,source:"account-registration"})}).catch(()=>{})}
document.querySelectorAll("[data-tab]").forEach(btn=>btn.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===btn));const login=btn.dataset.tab==="login";$("loginForm").hidden=!login;$("registerForm").hidden=login;message.hidden=true});
$("loginForm").onsubmit=async e=>{e.preventDefault();busy(e.currentTarget,true);message.hidden=true;try{const cred=await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value);await syncUser(cred.user);location.replace(safeNext())}catch(err){note(err.code==="auth/invalid-credential"?"Email or password is incorrect.":"Sign in failed. Please try again.")}finally{busy(e.currentTarget,false)}};
$("registerForm").onsubmit=async e=>{e.preventDefault();message.hidden=true;const password=$("registerPassword").value;if(password!==$("registerConfirm").value){note("Passwords do not match.");return}if(password.length<8){note("Use a password with at least 8 characters.");return}busy(e.currentTarget,true);try{const name=$("registerName").value.trim(),cred=await createUserWithEmailAndPassword(auth,$("registerEmail").value.trim(),password);await updateProfile(cred.user,{displayName:name});await syncUser(cred.user,{name,phone:$("registerPhone").value.trim(),created:true,subscribe:$("registerSubscribe").checked});location.replace(safeNext())}catch(err){note(err.code==="auth/email-already-in-use"?"An account already exists for that email.":"Account creation failed. Please check your details.")}finally{busy(e.currentTarget,false)}};
$("googleAuth").onclick=async()=>{message.hidden=true;try{const cred=await signInWithPopup(auth,new GoogleAuthProvider());await syncUser(cred.user);location.replace(safeNext())}catch(err){if(err.code!=="auth/popup-closed-by-user")note("Google sign-in could not be completed.")}};
$("forgotPassword").onclick=async()=>{const email=$("loginEmail").value.trim();if(!email){note("Enter your email above first.");return}try{await sendPasswordResetEmail(auth,email);note("Password reset email sent. Check your inbox.")}catch{note("We couldn't send the reset email. Check the address and try again.")}};
onAuthStateChanged(auth,user=>{if(user&&params.get("next"))location.replace(safeNext())});