import {initializeApp} from "https://www.gstatic.com/firebasejs/9.23.0/firebase-app.js";
import {getAuth,onAuthStateChanged,signOut as firebaseSignOut} from "https://www.gstatic.com/firebasejs/9.23.0/firebase-auth.js";
import {getFirestore,collection,getDocs,doc,setDoc,addDoc,updateDoc,deleteDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyA4_Ejkc3Of0T8fCj1QqkNN78-2xJ882F0",authDomain:"drixel-sa.firebaseapp.com",projectId:"drixel-sa",storageBucket:"drixel-sa.firebasestorage.app",messagingSenderId:"620600264300",appId:"1:620600264300:web:525de2d55cc1ae6269fa49"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const ADMINS=new Set(["admin@drixelsa.co.za","drixelsa@gmail.com"]);
const state={view:"dashboard",orders:[],products:[],users:[],banners:[],coupons:[]};
const $=s=>document.querySelector(s); const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const money=n=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(Number(n)||0);
const date=v=>v?new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)}
async function read(name){const s=await getDocs(collection(db,name));return s.docs.map(d=>({id:d.id,...d.data()}))}
async function loadAll(){const [orders,products,users,banners,coupons]=await Promise.all([read("orders"),read("products"),read("users"),read("banners"),read("coupons")]);Object.assign(state,{orders,products,users,banners,coupons});state.orders.sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0))}
onAuthStateChanged(auth,async user=>{const email=(user?.email||"").toLowerCase();if(!user||!ADMINS.has(email)){ $("#gateMessage").textContent=user?"This account is not authorised for Drixel Admin.":"Sign in with an authorised administrator account.";return}$("#gate").hidden=true;$("#app").hidden=false;await refresh()});
async function refresh(){try{$("#content").innerHTML='<div class="loading">Loading store data…</div>';await loadAll();render()}catch(e){console.error(e);$("#content").innerHTML='<div class="empty">Could not load store data. Check Firestore permissions and try again.</div>'}}
$("#refresh").onclick=refresh;$("#signOut").onclick=()=>firebaseSignOut(auth).then(()=>location.href="/auth.html");
$("#nav").addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(!b)return;state.view=b.dataset.view;document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===b));render()});
$("#primaryAction").onclick=()=>openProduct();
function setTitle(title,group="Drixel Admin"){ $("#pageTitle").textContent=title;$("#eyebrow").textContent=group;$("#primaryAction").style.display=state.view==="products"?"":"none"}
function render(){({dashboard:dashboard,orders:orders,products:products,inventory:inventory,customers:customers,content:content,discounts:discounts,payments:payments,shipping:shipping,settings:settings}[state.view]||dashboard)()}
function dashboard(){setTitle("Dashboard","Overview");const paid=state.orders.filter(o=>o.paymentStatus==="paid");const revenue=paid.reduce((s,o)=>s+Number(o.total||0),0);const pending=state.orders.filter(o=>["pending","pending_verification"].includes(o.paymentStatus)).length;const low=state.products.filter(p=>Number(p.stock??999)<=5).length;$("#content").innerHTML=`<div class="metrics"><div class="metric"><span>Revenue</span><strong>${money(revenue)}</strong></div><div class="metric"><span>Orders</span><strong>${state.orders.length}</strong></div><div class="metric"><span>Customers</span><strong>${state.users.length}</strong></div><div class="metric"><span>Low stock</span><strong>${low}</strong></div></div><div class="grid-2"><section class="panel"><div class="panel-head"><h2>Recent orders</h2><button class="icon-button" data-go="orders">View all</button></div>${orderTable(state.orders.slice(0,7))}</section><section class="panel"><div class="panel-head"><h2>Needs attention</h2></div><p><strong>${pending}</strong> payments awaiting verification</p><p><strong>${low}</strong> products at low stock</p><p><strong>${state.products.filter(p=>p.status==="draft").length}</strong> product drafts</p></section></div>`;document.querySelector("[data-go='orders']")?.addEventListener("click",()=>{state.view="orders";render()})}
function orderTable(rows){if(!rows.length)return'<div class="empty">No orders yet.</div>';return `<div class="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td><strong>${esc(o.orderNumber||o.order_id||o.id)}</strong></td><td>${esc(o.customer?.name||o.customer?.email||"Guest")}</td><td>${money(o.total)}</td><td><span class="badge ${esc(o.paymentStatus)}">${esc(o.paymentStatus||"pending")}</span></td><td>${esc(o.status||"processing")}</td><td>${date(o.createdAt)}</td><td><div class="row-actions"><button data-order="${esc(o.id)}">Manage</button></div></td></tr>`).join("")}</tbody></table></div>`}
function orders(){setTitle("Orders","Commerce");$("#content").innerHTML=`<section class="panel"><div class="toolbar"><input id="orderSearch" placeholder="Search order, customer or email"><select id="orderStatus"><option value="">All statuses</option><option>processing</option><option>shipped</option><option>delivered</option><option>cancelled</option></select></div><div id="orderRows">${orderTable(state.orders)}</div></section>`;const apply=()=>{const q=$("#orderSearch").value.toLowerCase(),s=$("#orderStatus").value;const rows=state.orders.filter(o=>(!s||(o.status||"processing")===s)&&JSON.stringify(o).toLowerCase().includes(q));$("#orderRows").innerHTML=orderTable(rows);bindOrderButtons()};$("#orderSearch").oninput=apply;$("#orderStatus").onchange=apply;bindOrderButtons()}
function bindOrderButtons(){document.querySelectorAll("[data-order]").forEach(b=>b.onclick=()=>openOrder(b.dataset.order))}
function openOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;$("#dialogTitle").textContent="Order "+(o.orderNumber||o.order_id||o.id);$("#dialogEyebrow").textContent="Fulfilment";$("#dialogBody").innerHTML=`<div class="form-grid"><div class="field"><label>Order status</label><select id="editOrderStatus"><option>processing</option><option>packed</option><option>ready_to_ship</option><option>shipped</option><option>out_for_delivery</option><option>delivered</option><option>cancelled</option></select></div><div class="field"><label>Payment status</label><select id="editPaymentStatus"><option>pending</option><option>pending_verification</option><option>paid</option><option>failed</option><option>refunded</option></select></div><div class="field full"><label>Tracking number</label><input id="editTracking" value="${esc(o.trackingNumber||"")}"></div></div><div class="form-actions"><button class="button" id="saveOrder" type="button">Save order</button></div>`;$("#editOrderStatus").value=o.status||"processing";$("#editPaymentStatus").value=o.paymentStatus||"pending";$("#saveOrder").onclick=async()=>{await updateDoc(doc(db,"orders",id),{status:$("#editOrderStatus").value,paymentStatus:$("#editPaymentStatus").value,trackingNumber:$("#editTracking").value.trim(),updatedAt:new Date().toISOString()});$("#dialog").close();toast("Order updated");await refresh()};$("#dialog").showModal()}
function products(){setTitle("Products","Commerce");$("#primaryAction").style.display="";$("#content").innerHTML=`<section class="panel"><div class="toolbar"><input id="productSearch" placeholder="Search products"><select id="productCategory"><option value="">All categories</option>${[...new Set(state.products.map(p=>p.category).filter(Boolean))].map(x=>`<option>${esc(x)}</option>`).join("")}</select></div><div id="productRows"></div></section>`;const apply=()=>{const q=$("#productSearch").value.toLowerCase(),cat=$("#productCategory").value;const rows=state.products.filter(p=>(!cat||p.category===cat)&&JSON.stringify(p).toLowerCase().includes(q));$("#productRows").innerHTML=productTable(rows);bindProductButtons()};$("#productSearch").oninput=apply;$("#productCategory").onchange=apply;apply()}
function productTable(rows){if(!rows.length)return'<div class="empty">No matching products.</div>';return `<div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td><div class="product-cell"><img src="${esc((p.images&&p.images[0])||p.image||"")}" alt=""><div><strong>${esc(p.name)}</strong><br><small>${esc(p.sku||p.id)}</small></div></div></td><td>${esc(p.category||"—")}</td><td>${money(p.price)}</td><td>${esc(p.stock??"—")}</td><td><span class="badge ${esc(p.status||"active")}">${esc(p.status||"active")}</span></td><td><div class="row-actions"><button data-product="${esc(p.id)}">Edit</button><button data-delete-product="${esc(p.id)}">Delete</button></div></td></tr>`).join("")}</tbody></table></div>`}
function bindProductButtons(){document.querySelectorAll("[data-product]").forEach(b=>b.onclick=()=>openProduct(b.dataset.product));document.querySelectorAll("[data-delete-product]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this product?"))return;await deleteDoc(doc(db,"products",b.dataset.deleteProduct));toast("Product deleted");await refresh()})}
function openProduct(id=null){const p=id?state.products.find(x=>x.id===id):{};$("#dialogTitle").textContent=id?"Edit product":"Add product";$("#dialogEyebrow").textContent="Catalogue";$("#dialogBody").innerHTML=`<div class="form-grid"><div class="field full"><label>Name</label><input id="pName" value="${esc(p.name||"")}"></div><div class="field"><label>Price (ZAR)</label><input id="pPrice" type="number" min="0" step=".01" value="${esc(p.price||"")}"></div><div class="field"><label>Compare-at price</label><input id="pCompare" type="number" min="0" step=".01" value="${esc(p.comparePrice||"")}"></div><div class="field"><label>Category</label><input id="pCategory" value="${esc(p.category||"")}"></div><div class="field"><label>Stock</label><input id="pStock" type="number" min="0" value="${esc(p.stock??"")}"></div><div class="field"><label>Status</label><select id="pStatus"><option>active</option><option>draft</option><option>hidden</option></select></div><div class="field"><label>SKU</label><input id="pSku" value="${esc(p.sku||"")}"></div><div class="field full"><label>Primary image URL</label><input id="pImage" value="${esc((p.images&&p.images[0])||p.image||"")}"></div><div class="field full"><label>Description</label><textarea id="pDescription">${esc(p.description||"")}</textarea></div></div><div class="form-actions"><button class="button" id="saveProduct" type="button">Save product</button></div>`;$("#pStatus").value=p.status||"active";$("#saveProduct").onclick=async()=>{const data={name:$("#pName").value.trim(),price:Number($("#pPrice").value),comparePrice:Number($("#pCompare").value)||null,category:$("#pCategory").value.trim().toLowerCase(),stock:Number($("#pStock").value)||0,status:$("#pStatus").value,sku:$("#pSku").value.trim(),image:$("#pImage").value.trim(),description:$("#pDescription").value.trim(),updatedAt:new Date().toISOString()};if(!data.name||!data.price){toast("Name and price are required");return}if(id)await updateDoc(doc(db,"products",id),data);else await addDoc(collection(db,"products"),{...data,createdAt:new Date().toISOString()});$("#dialog").close();toast("Product saved");await refresh()};$("#dialog").showModal()}
function inventory(){setTitle("Inventory","Commerce");const rows=[...state.products].sort((a,b)=>Number(a.stock??999)-Number(b.stock??999));$("#content").innerHTML=`<section class="panel"><div class="panel-head"><h2>Stock overview</h2><span>${rows.filter(p=>Number(p.stock??999)<=5).length} low-stock items</span></div>${productTable(rows)}</section>`;bindProductButtons()}
function customers(){setTitle("Customers","Commerce");$("#content").innerHTML=`<section class="panel"><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Email</th><th>Phone</th><th>Joined</th></tr></thead><tbody>${state.users.map(u=>`<tr><td><strong>${esc(u.name||"—")}</strong></td><td>${esc(u.email||"—")}</td><td>${esc(u.phone||"—")}</td><td>${date(u.createdAt)}</td></tr>`).join("")}</tbody></table></div></section>`}
function content(){setTitle("Content & campaigns","Marketing");$("#content").innerHTML=`<div class="grid-2"><section class="panel"><div class="panel-head"><h2>Homepage banners</h2></div>${simpleList(state.banners,"title")}</section><section class="panel"><h2>Content model</h2><p>Campaigns, lookbooks and homepage modules should be managed as Firestore content rather than duplicated HTML. This V2 admin is the foundation for that migration.</p></section></div>`}
function discounts(){setTitle("Discounts","Marketing");$("#content").innerHTML=`<section class="panel"><div class="panel-head"><h2>Coupons</h2></div>${simpleList(state.coupons,"code")}</section>`}
function payments(){setTitle("Payments","Operations");const paid=state.orders.filter(o=>o.paymentStatus==="paid"),pending=state.orders.filter(o=>o.paymentStatus!=="paid");$("#content").innerHTML=`<div class="metrics"><div class="metric"><span>Paid orders</span><strong>${paid.length}</strong></div><div class="metric"><span>Paid revenue</span><strong>${money(paid.reduce((s,o)=>s+Number(o.total||0),0))}</strong></div><div class="metric"><span>Needs review</span><strong>${pending.length}</strong></div></div><section class="panel">${orderTable(pending.slice(0,20))}</section>`;bindOrderButtons()}
function shipping(){setTitle("Shipping","Operations");const rows=state.orders.filter(o=>["packed","ready_to_ship","shipped","out_for_delivery"].includes(o.status));$("#content").innerHTML=`<section class="panel"><div class="panel-head"><h2>Fulfilment queue</h2></div>${orderTable(rows)}</section>`;bindOrderButtons()}
function settings(){setTitle("Store settings","System");$("#content").innerHTML='<section class="panel"><h2>V2 configuration</h2><p>Security-sensitive configuration stays server-side. Store presentation, shipping and content settings will move into validated Firestore settings documents as the migration continues.</p><p><strong>Admin access:</strong> Firebase Authentication + Firestore authorization.</p></section>'}
function simpleList(rows,key){return rows.length?'<div class="table-wrap"><table><tbody>'+rows.map(x=>`<tr><td><strong>${esc(x[key]||x.id)}</strong></td><td><span class="badge ${esc(x.status||"active")}">${esc(x.status||"active")}</span></td></tr>`).join("")+'</tbody></table></div>':'<div class="empty">Nothing here yet.</div>'}
