export const LEGAL_VERSION = '2026-10-08';
export const LEGAL_SOURCES = [
 ['Consumer Protection Act 68 of 2008','https://www.gov.za/documents/consumer-protection-act'],
 ['Electronic Communications and Transactions Act 25 of 2002','https://www.gov.za/documents/electronic-communications-and-transactions-act'],
 ['Protection of Personal Information Act 4 of 2013','https://www.justice.gov.za/legislation/acts/2013-004.pdf'],
 ['Information Regulator: privacy, marketing and PAIA guidance','https://inforegulator.org.za/'],
 ['Consumer Goods and Services Ombud','https://www.cgso.org.za/']
];
export const LEGAL_POLICIES = {
 'terms-of-use': {title:'Terms & conditions',intro:'Clear terms for shopping with Drixel SA. Your statutory consumer rights always remain available.',sections:[
 ['Who you are buying from','Drixel SA is the store trading name. The seller’s published legal details appear below. For orders, cancellations, complaints or legal enquiries, use the published customer-care email. These terms apply to individual purchases, not an automatic subscription.'],
 ['Your rights come first','These terms are subject to applicable South African law, including the Consumer Protection Act (CPA) and Electronic Communications and Transactions Act (ECTA). They do not waive mandatory rights, exclude liability that cannot lawfully be excluded, or prevent you approaching a regulator, ombud or court. Additional mandatory protections in your destination country are preserved.'],
 ['Accounts and lawful use','Provide accurate order and contact details. Keep account credentials private and tell us about suspected misuse. Do not impersonate another customer, submit fraudulent payment evidence, upload unlawful content or interfere with the store. Purchases by a person without legal capacity require appropriate guardian assistance or authority. Security restrictions must not remove rights relating to an existing paid order.'],
 ['Product information','Read the product description, size guide, fabric details, selected colour and stock information before ordering. Screen colours can differ from real fabric; this is not an excuse for supplying materially different goods. Personalisation, production lead times and any special conditions must be disclosed before checkout. Standard sizes or colours do not, by themselves, make a product personalised.'],
 ['Prices and promotions','The checkout summary identifies the currency, items, discount, delivery charge and total payable, including applicable taxes. Do not pay until you have reviewed it. Currency conversion and third-party bank charges may differ from displayed estimates; destination duties must be disclosed or explained before an international order is accepted. Promotions apply only on their stated dates and conditions. Price corrections must comply with the CPA; an error is not a blanket right to cancel any paid order or charge you more without agreement.'],
 ['Reviewing and placing an order','Before submitting, review the bag, quantities, sizes, delivery address and payment method; correct mistakes or leave checkout. An order reference records your request or reservation. A payment attempt, pending payment or reserved item does not mean a payment succeeded. We confirm acceptance and payment status separately. If an order cannot be fulfilled, we will inform you and refund money received in accordance with the law.'],
 ['Payments and records','Only payment methods currently offered at checkout are available. Yoco and SnapScan process their respective payments; EFT orders require funds to be verified before dispatch. Never email card credentials or passwords. Keep the checkout summary, receipt and order reference. Signed-in customers can view available order records; contact customer care for a copy if access is unavailable. Save or print these policies when ordering.'],
 ['Delivery and cancellation','The shipping policy explains delivery arrangements and delays. The returns policy explains online cooling-off, defective-goods remedies and refunds. A reservation expiry cannot erase a refund right where funds were received. We will not substitute a different product without your agreement.'],
 ['Intellectual property and customer material','Drixel branding, photographs and original store content remain the property of their respective owners. You may save information for your personal shopping and legal records. Commercial reuse requires permission. Sending support evidence does not grant permission to use your photos in advertising; separate permission is needed.'],
 ['Responsibility and interruptions','We take reasonable care with the store and payment integration. Temporary technical outages may occur; contact customer care if a payment succeeds but an order is not confirmed. We do not exclude responsibility for fraud, gross negligence, defective-product liability or other non-excludable obligations. Courier problems or events outside our control do not automatically remove cancellation, refund or delivery rights.'],
 ['Complaints and dispute resolution','Send your order reference, the issue and requested remedy to customer care. If unresolved, you may approach the Consumer Goods and Services Ombud at cgso.org.za or the National Consumer Commission at thencc.org.za, as appropriate. Privacy complaints may be made to the Information Regulator. No compulsory private arbitration, exclusive foreign court or confidentiality condition restricts your statutory remedies.'],
 ['Policy changes','The version available when your order is accepted applies to that purchase. Later changes do not retrospectively reduce existing rights. South African law governs these terms subject to mandatory protections that apply to you. If a provision is unlawful, it does not invalidate the remaining lawful provisions.']
 ]},
 'returns-policy': {title:'Returns, cancellations & refunds',intro:'Online cancellation rights, quality guarantees and practical steps for resolving a purchase.',sections:[
 ['Request a return','Contact customer care with your order reference and the item concerned. State whether you want to cancel, return a faulty or incorrect item, or request an exchange. A reason is not required for an applicable online cooling-off cancellation. Reasonable proof of purchase is sufficient; photos can help but are not a condition that removes a legal right. We will provide return instructions and an appropriate address. Do not send goods to an unconfirmed address.'],
 ['Online cooling-off: seven days','Where ECTA section 44 applies, you may cancel without a reason or penalty within seven calendar days after receiving the goods. Notify us in writing, including by email, within that period. Only the direct cost of returning goods may be charged to you. We will refund the full payment within 30 days of cancellation, including the original delivery payment covered by the cancelled transaction. We do not impose a restocking fee on this right.'],
 ['Personalised items and exceptions','The ECTA cooling-off right has statutory exceptions, including goods made to your specifications or clearly personalised. Any relevant exception must be explained before purchase and applied only where the law permits it. A standard stocked garment, sale price or ordinary size selection does not automatically create an exception. These exceptions do not remove rights concerning defective, unsafe, incorrect or misdescribed goods.'],
 ['Direct-marketing purchases','Where CPA section 16 applies and ECTA section 44 does not, a purchase resulting from direct marketing may be cancelled without reason or penalty within five business days after the later of agreement or delivery. Give written or otherwise recorded notice. Refunds are due within 15 business days after cancellation notice if goods were not delivered, or after returned goods are received if they were delivered. Return costs and lawful adjustments are governed by CPA section 20.'],
 ['Faulty or unsafe goods: six months','Where the CPA applies, goods must meet the standards in section 55. If they fail those standards within six months after delivery, you may return them without penalty, at our risk and expense, and choose a repair, replacement or refund under section 56. Store credit is not compulsory. If a repair fails or a further defect appears within three months after repair, a replacement or refund is required. This does not limit other applicable rights.'],
 ['Wrong goods or unsuitable goods','Contact us if the item differs materially from the order or description. We will arrange the appropriate correction or lawful refund, including return transport where required. CPA section 20 also provides remedies in specified circumstances, including goods unsuitable for a particular purpose communicated to the supplier and returned within ten business days after delivery. Your rights depend on the facts and applicable law.'],
 ['Condition and inspection','For a voluntary size or preference exchange, keep items unworn, unwashed and with tags where possible. Such exchanges outside a statutory entitlement require a separately agreed offer and available stock. These conditions do not override statutory returns. A faulty garment can be faulty after normal use; missing original packaging does not automatically defeat a quality claim. Damage caused by misuse or ignoring care instructions may fall outside a defect remedy, depending on the facts.'],
 ['Return transport','For defective or incorrect goods where the law places costs on us, we will arrange or cover reasonable return transport. For an ECTA change-of-mind return, you pay the direct return cost. Keep collection or posting evidence. No return authorisation process may shorten a statutory notice period; notify us within the period even if collection instructions are still being arranged.'],
 ['Refund method and timing','Refunds normally go to the original payment method; an alternative may be agreed where necessary. Payment-provider posting times may differ, but do not extend statutory refund deadlines. We will provide confirmation when the refund is submitted. We do not deduct a payment-processing fee from a statutory full refund or force a voucher in place of money. Contact customer care if an expected refund is missing.'],
 ['Before dispatch, exchanges and sale goods','Tell us promptly if you wish to cancel before dispatch; applicable legal rights continue to apply. A voluntary exchange depends on stock and any price difference agreed with you. Sale goods retain statutory protections. A specifically disclosed defect affects rights only to the extent permitted by law; unrelated defects remain protected.'],
 ['Escalating a dispute','If we cannot resolve your request, you may seek assistance from the Consumer Goods and Services Ombud, National Consumer Commission or another competent body. Keep your order confirmation and correspondence. This policy does not limit access to statutory remedies.']
 ]},
 'shipping-policy': {title:'Shipping & delivery',intro:'How delivery is arranged, what the checkout price covers and what happens if an order is delayed.',sections:[
 ['Destinations and delivery options','Delivery is available only for destinations supported at checkout. A selectable country or currency is not a guarantee that we can ship there. South African orders may use The Courier Guy or PAXI, depending on the arrangement confirmed for your order. A PAXI collection requires an agreed collection point; a street-address form alone does not book a PAXI collection.'],
 ['Delivery charges','Use the verified checkout delivery charge and total for your destination. Free-delivery offers apply only where checkout confirms eligibility. There is no universal shipping fee or threshold promised by this page. We will not add an undisclosed delivery charge after acceptance without your agreement.'],
 ['Processing and delivery estimates','In-stock orders ordinarily take 1–3 business days to verify, check and pack, followed by an estimated 3–5 business days for standard South African transit. These are estimates, not an additional period overriding a delivery date agreed for your order. Remote areas and collection services may differ. Specific production or preorder lead times must be disclosed and agreed before purchase. Business days exclude weekends and South African public holidays.'],
 ['Late or unavailable orders','ECTA section 46 requires execution within 30 days of receiving the order unless a different period was agreed. If that deadline or the agreed period is missed, you may cancel with seven days’ written notice. If goods are unavailable, we must notify you immediately and refund payments within 30 days of that notification. We will communicate known delays; your legal remedies continue to apply.'],
 ['Payment verification and dispatch','Dispatch follows verified payment and order acceptance. EFT payment screenshots alone do not establish receipt of funds. If payment has left your account but the order remains pending, contact us with the reference so we can reconcile it. Never make a second payment merely because the confirmation page did not load.'],
 ['Tracking and collection','We provide available tracking or collection details after dispatch. Use the courier’s stated collection requirements and deadline where applicable. If tracking is missing or inaccurate, contact Drixel customer care. We remain your point of contact for the order and will help investigate with the delivery provider.'],
 ['Delivery responsibility','For deliveries arranged by us, we take responsibility for the goods until delivery to you or an authorised recipient at the agreed destination. Handover to a courier alone does not remove our responsibility. Contact us promptly about loss, damage or wrong delivery; a short reporting request is not a cut-off for your statutory rights. A courier’s internal claim deadline does not replace those rights.'],
 ['Addresses and unsuccessful delivery','Check your address, phone number and collection details before ordering. Ask us promptly for corrections before dispatch. If incorrect details or missed collection require another delivery, any reasonable additional charge must be explained and agreed, subject to the law. A failed delivery is not automatic permission to keep your payment. We will agree redelivery or the appropriate cancellation/refund process.'],
 ['International deliveries','International delivery requires an expressly supported destination and agreed service. Before acceptance we must explain the delivery charge, expected timeframe and who is responsible for import duties, taxes and customs charges. Customs delays can affect estimates; they do not waive mandatory consumer rights. Do not assume South African free-shipping offers apply internationally.'],
 ['Help with an order','Contact customer care with your order reference for a delay, missing parcel, damaged goods or delivery correction. The returns policy explains cancellation and refund rights. No statement here excludes rights under the CPA, ECTA or other applicable mandatory law.']
 ]},
 'privacy-policy': {title:'Privacy & personal information',intro:'What information the Drixel store uses, why it is needed and how to exercise your privacy rights.',sections:[
 ['Responsible party and contact','The seller identified in the legal details below is responsible for personal information processed for this store. Address privacy requests to the published Information Officer contact, or customer care for routing if none is yet published. This notice covers customer information collected through the storefront, orders, support and newsletter subscriptions.'],
 ['Information and sources','We receive account and contact details, delivery addresses, selected products, order and payment references, support correspondence and subscription preferences directly from you. Authentication, payment and delivery providers may supply verification, payment status or tracking information. Technical service logs can include IP addresses, device/browser information, timestamps and security events. Email services record dispatch, acceptance, delivery or bounce events.'],
 ['Purposes and lawful grounds','We use necessary information to administer accounts, accept payment, fulfil orders, handle returns and support, maintain records and protect the service. Processing must rest on an applicable POPIA ground, such as performing the purchase contract, meeting a legal obligation, consent or a justified legitimate interest. A purchase does not give unrestricted permission to use your data for unrelated purposes.'],
 ['Required and optional information','Delivery and contact information needed to fulfil an order is required for that service; without it we may be unable to complete the order. Newsletter participation is optional and is not a condition of buying. Supply accurate information and contact us to correct it. Do not send unnecessary identity documents or sensitive information in a support request.'],
 ['Marketing choices','Promotional campaigns require a lawful basis under POPIA section 69. Our newsletter uses an opt-in subscription process; completing a purchase alone is not a newsletter subscription. You may withdraw consent using the unsubscribe link or by contacting customer care, without a charge for doing so. An unsubscribe must be respected. Essential order, delivery, refund and security messages may still be sent for their service purpose; they must not be disguised advertisements.'],
 ['Providers and recipients','We use service providers to operate the website, manage customer accounts and records, deliver communications, process payments and fulfil deliveries. We share only the information needed for the relevant service. Authorised staff, advisers and authorities may receive information where needed or legally required. We do not sell customer lists.'],
 ['International processing','Some hosting and service providers process information outside South Africa. Cross-border transfers must meet POPIA section 72, for example through adequate legal or contractual protection or another applicable statutory ground. You may request information about the providers and safeguards relevant to your data. This notice is not blanket consent to every overseas transfer.'],
 ['Payments and account security','Card details are entered with the payment provider; the store uses order/payment references and status information rather than storing full card numbers or card security codes. We use reasonable technical and organisational safeguards to protect personal information and limit access to people who need it for their work.'],
 ['Cookies and browser storage','The current storefront uses browser storage for functions such as the bag, account session and market selection. Service providers may use technical storage needed to deliver their services. Browser settings can clear or restrict storage, which can affect sign-in or the saved bag. Any additional advertising or optional tracking must have an appropriate notice and lawful basis before activation; this notice does not silently authorise new trackers.'],
 ['Retention and deletion','Information should be kept only as long as necessary for its purpose, applicable recordkeeping obligations and legitimate unresolved disputes. Account deletion does not automatically delete order, tax or fraud-prevention records that must lawfully be retained. Limited suppression records may be retained to honour an unsubscribe. Backups may take time to expire. Contact the Information Officer for the retention criteria relevant to your request; no unlimited retention is authorised by this notice.'],
 ['Access, correction and objection','You may request confirmation/access to your information, correction of inaccurate data and deletion where retention is no longer lawful. You may object to processing on grounds provided by POPIA and withdraw consent, without undoing processing already lawfully performed. We may need proportionate identity verification and may explain a lawful refusal or permitted fee. Access-to-record requests may use the PAIA process and prescribed forms.'],
 ['Security incidents','We must take reasonable technical and organisational steps to protect information and address identified risks. Where there are reasonable grounds to believe an unauthorised person accessed or acquired personal information, notifications to the Information Regulator and affected people must be made as soon as reasonably possible, subject to lawful exceptions. No system can promise zero risk; that does not remove our security or notification duties.'],
 ['Children and sensitive information','The store does not seek children’s personal information or sensitive information for marketing. Where processing such information is necessary, the relevant POPIA conditions and authority must first be met. Contact customer care if information was submitted without appropriate authority.'],
 ['Complaints, PAIA and changes','Raise privacy concerns with the Information Officer. You can also complain to the Information Regulator at inforegulator.org.za, whose site provides POPIA forms and PAIA guidance. A PAIA manual, when published, is linked in the legal details. A privacy notice does not replace that manual. Material changes will be explained through an appropriate notice; a new purpose may require a separate lawful basis.']
 ]}
};
