import React,{useEffect,useState} from 'react';
import {apiUrl} from '../utils/api.js';
import {useCart} from '../context/CartContext.jsx';
function providerUrl(value,image=false){const u=new URL(value);if(u.protocol!=='https:'||u.hostname!=='pos.snapscan.io'||u.username||u.password||!/^\/qr\/[A-Za-z0-9_-]+(?:\.svg)?$/.test(u.pathname)||image&&!u.pathname.endsWith('.svg'))throw Error('The SnapScan payment link could not be verified.');return u.href;}
export default function SnapscanPayment({order,user,onConfirmed}){const cart=useCart(),[details,setDetails]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[imageFailed,setImageFailed]=useState(false),[message,setMessage]=useState('Preparing your payment code…'),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!user)return;if(order.paymentStatus==='paid'){setDetails(null);if(sessionStorage.getItem('drixel_pending_snapscan_order')===order.id){cart.clear();sessionStorage.removeItem('drixel_checkout_attempt');sessionStorage.removeItem('drixel_pending_snapscan_order');}setMessage(order.status==='payment_review'?'Payment received, but the order needs review. Contact Drixel before paying again.':'Your payment is confirmed.');return;}let active=true;setError('');async function load(){try{const token=await user.getIdToken(),r=await fetch(apiUrl('/api/payments/snapscan/checkout'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({orderId:order.id})}),d=await r.json();if(!r.ok)throw Error(d.message||'SnapScan is unavailable.');if(!active)return;if(d.review){setDetails(null);setMessage('Payment needs an order review. Contact Drixel before paying again.');return;}if(d.paid){setMessage('Your payment is confirmed.');onConfirmed?.();return;}setDetails({...d,paymentUrl:providerUrl(d.paymentUrl),qrUrl:providerUrl(d.qrUrl,true)});setMessage('Scan this code with SnapScan, or open the payment page on your phone.');}catch(e){if(active){setError(e.message);setMessage('Your order is saved. Contact Drixel before making another payment.');}}}load();return()=>{active=false;};},[user,order.id,order.paymentStatus,retry]);
 async function check(){if(busy)return;setBusy(true);setError('');try{const token=await user.getIdToken(),r=await fetch(apiUrl('/api/payments/snapscan/verify'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({orderId:order.id})}),d=await r.json();if(!r.ok)throw Error(d.message||'Payment could not be checked.');if(d.review){setMessage('Payment received, but the order needs review. Contact Drixel before paying again.');setDetails(null);return;}if(d.paid){setMessage('Payment confirmed. Thank you.');setDetails(null);if(sessionStorage.getItem('drixel_pending_snapscan_order')===order.id){cart.clear();sessionStorage.removeItem('drixel_checkout_attempt');sessionStorage.removeItem('drixel_pending_snapscan_order');}onConfirmed?.();}else setMessage('Payment has not been confirmed yet. If you already paid, wait before checking again.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="dx-snapscan"><p className="dx-payment-kicker">SNAPSCAN · SECURE PAYMENT</p><h2>{order.paymentStatus==='paid'?'Payment confirmed':'Pay for this order'}</h2><p role="status">{message}</p>{details&&<><div className="dx-snapscan-code">{!imageFailed?<img src={details.qrUrl} alt="SnapScan QR code for this order" onError={()=>setImageFailed(true)}/>:<p>The code image could not load. Use the payment link below.</p>}</div><dl><div><dt>Amount</dt><dd>ZAR {Number(details.amount).toFixed(2)}</dd></div><div><dt>Payment reference</dt><dd>{details.reference}</dd></div></dl><a className="confirmation-primary" href={details.paymentUrl} target="_blank" rel="noopener noreferrer">Open SnapScan payment</a></>}{error&&<p className="dx-error" role="alert">{error}</p>}{error&&!details&&<button type="button" disabled={busy} onClick={()=>setRetry(x=>x+1)}>Reload payment code</button>}{order.paymentStatus!=='paid'&&<button type="button" className="dx-snapscan-check" disabled={busy||!user} onClick={check}>{busy?'Checking payment…':'Check payment status'}</button>}<p className="dx-snapscan-note">Dispatch begins after payment verification. If you already paid, do not pay again while confirmation is pending.</p></section>;
}
