import test from 'node:test';import assert from 'node:assert/strict';
import {createAdminTeamHandlers} from '../src/admin-team.mjs';
import {resolveAdminMembership,accessId} from '../src/admin-membership.mjs';
function memory(){const values=new Map();return {values,doc(path){return {path,async get(){return {data:()=>values.get(path)}}}},collection(name){const query={orderBy(){return query},limit(){return query},async get(){const docs=[...values].filter(([p])=>p.startsWith(name+'/')).map(([path,value])=>({id:path.split('/')[1],data:()=>value}));return {docs,size:docs.length}}};return query},async runTransaction(fn){const writes=[];let writing=false;await fn({async get(ref){assert.ok(!writing);return {data:()=>values.get(ref.path)}},set(ref,data){writing=true;writes.push(()=>values.set(ref.path,data))},update(ref,data){writing=true;writes.push(()=>values.set(ref.path,{...values.get(ref.path),...data}))}});writes.forEach(fn=>fn());}}}
function harness(){const database=memory(),now=1800000000000,actor={uid:'owner',email:'drixelsa@gmail.com',email_verified:true,admin:true,drixel_admin_verified_at:now/1000},handlers=createAdminTeamHandlers({db:()=>database,authenticate:async()=>actor,now:()=>now}),req=body=>({body}),res={json(data){this.data=data;return this}};return {database,now,actor,handlers,req,res};}
const grant=async(h,email='new@example.com')=>{await h.handlers.grant(h.req({email}),h.res);return h.database.values.get('admin_access/'+accessId(email))};
test('only a verified owner with recent MFA may grant or remove access',async()=>{for(const patch of [{email:'staff@example.com'},{email_verified:false},{drixel_admin_verified_at:1800000000-301},{drixel_admin_verified_at:undefined}]){const h=harness();Object.assign(h.actor,patch);await assert.rejects(grant(h));assert.equal(h.database.values.has('admin_access/'+accessId('new@example.com')),false);}});
test('grant normalizes email, is idempotent and records server-owned audit',async()=>{const h=harness(),record=await grant(h,' New@Example.COM ');assert.equal(record.email,'new@example.com');assert.equal(record.active,true);assert.equal(record.uid,null);assert.equal(record.updatedBy,'owner');const version=record.version;await grant(h);assert.equal(h.database.values.get('admin_access/'+accessId(record.email)).version,version);const events=[...h.database.values].filter(([p])=>p.startsWith('security_events/'));assert.equal(events.length,1);assert.equal(events[0][1].action,'admin_access_granted');});
test('bad email and protected owner addresses cannot be granted',async()=>{for(const email of ['not-an-email','x\ny@example.com','admin@drixelsa.co.za','drixelsa@gmail.com']){const h=harness();await assert.rejects(grant(h,email));assert.equal([...h.database.values].filter(([p])=>p.startsWith('admin_access/')).length,0);}});
test('non-owner team members cannot read the team directory',async()=>{const h=harness();await grant(h);h.actor.email='member@example.com';await h.handlers.list(h.req({}),h.res);assert.deepEqual(h.res.data,{canManage:false,members:[]});});
test('owner list returns status only, without credentials or authenticator secrets',async()=>{const h=harness();await grant(h);await h.handlers.list(h.req({}),h.res);assert.equal(h.res.data.members[0].status,'Awaiting first sign-in');assert.deepEqual(Object.keys(h.res.data.members[0]).sort(),['active','email','id','status','updatedAt']);});
test('a signed-in unverified email or ordinary customer cannot redeem admin access',async()=>{const h=harness();await grant(h);for(const u of [{uid:'new',email:'new@example.com',email_verified:false},{uid:'customer',email:'customer@example.com',email_verified:true}])await assert.rejects(resolveAdminMembership(h.database,u),e=>e.status===403);assert.equal(h.database.values.get('admin_access/'+accessId('new@example.com')).uid,null);});
test('first verified sign-in binds an invite to one UID and returns only its own role version',async()=>{const h=harness(),record=await grant(h),u=await resolveAdminMembership(h.database,{uid:'new',email:'new@example.com',email_verified:true});assert.equal(u.admin,true);assert.equal(u.drixel_admin_access_id,accessId('new@example.com'));assert.equal(u.drixel_admin_access_version,record.version);assert.equal(h.database.values.get('admin_access/'+u.drixel_admin_access_id).uid,'new');await assert.rejects(resolveAdminMembership(h.database,{uid:'different',email:'new@example.com',email_verified:true}),e=>e.status===403);});
test('revocation denies the same active token immediately and rotates MFA proof',async()=>{const h=harness();await grant(h);const u=await resolveAdminMembership(h.database,{uid:'new',email:'new@example.com',email_verified:true});h.database.values.set('admin_security/new',{enabled:true,totpEnabled:true,version:'mfa1',totpSecret:'encrypted'});await h.handlers.remove(h.req({id:u.drixel_admin_access_id}),h.res);await assert.rejects(resolveAdminMembership(h.database,u),e=>e.status===403);assert.notEqual(h.database.values.get('admin_security/new').version,'mfa1');assert.equal(h.database.values.get('admin_security/new').totpSecret,'encrypted');assert.equal(h.database.values.get('admin_access/'+u.drixel_admin_access_id).active,false);assert.equal([...h.database.values].some(([p,v])=>p.startsWith('security_events/')&&v.action==='admin_access_removed'),true);});
test('re-granting access cannot reactivate an old token version',async()=>{const h=harness();await grant(h);const u=await resolveAdminMembership(h.database,{uid:'new',email:'new@example.com',email_verified:true});await h.handlers.remove(h.req({id:u.drixel_admin_access_id}),h.res);await grant(h);await assert.rejects(resolveAdminMembership(h.database,u),e=>e.status===403);const fresh=await resolveAdminMembership(h.database,{uid:'new',email:'new@example.com',email_verified:true});assert.notEqual(fresh.drixel_admin_access_version,u.drixel_admin_access_version);});
test('a different email cannot use another user grant ID',async()=>{const h=harness();await grant(h);await assert.rejects(resolveAdminMembership(h.database,{uid:'other',email:'other@example.com',email_verified:true,admin:true,drixel_admin_access_id:accessId('new@example.com')}),e=>e.status===403);});
test('missing grant records fail closed when a token names a grant',async()=>{const h=harness();await assert.rejects(resolveAdminMembership(h.database,{uid:'user',admin:true,email:'user@example.com',email_verified:true,drixel_admin_access_id:'a'.repeat(64)}),e=>e.status===403);});
test('owner and existing claim-based accounts continue to work without a grant record',async()=>{const h=harness();assert.equal((await resolveAdminMembership(h.database,h.actor)).uid,'owner');assert.equal((await resolveAdminMembership(h.database,{uid:'legacy',admin:true,email:'legacy@example.com'})).uid,'legacy');});
test('self-removal and protected-owner removal are rejected',async()=>{const h=harness();for(const record of [{email:'self@example.com',uid:'owner',active:true},{email:'admin@drixelsa.co.za',uid:'other-owner',active:true}]){const id=accessId(record.email);h.database.values.set('admin_access/'+id,record);await assert.rejects(h.handlers.remove(h.req({id}),h.res),e=>e.status===403);assert.equal(h.database.values.get('admin_access/'+id).active,true);}});
