import test from 'node:test';import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {createAuthenticatorHandlers,base32,totp,matchingStep,seal,unseal} from '../src/admin-authenticator.mjs';
import {recentAdminProof} from '../src/security.mjs';
function memory(){const values=new Map();return {values,doc(path){return {path,async get(){return {data:()=>values.get(path)}},async create(d){assert.ok(!values.has(path));values.set(path,d);}}},async runTransaction(fn){const writes=[];let written=false;await fn({async get(r){assert.ok(!written,'reads precede writes');return {data:()=>values.get(r.path)}},set(r,d,o){written=true;writes.push(()=>values.set(r.path,o?.merge?{...values.get(r.path),...d}:d))},update(r,d){written=true;writes.push(()=>values.set(r.path,{...values.get(r.path),...d}))}});for(const w of writes)w();}}}
function harness(){const database=memory(),key=randomBytes(32),clock={now:1800000000000},user={uid:'alice',email:'alice@example.com',admin:true,auth_time:clock.now/1000},minted=[];process.env.STORE_URL='https://drixelsa.co.za';const handlers=createAuthenticatorHandlers({db:()=>database,key:()=>key,identity:async()=>user,now:()=>clock.now,mint:async(u,v,n,m)=>{minted.push({uid:u.uid,version:v,method:m});return 'token'}}),req=body=>({body,get:()=>process.env.STORE_URL}),res={json(d){this.data=d;return this}};return {database,key,clock,user,minted,handlers,req,res};}
async function enroll(h){await h.handlers.setup(h.req({}),h.res);const id=h.res.data.challengeId,record=h.database.values.get('admin_challenges/'+id),secret=unseal(record.encryptedSecret,h.user.uid,h.key);await h.handlers.verify(h.req({challengeId:id,code:totp(secret,Math.floor(h.clock.now/30000))}),h.res);return {id,secret,codes:h.res.data.recoveryCodes};}
test('RFC 6238 SHA1 published vectors and base32 provisioning',()=>{const secret=Buffer.from('12345678901234567890');for(const [time,expected] of [[59,'94287082'],[1111111109,'07081804'],[1111111111,'14050471'],[1234567890,'89005924'],[2000000000,'69279037'],[20000000000,'65353130']])assert.equal(totp(secret,Math.floor(time/30),8),expected);assert.equal(base32(Buffer.from('foobar')),'MZXW6YTBOI');});
test('encrypted secrets are authenticated and bound to their account',()=>{const key=randomBytes(32),secret=randomBytes(20),encrypted=seal(secret,'alice',key);assert.ok(!encrypted.includes(base32(secret)));assert.deepEqual(unseal(encrypted,'alice',key),secret);assert.throws(()=>unseal(encrypted,'bob',key));assert.throws(()=>unseal(encrypted,'alice',randomBytes(32)));});
test('unregistered accounts are not verified; setup confirms code before enabling protection',async()=>{const h=harness();await h.handlers.status(h.req({}),h.res);assert.equal(h.res.data.enrolled,false);assert.equal(h.res.data.verified,false);await h.handlers.setup(h.req({}),h.res);assert.ok(!h.database.values.has('admin_security/alice'));const id=h.res.data.challengeId;await assert.rejects(h.handlers.verify(h.req({challengeId:id,code:'xxxxxx'}),h.res),e=>e.status===403);assert.equal(h.minted.length,0);const secret=unseal(h.database.values.get('admin_challenges/'+id).encryptedSecret,'alice',h.key);await h.handlers.verify(h.req({challengeId:id,code:totp(secret,h.clock.now/30000)}),h.res);assert.equal(h.res.data.recoveryCodes.length,8);const p=h.database.values.get('admin_security/alice');assert.equal(p.totpEnabled,true);assert.equal(p.credentials.length,0);assert.equal(h.minted[0].method,'totp');assert.equal(h.database.values.get('security_config/admin').authenticatorRequired,true);assert.ok(p.recoveryHashes.every(x=>!h.res.data.recoveryCodes.includes(x)));});
test('new email/account cannot inherit enrollment or redeem another account setup',async()=>{const h=harness();await h.handlers.setup(h.req({}),h.res);const id=h.res.data.challengeId;h.user.uid='bob';await h.handlers.status(h.req({}),h.res);assert.equal(h.res.data.enrolled,false);await assert.rejects(h.handlers.verify(h.req({challengeId:id,code:'123456'}),h.res),e=>e.status===409);assert.equal(h.minted.length,0);});
test('setup is bound to fresh sign-in, expiry and the session that initiated it',async()=>{for(const change of [h=>h.user.auth_time-=301,h=>h.user.auth_time-=1,h=>h.clock.now+=301000]){const h=harness();await h.handlers.setup(h.req({}),h.res);const id=h.res.data.challengeId;change(h);await assert.rejects(h.handlers.verify(h.req({challengeId:id,code:'123456'}),h.res));assert.equal(h.minted.length,0);}const h=harness();h.user.auth_time-=301;await assert.rejects(h.handlers.setup(h.req({}),h.res),e=>e.status===401);});
test('new device/session needs its own code proof; successful codes cannot be replayed',async()=>{const h=harness(),{secret}=await enroll(h);await h.handlers.status(h.req({}),h.res);assert.equal(h.res.data.enrolled,true);assert.equal(h.res.data.verified,false);await assert.rejects(h.handlers.verify(h.req({code:totp(secret,h.clock.now/30000)}),h.res),e=>e.status===403);h.clock.now+=30000;await h.handlers.verify(h.req({code:totp(secret,h.clock.now/30000)}),h.res);const p=h.database.values.get('admin_security/alice');Object.assign(h.user,{drixel_admin_method:'totp',drixel_admin_key_version:p.version,drixel_admin_verified_at:h.clock.now/1000});await h.handlers.status(h.req({}),h.res);assert.equal(h.res.data.verified,true);delete h.user.drixel_admin_verified_at;await h.handlers.status(h.req({}),h.res);assert.equal(h.res.data.verified,false);});
test('code guessing is limited across sign-in sessions',async()=>{const h=harness();await enroll(h);for(let i=0;i<4;i++)await assert.rejects(h.handlers.verify(h.req({code:'bad'}),h.res),e=>e.status===403);h.user.auth_time-=1;await assert.rejects(h.handlers.verify(h.req({code:'bad'}),h.res),e=>e.status===429);});
test('existing passkey must be verified before migration, and authenticator cannot be reset with a password',async()=>{const h=harness();h.database.values.set('admin_security/alice',{enabled:true,version:'old',credentials:[{id:'device'}]});await assert.rejects(h.handlers.setup(h.req({}),h.res),e=>e.status===403);Object.assign(h.user,{drixel_admin_key_version:'old',drixel_admin_verified_at:h.clock.now/1000});await enroll(h);await assert.rejects(h.handlers.setup(h.req({}),h.res),e=>e.status===409);assert.equal(recentAdminProof(h.user,h.database.values.get('admin_security/alice'),h.clock.now),false);});
test('recovery codes are single use and rotate proof; wrong recovery does not grant a session',async()=>{const h=harness(),{codes}=await enroll(h),old=h.database.values.get('admin_security/alice').version;await assert.rejects(h.handlers.recover(h.req({code:'0'.repeat(32)}),h.res),e=>e.status===403);await h.handlers.recover(h.req({code:codes[0]}),h.res);assert.notEqual(h.database.values.get('admin_security/alice').version,old);assert.equal(h.minted.at(-1).method,'totp');await assert.rejects(h.handlers.recover(h.req({code:codes[0]}),h.res),e=>e.status===403);});
test('verification window rejects expired, future and already-consumed codes',()=>{const secret=Buffer.from('12345678901234567890'),now=1800000000000,step=now/30000;assert.equal(matchingStep(secret,totp(secret,step),now),step);assert.equal(matchingStep(secret,totp(secret,step-2),now),null);assert.equal(matchingStep(secret,totp(secret,step+2),now),null);assert.equal(matchingStep(secret,totp(secret,step),now,step),null);});
