import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {cardConfig,bankConfig,verifySignature,paymentPatch,startCheckout,processEvent,checkoutUrl,returnOrigin} from '../src/payments.mjs';
const order={customer:{email:'test@example.test'},orderNumber:'DX-TEST',total:250,currency:'ZAR',paymentMethod:'yoco',paymentMode:'live',yocoCheckoutId:'checkout_1',inventoryStatus:'reserved',paymentStatus:'pending',status:'processing'};
const event={type:'payment.succeeded',payload:{id:'payment_1',status:'succeeded',amount:25000,currency:'ZAR',mode:'live',metadata:{checkoutId:'checkout_1'}}};
test('cards require explicit enable, matching key mode and webhook secret',()=>{assert.equal(cardConfig({CARD_PAYMENTS_ENABLED:'true',YOCO_MODE:'test',YOCO_SECRET_KEY:'sk_live_x',YOCO_WEBHOOK_SECRET:'whsec_x'}).enabled,false);assert.equal(cardConfig({CARD_PAYMENTS_ENABLED:'true',YOCO_MODE:'test',YOCO_SECRET_KEY:'sk_test_x',YOCO_WEBHOOK_SECRET:'whsec_x'}).enabled,true);assert.equal(cardConfig({YOCO_MODE:'test'}).enabled,false);});
test('bank instructions remain disabled until complete and expressly enabled',()=>{assert.equal(bankConfig({bankTransferEnabled:true}).enabled,false);assert.equal(bankConfig({bankTransferEnabled:true,bankName:'Bank',bankAccountHolder:'Drixel',bankAccountNumber:'123',bankBranchCode:'456',bankAccountType:'Business',secret:'never expose'}).enabled,true);assert.equal('secret' in bankConfig({secret:'private'}),false);});
test('webhook authenticity uses raw bytes and rejects forged or stale requests',()=>{const raw=Buffer.from(JSON.stringify(event)),secret='whsec_'+Buffer.from('test-secret').toString('base64'),timestamp=String(Math.floor(Date.now()/1000)),headers={'webhook-id':'evt_1','webhook-timestamp':timestamp};headers['webhook-signature']='v1,'+createHmac('sha256',Buffer.from('test-secret')).update('evt_1.'+timestamp+'.').update(raw).digest('base64');assert.equal(verifySignature(headers,raw,secret),true);assert.equal(verifySignature(headers,Buffer.concat([raw,Buffer.from(' ')]),secret),false);assert.equal(verifySignature(headers,raw,secret,Date.now()+181000),false);});
test('payment verifies amount, currency, checkout, payment ID and mode',()=>{assert.equal(paymentPatch(order,event).paymentStatus,'paid');for(const change of [{amount:1},{currency:'USD'},{mode:'test'},{metadata:{checkoutId:'other'}},{status:'failed'},{id:''}])assert.throws(()=>paymentPatch(order,{...event,payload:{...event.payload,...change}}));assert.equal(paymentPatch({...order,paymentStatus:'paid',yocoPaymentId:'payment_1'},event),null);assert.throws(()=>paymentPatch({...order,paymentStatus:'paid',yocoPaymentId:'different'},event));});
test('test payments cannot make fulfilment eligible and released stock requires review',()=>{const e={...event,payload:{...event.payload,mode:'test'}};const p=paymentPatch({...order,paymentMode:'test'},e);assert.equal(p.paymentStatus,'test_paid');assert.equal(p.status,'payment_test');assert.equal(paymentPatch({...order,inventoryStatus:'restored'},event).status,'payment_review');});
test('redirects stay on the hosted Yoco checkout and never use Worker origin',()=>{assert.equal(checkoutUrl('https://c.yoco.com/checkout/1'),'https://c.yoco.com/checkout/1');for(const url of ['http://c.yoco.com/1','https://c.yoco.com.evil.test/1','https://user@c.yoco.com/1'])assert.throws(()=>checkoutUrl(url));process.env.STORE_URL='https://drixelsa.co.za';assert.equal(returnOrigin({get:()=> 'https://evil.test'}),'https://drixelsa.co.za');});
test('unknown provider result preserves stock and retry uses same idempotency key',async()=>{Object.assign(process.env,{CARD_PAYMENTS_ENABLED:'true',YOCO_MODE:'test',YOCO_SECRET_KEY:'sk_test_x',YOCO_WEBHOOK_SECRET:'whsec_x'});const data={...order,paymentMode:'test'},updates=[],ref={get:async()=>({data:()=>data}),update:async patch=>updates.push(patch)},db={doc:()=>ref};const keys=[];const request=async(url,options)=>{keys.push(options.headers['Idempotency-Key']);throw Error('timeout');};for(let i=0;i<2;i++)await assert.rejects(startCheckout({orderId:'o1',req:{get:()=>null}},{db,request}),e=>e.status===503);assert.equal(keys[0],keys[1]);assert.equal(updates.some(x=>x.inventoryStatus==='restored'),false);process.env.CARD_PAYMENTS_ENABLED='false';});
test('duplicate signed payment does not create a second receipt; first payment is atomic',async()=>{let saved={...order},writes=[],ref={id:'o1'},db={doc:path=>({path}),collection:()=>({where:()=>({limit:()=>({get:async()=>({empty:false,docs:[{ref}]})})})}),runTransaction:async fn=>fn({get:async()=>({data:()=>saved}),update:(r,p)=>{saved={...saved,...p};writes.push('order')},set:()=>writes.push('mail')})};await processEvent(event,{db});assert.deepEqual(writes,['order','mail']);await processEvent(event,{db});assert.deepEqual(writes,['order','mail']);});
test('an existing test checkout cannot be resumed with live mode',async()=>{Object.assign(process.env,{CARD_PAYMENTS_ENABLED:'true',YOCO_MODE:'live',YOCO_SECRET_KEY:'sk_live_x',YOCO_WEBHOOK_SECRET:'whsec_x'});let calls=0;const db={doc:()=>({get:async()=>({data:()=>({...order,paymentMode:'test'})})})};try{await assert.rejects(startCheckout({orderId:'o1',req:{get:()=>null}},{db,request:async()=>{calls++;}}),/different payment mode/);assert.equal(calls,0);}finally{process.env.CARD_PAYMENTS_ENABLED='false';}});
test('checkout uses stored amount, validates provider response and reuses recorded URL',async()=>{Object.assign(process.env,{CARD_PAYMENTS_ENABLED:'true',YOCO_MODE:'test',YOCO_SECRET_KEY:'sk_test_x',YOCO_WEBHOOK_SECRET:'whsec_x'});let data={...order,paymentMode:'test',yocoCheckoutId:null},calls=0,body;const ref={get:async()=>({data:()=>data}),update:async p=>data={...data,...p}},db={doc:()=>ref,runTransaction:async fn=>fn({get:()=>ref.get(),update:(r,p)=>data={...data,...p}})};try{const request=async(url,options)=>{calls++;body=JSON.parse(options.body);return Response.json({id:'checkout_1',amount:25000,currency:'ZAR',processingMode:'test',redirectUrl:'https://c.yoco.com/checkout/1'});};await startCheckout({orderId:'o1',total:1,req:{get:()=>null}},{db,request});assert.equal(body.amount,25000);assert.match(body.successUrl,/^https:\/\/drixelsa.co.za\/za\/payment\/yoco\/success/);await startCheckout({orderId:'o1',req:{get:()=>null}},{db,request});assert.equal(calls,1);assert.equal(data.yocoCheckoutId,'checkout_1');}finally{process.env.CARD_PAYMENTS_ENABLED='false';}});

 test('live checkout never sends local return URLs even when local API access is allowed',()=>{const saved={...process.env};try{Object.assign(process.env,{STORE_URL:'https://drixelsa.co.za',ALLOW_LOCAL_ORIGINS:'true',YOCO_MODE:'live'});assert.equal(returnOrigin({get:()=> 'http://localhost:5173'}),'https://drixelsa.co.za');process.env.YOCO_MODE='test';assert.equal(returnOrigin({get:()=> 'http://localhost:5173'}),'http://localhost:5173');}finally{for(const k of ['STORE_URL','ALLOW_LOCAL_ORIGINS','YOCO_MODE']){if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k];}}});
 test('provider rejection reports HTTP status without exposing keys or raw provider data',async()=>{const saved={...process.env},original=console.error,logs=[];try{Object.assign(process.env,{STORE_URL:'https://drixelsa.co.za',CARD_PAYMENTS_ENABLED:'true',YOCO_MODE:'live',YOCO_SECRET_KEY:'sk_live_private',YOCO_WEBHOOK_SECRET:'whsec_private'});console.error=(...args)=>logs.push(args.join(' '));const ref={get:async()=>({data:()=>({...order,yocoCheckoutId:null})}),update:async()=>{}};await assert.rejects(startCheckout({orderId:'o1',req:{get:()=>null}},{db:{doc:()=>ref},request:async()=>Response.json({errorCode:'DOMAIN_NOT_VERIFIED',message:'private-provider-data'},{status:403})}),e=>e.status===502&&e.message.includes('HTTP 403'));assert.match(logs.join(' '),/DOMAIN_NOT_VERIFIED/);assert.doesNotMatch(logs.join(' '),/sk_live_private|whsec_private|private-provider-data/);}finally{console.error=original;for(const k of ['STORE_URL','CARD_PAYMENTS_ENABLED','YOCO_MODE','YOCO_SECRET_KEY','YOCO_WEBHOOK_SECRET']){if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k];}}});
