import test from 'node:test';import assert from 'node:assert/strict';import worker from '../dist/worker.mjs';
test('public health reveals no provider configuration or credentials',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/health'),{});assert.equal(r.status,200);const data=await r.json();assert.deepEqual(data,{service:'drixel-api',status:'ok'});});
test('unrelated origins cannot call even public routes',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/market',{headers:{Origin:'https://unrelated.example'}}),{});assert.equal(r.status,403);});
test('Pages preflight is allowed and correctly scoped',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/media/sign',{method:'OPTIONS',headers:{Origin:'https://andziboyrsa702-spec.github.io'}}),{});assert.equal(r.status,204);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://andziboyrsa702-spec.github.io');});
test('media signing requires administrator token before accessing secrets',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/media/sign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'image/png',size:100})}),{});assert.equal(r.status,401);});
test('card checkout stays disabled',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"paymentMethod":"yoco"}'}),{});assert.equal(r.status,409);});
test('country endpoint uses real Cloudflare country header',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/market',{headers:{'cf-ipcountry':'ZA'}}),{});assert.equal(r.status,200);assert.equal((await r.json()).countryCode,'ZA');});
test('oversized bodies rejected before parsing and authentication',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/media/sign',{method:'POST',body:'x'.repeat(250001)}),{});assert.equal(r.status,413);});

test('card confirmation requires authentication and cannot trust a success redirect',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/payments/yoco/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"orderId":"o1"}'}),{});assert.equal(r.status,401);});
test('forged Yoco webhook fails before database access',async()=>{process.env.YOCO_WEBHOOK_SECRET='whsec_dGVzdA==';try{const r=await worker.fetch(new Request('https://example.workers.dev/api/payments/yoco/webhook',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"type":"payment.succeeded"}'}),{});assert.equal(r.status,403);}finally{delete process.env.YOCO_WEBHOOK_SECRET;}});
test('test checkout is restricted to administrators before reserving stock',async()=>{const env={CARD_PAYMENTS_ENABLED:'true',YOCO_MODE:'test',YOCO_SECRET_KEY:'sk_test_x',YOCO_WEBHOOK_SECRET:'whsec_x'};const r=await worker.fetch(new Request('https://example.workers.dev/api/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"paymentMethod":"yoco"}'}),env);assert.equal(r.status,401);});

test('SnapScan checkout and payment checks require a signed-in owner',async()=>{for(const path of ['checkout','verify']){const r=await worker.fetch(new Request('https://example.workers.dev/api/payments/snapscan/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:'{"orderId":"o1"}'}),{});assert.equal(r.status,401);}});
test('forged SnapScan form webhook cannot reach the merchant API',async()=>{process.env.SNAPSCAN_WEBHOOK_AUTH_KEY='test-webhook';try{const r=await worker.fetch(new Request('https://example.workers.dev/api/payments/snapscan/webhook',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'payload='+encodeURIComponent('{"id":1,"status":"completed"}')}),{});assert.equal(r.status,403);}finally{delete process.env.SNAPSCAN_WEBHOOK_AUTH_KEY;}});

test('API responses include defensive headers without caching account data',async()=>{const r=await worker.fetch(new Request('https://example.workers.dev/api/health'),{});for(const [name,value] of [['cache-control','no-store'],['x-content-type-options','nosniff'],['x-frame-options','DENY'],['referrer-policy','no-referrer']])assert.equal(r.headers.get(name),value);});
test('invalid methods and malformed JSON fail before handlers',async()=>{for(const [path,method,body,status] of [['/api/media/sign','GET',undefined,405],['/api/market','DELETE',undefined,405],['/api/media/sign','POST','{broken',400],['/api/media/sign','POST','[]',400]]){const r=await worker.fetch(new Request('https://example.workers.dev'+path,{method,...(body?{body,headers:{'Content-Type':'application/json'}}:{})}),{});assert.equal(r.status,status);}});
