import test from 'node:test';import assert from 'node:assert/strict';
import {consumeRateLimit,recentAdminProof} from '../src/security.mjs';
import {readLoginGuard,recordLoginFailure,clearLoginGuard,LOGIN_COOLDOWN_MS} from '../../src/utils/loginSecurity.js';
import {createPasskeyHandlers,relyingParty,mintAdminToken} from '../src/admin-passkeys.mjs';
import {generateKeyPairSync,verify} from 'node:crypto';
const memory=()=>{const values=new Map();return {values,doc(path){return {path,get:async()=>({data:()=>values.get(path)}),create:async data=>{if(values.has(path))throw Error('exists');values.set(path,data);}}},async runTransaction(fn){const writes=[];const result=await fn({get:async ref=>({data:()=>values.get(ref.path)}),set:(ref,data)=>writes.push(()=>values.set(ref.path,data)),update:(ref,data)=>writes.push(()=>values.set(ref.path,{...values.get(ref.path),...data}))});writes.forEach(fn=>fn());return result;}}};
const storage=()=>{const map=new Map();return {getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}};
test('three credential failures pause password login; network failures do not count and expiry restores access',()=>{const s=storage(),now=10000;recordLoginFailure('auth/network-request-failed',s,now);assert.equal(readLoginGuard(s,now).failures,0);for(let n=1;n<=3;n++)assert.equal(recordLoginFailure('auth/invalid-credential',s,now+n).failures,n);assert.equal(readLoginGuard(s,now+LOGIN_COOLDOWN_MS+4).failures,0);recordLoginFailure('auth/too-many-requests',s,now);assert.equal(readLoginGuard(s,now).failures,3);clearLoginGuard(s);assert.equal(readLoginGuard(s,now).failures,0);});
test('server rate limit persists independently of client state, isolates identities and provides retry time',async()=>{const db=memory(),input={identity:'alice',bucket:'admin',limit:3,windowMs:900000,now:1000};for(let i=0;i<3;i++)await consumeRateLimit(db,input);await assert.rejects(consumeRateLimit(db,input),e=>e.status===429&&e.retryAfter===900);await consumeRateLimit(db,{...input,identity:'bob'});await consumeRateLimit(db,{...input,now:901001});});
test('admin proof rejects old, future and rotated credentials',()=>{const policy={enabled:true,version:'v1'},now=2000000,user={drixel_admin_key_version:'v1',drixel_admin_verified_at:1900};assert.equal(recentAdminProof(user,policy,now),true);for(const u of [{...user,drixel_admin_verified_at:1000},{...user,drixel_admin_verified_at:2001},{...user,drixel_admin_key_version:'v0'},{}])assert.equal(recentAdminProof(u,policy,now),false);});
test('passkeys only accept the canonical HTTPS origin',()=>{assert.deepEqual(relyingParty({get:()=> 'https://drixelsa.co.za'},'https://drixelsa.co.za'),{origin:'https://drixelsa.co.za',rpID:'drixelsa.co.za'});assert.throws(()=>relyingParty({get:()=> 'http://localhost:5173'},'https://drixelsa.co.za'),e=>e.status===403);assert.throws(()=>relyingParty({get:()=> 'https://evil.example'},'https://drixelsa.co.za'),e=>e.status===403);});
function harness(){const database=memory(),now=Date.now(),user={uid:'admin',email:'owner@example.com',admin:true,auth_time:now/1000};process.env.STORE_URL='https://drixelsa.co.za';process.env.ADMIN_PASSKEYS_ENABLED='true';let verifications=0;const handlers=createPasskeyHandlers({db:()=>database,identity:async()=>user,now:()=>now,mint:async()=> 'signed-token',webauthn:{generateRegistrationOptions:async()=>({challenge:'challenge'}),verifyRegistrationResponse:async()=>{verifications++;return {verified:true,registrationInfo:{userVerified:true,credential:{id:'key1',publicKey:new Uint8Array([1,2]),counter:0}}}}}});const request=body=>({body,get:()=> 'https://drixelsa.co.za'}),response={json(data){this.data=data;return this;}};return {database,now,user,handlers,request,response,verifications:()=>verifications};}
test('registration binds a one-use challenge to account and session and stores only public keys and hashed recovery codes',async()=>{const h=harness();await h.handlers.options(h.request({kind:'register'}),h.response);const challengeId=h.response.data.challengeId;await h.handlers.verify(h.request({kind:'register',challengeId,credential:{}}),h.response);assert.equal(h.response.data.customToken,'signed-token');assert.equal(h.response.data.recoveryCodes.length,8);const policy=h.database.values.get('admin_security/admin');assert.equal(policy.enabled,true);assert.equal(policy.credentials[0].publicKey,'AQI');assert.ok(policy.recoveryHashes.every(x=>x.length===64&&!h.response.data.recoveryCodes.includes(x)));assert.equal(h.database.values.get('security_config/admin').passkeysRequired,true);await assert.rejects(h.handlers.verify(h.request({kind:'register',challengeId,credential:{}}),h.response),e=>e.status===409);assert.equal(h.verifications(),1);});
test('stale sign-in cannot enrol; changed identity cannot redeem the challenge',async()=>{const h=harness();h.user.auth_time-=301;await assert.rejects(h.handlers.options(h.request({kind:'register'}),h.response),e=>e.status===401);h.user.auth_time=h.now/1000;await h.handlers.options(h.request({kind:'register'}),h.response);const id=h.response.data.challengeId;h.user.uid='attacker';await assert.rejects(h.handlers.verify(h.request({kind:'register',challengeId:id,credential:{}}),h.response),e=>e.status===409);assert.equal(h.verifications(),0);});
test('recovery consumes a code once and rotates session version; wrong code grants no token',async()=>{const h=harness();await h.handlers.options(h.request({kind:'register'}),h.response);await h.handlers.verify(h.request({kind:'register',challengeId:h.response.data.challengeId,credential:{}}),h.response);const code=h.response.data.recoveryCodes[0],old=h.database.values.get('admin_security/admin').version;await assert.rejects(h.handlers.recover(h.request({code:'a'.repeat(32)}),h.response),e=>e.status===403);await h.handlers.recover(h.request({code}),h.response);assert.notEqual(h.database.values.get('admin_security/admin').version,old);assert.equal(h.database.values.get('admin_security/admin').recoveryHashes.length,7);await assert.rejects(h.handlers.recover(h.request({code}),h.response),e=>e.status===403);});
test('custom admin token is server-signed and contains short-lived, version-bound proof',()=>{const previous={...process.env},keys=generateKeyPairSync('rsa',{modulusLength:2048});process.env.FIREBASE_PROJECT_ID='demo-drixel';process.env.FIREBASE_SERVICE_ACCOUNT=JSON.stringify({project_id:'demo-drixel',client_email:'test@demo-drixel.iam.gserviceaccount.com',private_key:keys.privateKey.export({type:'pkcs8',format:'pem'})});try{const token=mintAdminToken({uid:'admin'},'v1',2000000),parts=token.split('.'),claims=JSON.parse(Buffer.from(parts[1],'base64url'));assert.equal(claims.uid,'admin');assert.equal(claims.exp-claims.iat,300);assert.equal(claims.claims.drixel_admin_verified_at,2000);assert.equal(claims.claims.drixel_admin_key_version,'v1');assert.ok(verify('RSA-SHA256',Buffer.from(parts[0]+'.'+parts[1]),keys.publicKey,Buffer.from(parts[2],'base64url')));}finally{for(const key of ['FIREBASE_PROJECT_ID','FIREBASE_SERVICE_ACCOUNT'])if(previous[key]===undefined)delete process.env[key];else process.env[key]=previous[key];}});

test('real WebAuthn verification accepts a signed device assertion and rejects tampering, wrong origin and missing user verification',async()=>{
 const {encodeCBOR}=await import('@levischuck/tiny-cbor');
 const {verifyRegistrationResponse,verifyAuthenticationResponse}=await import('@simplewebauthn/server');
 const {createHash,sign}=await import('node:crypto'),keys=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),jwk=keys.publicKey.export({format:'jwk'}),decode=s=>Buffer.from(s,'base64url');
 const publicKey=Buffer.from(encodeCBOR(new Map([[1,2],[3,-7],[-1,1],[-2,new Uint8Array(decode(jwk.x))],[-3,new Uint8Array(decode(jwk.y))]]))),rpID='drixelsa.co.za',origin='https://drixelsa.co.za',challenge='device-challenge',id=Buffer.from('device-key'),rpHash=createHash('sha256').update(rpID).digest();
 const client=type=>Buffer.from(JSON.stringify({type,origin,challenge,crossOrigin:false}));
 const registrationAuth=Buffer.concat([rpHash,Buffer.from([0x45]),Buffer.alloc(4),Buffer.alloc(16),Buffer.from([0,id.length]),id,publicKey]);
 const registration={id:id.toString('base64url'),rawId:id.toString('base64url'),type:'public-key',response:{clientDataJSON:client('webauthn.create').toString('base64url'),attestationObject:Buffer.from(encodeCBOR(new Map([['fmt','none'],['attStmt',new Map()],['authData',new Uint8Array(registrationAuth)]]))).toString('base64url'),transports:['internal']}};
 const registered=await verifyRegistrationResponse({response:registration,expectedChallenge:challenge,expectedOrigin:origin,expectedRPID:rpID,requireUserVerification:true});assert.equal(registered.verified,true);
 const authData=Buffer.concat([rpHash,Buffer.from([5]),Buffer.from([0,0,0,1])]),clientData=client('webauthn.get'),signature=sign('sha256',Buffer.concat([authData,createHash('sha256').update(clientData).digest()]),keys.privateKey);
 const response={id:id.toString('base64url'),rawId:id.toString('base64url'),type:'public-key',response:{clientDataJSON:clientData.toString('base64url'),authenticatorData:authData.toString('base64url'),signature:signature.toString('base64url'),userHandle:null}},options={response,expectedChallenge:challenge,expectedOrigin:origin,expectedRPID:rpID,requireUserVerification:true,credential:registered.registrationInfo.credential};
 assert.equal((await verifyAuthenticationResponse(options)).verified,true);
 await assert.rejects(verifyAuthenticationResponse({...options,expectedOrigin:'https://attacker.example'}));
 const noUV=Buffer.from(authData);noUV[32]=1;await assert.rejects(verifyAuthenticationResponse({...options,response:{...response,response:{...response.response,authenticatorData:noUV.toString('base64url')}}}));
 const broken=Buffer.from(signature);broken[broken.length-1]^=1;assert.equal((await verifyAuthenticationResponse({...options,response:{...response,response:{...response.response,signature:broken.toString('base64url')}}})).verified,false);
});
