import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {snapscanConfig,snapscanUrls,snapscanSignature,snapscanPatch,snapscanRequest,settleSnapscanPayment,ownedSnapscanOrder,snapscanWebhook} from '../src/snapscan.mjs';
const order={customer:{uid:'u',email:'buyer@example.test'},orderNumber:'DX-TEST',paymentMethod:'snapscan',currency:'ZAR',total:320,snapscanCode:'DRIXEL1',snapscanReference:'order1',inventoryStatus:'reserved',paymentStatus:'pending',status:'processing'};
const payment={id:123,status:'completed',totalAmount:32000,requiredAmount:32000,tipAmount:0,transactionType:'payment',snapCode:'DRIXEL1',merchantReference:'order1'};
test('SnapScan is unavailable until merchant code, API and webhook are configured',()=>{assert.equal(snapscanConfig({snapscanEnabled:true,snapscanCode:'DRIXEL1'},{}).enabled,false);assert.equal(snapscanConfig({snapscanEnabled:true,snapscanCode:'https://malicious.test'},{SNAPSCAN_API_KEY:'key',SNAPSCAN_WEBHOOK_AUTH_KEY:'secret'}).enabled,false);const c=snapscanConfig({snapscanEnabled:true,snapscanCode:'DRIXEL1'},{SNAPSCAN_API_KEY:'private',SNAPSCAN_WEBHOOK_AUTH_KEY:'secret'});assert.equal(c.enabled,true);assert.equal('SNAPSCAN_API_KEY' in c,false);});
test('QR links use stored order amount and unique ID with strict payment mode',()=>{const d=snapscanUrls(order,'order1',''),url=new URL(d.paymentUrl);assert.equal(url.origin,'https://pos.snapscan.io');assert.equal(url.searchParams.get('amount'),'32000');assert.equal(url.searchParams.get('id'),'order1');assert.equal(url.searchParams.get('strict'),'true');assert.match(d.qrUrl,/DRIXEL1\.svg/);assert.throws(()=>snapscanUrls({...order,currency:'USD'},'order1'));assert.throws(()=>snapscanUrls({...order,snapscanCode:'../bad'},'order1'));assert.throws(()=>snapscanUrls(order,'different'));});
test('optional secure QR payload follows the merchant validation-key signature',()=>{const d=snapscanUrls(order,'order1','validation-key');const signature=new URL(d.paymentUrl).searchParams.get('signature');assert.equal(signature,createHmac('sha256','validation-key').update('validation-key||32000||order1').digest('hex'));assert.equal(d.paymentUrl.includes('validation-key'),false);});
test('webhook verifies the untouched form-encoded body and rejects tampering',()=>{const raw=Buffer.from('payload='+encodeURIComponent(JSON.stringify(payment))),key='webhook-key',header='SnapScan signature='+createHmac('sha256',key).update(raw).digest('hex');assert.equal(snapscanSignature(header,raw,key),true);assert.equal(snapscanSignature(header,Buffer.concat([raw,Buffer.from('&extra=1')]),key),false);assert.equal(snapscanSignature('',raw,key),false);assert.equal(snapscanSignature(header,raw,'wrong'),false);});
test('only completed matching merchant payments can mark the order paid',()=>{assert.equal(snapscanPatch(order,payment).paymentStatus,'paid');assert.equal(snapscanPatch(order,{...payment,status:'pending'}),null);for(const patch of [{totalAmount:100},{requiredAmount:1},{tipAmount:1},{merchantReference:'other'},{snapCode:'OTHER'},{id:0},{transactionType:'refund'},{isVoucher:true}])assert.throws(()=>snapscanPatch(order,{...payment,...patch}));assert.equal(snapscanPatch({...order,paymentStatus:'paid',snapscanPaymentId:123},payment),null);assert.equal(snapscanPatch({...order,inventoryStatus:'restored'},payment).status,'payment_review');assert.equal(snapscanPatch({...order,paymentStatus:'paid',snapscanPaymentId:122},payment).status,'payment_review');});
test('merchant API secrets stay in server authorization; outages never become success',async()=>{let seen;await snapscanRequest('/123',{key:'private-api',request:async(u,o)=>{seen={u,o};return Response.json(payment);}});assert.equal(seen.o.headers.Authorization,'Basic '+Buffer.from('private-api:').toString('base64'));assert.equal(seen.u,'https://pos.snapscan.io/merchant/api/v1/payments/123');for(const status of [401,429,500])await assert.rejects(snapscanRequest('/123',{key:'private',request:async()=>new Response('',{status})}),e=>e.status===503);await assert.rejects(snapscanRequest('/123',{key:'private',request:async()=>{throw Error('offline');}}),e=>e.status===503);});
function database(){const docs=new Map([['orders/order1',structuredClone(order)]]),ref=path=>({id:path.split('/').at(-1),path,get:async()=>({exists:docs.has(path),data:()=>docs.get(path)})});return {docs,db:{doc:ref,runTransaction:async fn=>{const writes=[];await fn({get:r=>r.get(),set:(r,d)=>writes.push(()=>docs.set(r.path,d)),update:(r,d)=>writes.push(()=>docs.set(r.path,{...docs.get(r.path),...d}))});writes.forEach(fn=>fn());}}};}
test('payment, receipt and replay record commit together; duplicate notifications send no extra receipt',async()=>{const {docs,db}=database();await settleSnapscanPayment(payment,{db});assert.equal(docs.get('orders/order1').paymentStatus,'paid');assert.equal([...docs.keys()].filter(x=>x.startsWith('mail_jobs/')).length,1);assert.equal(docs.get('payment_events/snapscan_123').orderId,'order1');await settleSnapscanPayment(payment,{db});assert.equal([...docs.keys()].filter(x=>x.startsWith('mail_jobs/')).length,1);await settleSnapscanPayment({...payment,id:124},{db});assert.equal(docs.get('orders/order1').status,'payment_review');assert.equal(docs.get('orders/order1').snapscanPaymentId,123);});
test('one provider payment cannot be credited to another order',async()=>{const {docs,db}=database();docs.set('payment_events/snapscan_123',{orderId:'other'});await assert.rejects(settleSnapscanPayment(payment,{db}),/already assigned/);assert.equal(docs.get('orders/order1').paymentStatus,'pending');assert.equal([...docs.keys()].filter(x=>x.startsWith('mail_jobs/')).length,0);});
test('customer payment lookup checks authentication, order ownership and method',async()=>{const {db}=database(),req={method:'POST',body:{orderId:'order1'},get:()=> 'Bearer test'};await assert.rejects(ownedSnapscanOrder(req,{db,authenticate:async()=>({uid:'other'})}),e=>e.status===403);await assert.rejects(ownedSnapscanOrder({...req,get:()=>null},{db}),e=>e.status===401);assert.equal((await ownedSnapscanOrder(req,{db,authenticate:async()=>({uid:'u'})})).order.snapscanCode,'DRIXEL1');});

test('even an authentic webhook must be confirmed by the merchant API',async()=>{const original=globalThis.fetch;Object.assign(process.env,{SNAPSCAN_API_KEY:'private-api',SNAPSCAN_WEBHOOK_AUTH_KEY:'webhook-key'});let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'https://pos.snapscan.io/merchant/api/v1/payments/123');assert.equal(options.headers.Authorization,'Basic '+Buffer.from('private-api:').toString('base64'));return Response.json({...payment,status:'pending'});};try{const payload=JSON.stringify(payment),raw=Buffer.from('payload='+encodeURIComponent(payload)),authorization='SnapScan signature='+createHmac('sha256','webhook-key').update(raw).digest('hex'),req={method:'POST',body:{payload},rawBody:raw,get:()=>authorization},res={json(value){this.body=value;return this;}};await snapscanWebhook(req,res);assert.equal(res.body.ignored,true);assert.equal(calls,1);}finally{globalThis.fetch=original;delete process.env.SNAPSCAN_API_KEY;delete process.env.SNAPSCAN_WEBHOOK_AUTH_KEY;}});
