import UserAvatar from '../components/UserAvatar.jsx';
import React,{useEffect,useState} from 'react';
import {useNavigate,Link} from 'react-router-dom';
import {collection,query,where,getDocs,doc,getDoc,setDoc,serverTimestamp} from 'firebase/firestore';
import {signOut,sendPasswordResetEmail} from 'firebase/auth';
import Layout from '../components/Layout.jsx';
import Seo from '../components/Seo.jsx';
import useAuth from '../hooks/useAuth.js';
import {auth,db} from '../config/firebase-react.js';
import {useMarket} from '../context/MarketContext.jsx';
export default function Account(){
 const {money,path}=useMarket(),user=useAuth(),nav=useNavigate();
 const [orders,setOrders]=useState([]),[profile,setProfile]=useState({}),[tab,setTab]=useState('orders'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;if(user===null)nav(path('/za/member/login')+'?next=account',{replace:true});if(user){setLoading(true);setError('');Promise.all([getDocs(query(collection(db,'orders'),where('customer.uid','==',user.uid))),getDoc(doc(db,'users',user.uid))]).then(([o,p])=>{if(live){setOrders(o.docs.map(x=>({id:x.id,...x.data()})));setProfile(p.data()||{})}}).catch(()=>{if(live)setError('Your account could not be loaded. Check your connection and retry.')}).finally(()=>{if(live)setLoading(false)})}return()=>{live=false}},[user,path,nav,attempt]);
 async function reset(){if(busy)return;setBusy(true);setNotice('');try{await sendPasswordResetEmail(auth,user.email);setNotice('Password reset requested. Check your email and spam folder.')}catch{setNotice('The password reset request failed. Please try again.')}finally{setBusy(false)}}
 if(!user)return <Layout><Seo title="My account | Drixel" noindex/><div className="account-empty">Loading account…</div></Layout>;
 return <Layout><Seo title="My account | Drixel" noindex/><main className="dx-account"><header><p>DRIXEL SA / CUSTOMER</p><h1>My account</h1></header>{notice&&<p role="status">{notice}</p>}{error&&<div role="alert">{error} <button onClick={()=>setAttempt(x=>x+1)}>Retry loading account</button></div>}<div className="account-grid"><aside className="account-panel"><div className="account-profile"><UserAvatar user={{...user,...profile}} size={64}/><strong>{user.displayName||profile.name||'Drixel customer'}</strong><span>{user.email}</span></div><div className="account-nav">{['orders','address','security'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x==='address'?'Delivery address':x==='security'?'Profile & security':'Orders'}</button>)}</div><button className="account-signout" onClick={()=>signOut(auth).catch(()=>setNotice('Sign out failed. Please retry.'))}>Sign out</button></aside><section className="account-panel">{loading?<p role="status">Loading your details…</p>:error?<p>Retry loading your details before making changes.</p>:<>{tab==='orders'&&<><h2>Your orders</h2>{orders.length===0&&<p>You have no orders yet.</p>}{orders.map(o=><Link className="account-order" key={o.id} to={path('/za/member/orders/'+o.id)}><div><strong>{o.orderNumber||o.id}</strong><small>{o.status||o.fulfillmentStatus||'processing'}</small></div><div className="account-order-meta"><span className="account-status">{o.paymentStatus||'pending'}</span><strong>{o.displayCurrency&&o.displayTotal!=null?new Intl.NumberFormat(undefined,{style:'currency',currency:o.displayCurrency}).format(o.displayTotal):money(o.total)}</strong></div></Link>)}</>}{tab==='address'&&<Address key={user.uid} user={user} profile={profile} saved={p=>setProfile(x=>({...x,defaultAddress:p}))}/>} {tab==='security'&&<><h2>Profile & security</h2><ProfilePicture user={user} profile={profile} saved={p=>setProfile(x=>({...x,...p}))}/><div className="account-detail-row"><span>Email</span><strong>{user.email}</strong></div><button disabled={busy} className="account-secondary" onClick={reset}>{busy?'Sending…':'Send password reset email'}</button></>}</>}</section></div></main></Layout>
}
function Address({user,profile,saved}){
 const a=profile.defaultAddress||{},[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e){e.preventDefault();if(busy)return;const d=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setMessage('');try{await setDoc(doc(db,'users',user.uid),{defaultAddress:d,updatedAt:serverTimestamp()},{merge:true});saved(d);setMessage('Delivery address saved.')}catch{setMessage('Your address was not saved. Please retry.')}finally{setBusy(false)}}
 return <form className="account-form" onSubmit={submit}><h2>Default delivery address</h2>{['firstName','lastName','phone','address','city','postalCode','province'].map(x=><label key={x}>{x.replace(/([A-Z])/g,' $1')}<input name={x} defaultValue={a[x]||''} required/></label>)}<button disabled={busy} className="account-primary">{busy?'Saving…':'Save address'}</button>{message&&<p role="status">{message}</p>}</form>
}

function ProfilePicture({user,profile,saved}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file||busy)return;setMessage('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)return setMessage('Choose a JPG, PNG or WebP picture smaller than 5 MB.');setBusy(true);let url;try{url=URL.createObjectURL(file);const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=192;canvas.height=192;const edge=Math.min(image.width,image.height);canvas.getContext('2d').drawImage(image,(image.width-edge)/2,(image.height-edge)/2,edge,edge,0,0,192,192);const photoURL=canvas.toDataURL('image/jpeg',0.8);await setDoc(doc(db,'users',user.uid),{photoURL,updatedAt:serverTimestamp()},{merge:true});saved({photoURL});setMessage('Profile picture saved.');}catch{setMessage('Your profile picture was not saved. Please retry.');}finally{if(url)URL.revokeObjectURL(url);setBusy(false)}}
 async function remove(){setBusy(true);try{await setDoc(doc(db,'users',user.uid),{photoURL:'',updatedAt:serverTimestamp()},{merge:true});saved({photoURL:''});setMessage('Profile picture removed.');}catch{setMessage('Your picture could not be removed. Please retry.');}finally{setBusy(false)}}
 return <div className="account-form"><UserAvatar user={{...user,...profile}} size={64}/><label>Change profile picture<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={upload}/></label><p>Your picture is shown on your account and to store staff.</p>{(profile.photoURL||user.photoURL)&&<button type="button" disabled={busy} onClick={remove}>Remove picture</button>}{(busy||message)&&<p role="status">{busy?'Saving picture…':message}</p>}</div>;
}
