import {apiUrl} from '../utils/api.js';
import React,{useEffect,useState} from 'react';
import {Link,useNavigate,useSearchParams,useParams} from 'react-router-dom';
import Layout from '../components/Layout.jsx';
import Seo from '../components/Seo.jsx';
import useAuth from '../hooks/useAuth.js';
import {useCart} from '../context/CartContext.jsx';
import {useMarket} from '../context/MarketContext.jsx';
export default function YocoReturn(){const user=useAuth(),cart=useCart(),{path}=useMarket(),nav=useNavigate(),[params]=useSearchParams(),{result}=useParams(),[retry,setRetry]=useState(0),[message,setMessage]=useState('Checking payment confirmation…'),[resume,setResume]=useState('');
 useEffect(()=>{if(user===null){setMessage('Sign in with your checkout account to view the payment result.');return;}if(!user)return;const orderId=params.get('order');if(!orderId){setMessage('The order reference is missing. Open your orders to check payment.');return;}let active=true,timer,count=0;setResume('');async function check(){try{const token=await user.getIdToken(),r=await fetch(apiUrl('/api/payments/yoco/verify'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({orderId})}),d=await r.json();if(!r.ok)throw Error(d.message||'Could not check payment.');if(!active)return;if(d.review){setMessage('Payment needs an order review. Contact Drixel before paying again.');return;}if(d.paid||d.testPaid){cart.clear();sessionStorage.removeItem('drixel_checkout_attempt');nav(path('/za/order-confirmation/'+encodeURIComponent(d.orderNumber)),{replace:true});return;}if(d.checkoutUrl)setResume(d.checkoutUrl);setMessage(result==='cancel'?'Payment was cancelled. Your bag is saved and your order is still pending.':result==='failure'?'Payment has not been confirmed. Your bag is saved. You can retry the secure payment.':'Waiting for Yoco’s payment confirmation. Please do not pay again.');if(result==='success'&&++count<10)timer=setTimeout(check,2000);}catch(e){if(active)setMessage(e.message||'Payment verification is unavailable. Check your orders before paying again.');}}check();return()=>{active=false;clearTimeout(timer);};},[user,retry,params.get('order'),result]);
 return <Layout><Seo title="Payment verification | Drixel" noindex/><main className="confirmation-shell"><p className="confirmation-kicker">SECURE PAYMENT</p><h1>Payment status</h1><p className="confirmation-lead" role="status">{message}</p>{user?<><button className="confirmation-primary" onClick={()=>setRetry(x=>x+1)}>Check confirmation again</button>{resume&&result!=='success'&&<a className="confirmation-primary" href={resume}>Return to secure payment</a>}<p><Link to={path('/za/member/orders')}>View my orders</Link></p></>:<Link className="confirmation-primary" to={path('/za/member/login')+'?next=account'}>Sign in</Link>}</main></Layout>;
}
