import { initializeApp } from "https://www.gstatic.com/firebasejs/9.23.0/firebase-app.js";
import { getAuth,onAuthStateChanged,signOut } from "https://www.gstatic.com/firebasejs/9.23.0/firebase-auth.js";
import { getFirestore,collection,getDocs,query,orderBy,limit } from "https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyA4_Ejkc3Of0T8fCj1QqkNN78-2xJ882F0",authDomain:"drixel-sa.firebaseapp.com",projectId:"drixel-sa",storageBucket:"drixel-sa.firebasestorage.app",messagingSenderId:"620600264300",appId:"1:620600264300:web:525de2d55cc1ae6269fa49",measurementId:"G-RTRKFY9NPW"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const admins=new Set(["admin@drixelsa.co.za","drixelsa@gmail.com"]); let currentView="dashboard";
const el=id=>document.getElementById(id); const money=n=>new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(Number(n||0));
const safe=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
onAuthStateChanged(auth,user=>{const email=(user?.email||"").toLowerCase();if(!user||!admins.has(email)){location.replace("../auth.html?next=admin");return}el("adminGate").hidden=true;el("adminApp").hidden=false;el("adminIdentity").textContent=user.email;render("dashboard")});
el("signOutBtn").onclick=async()=>{await signOut(auth);location.replace("../auth.html")}; el("refreshBtn").onclick=()=>render(currentView);
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>render(b.dataset.view));
async function docs(name){const s=await getDocs(collection(db,name));return s.docs.map(d=>({id:d.id,...d.data()}))}
function setActive(v){document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));el("viewTitle").textContent=v[0].toUpperCase()+v.slice(1)}
async function render(v){currentView=v;setActive(v);el("view").innerHTML='<div class="panel"><p>Loading…</p></div>';try{if(v==="dashboard")return dashboard();if(v==="orders")return orders();if(v==="products")return products();return placeholder(v)}catch(e){el("view").innerHTML='<div class="panel"><h2>Unable to load</h2><p>'+safe(e.message)+'</p></div>'}}
async function dashboard(){const [orders,products,users]=await Promise.all([docs("orders"),docs("products"),docs("users")]);const paid=orders.filter(o=>o.paymentStatus==="paid");const revenue=paid.reduce((s,o)=>s+Number(o.total||0),0);const pending=orders.filter(o=>["pending","pending_verification"].includes(o.paymentStatus)).length;const recent=[...orders].sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0)).slice(0,8);el("view").innerHTML='<div class="metrics"><div class="metric"><span>Revenue</span><strong>'+money(revenue)+'</strong></div><div class="metric"><span>Orders</span><strong>'+orders.length+'</strong></div><div class="metric"><span>Customers</span><strong>'+users.length+'</strong></div><div class="metric"><span>Needs attention</span><strong>'+pending+'</strong></div></div><div class="grid"><div class="panel"><div class="panel-head"><h2>Recent orders</h2></div>'+orderTable(recent)+'</div><div class="panel"><div class="panel-head"><h2>Store health</h2></div><p>'+products.length+' products in catalogue.</p><p>'+paid.length+' paid orders.</p><p>'+pending+' payments awaiting attention.</p></div></div>'}
function orderTable(rows){if(!rows.length)return '<div class="empty">No orders yet.</div>';return '<table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody>'+rows.map(o=>'<tr><td>'+safe(o.orderNumber||o.id.slice(0,8))+'</td><td>'+safe(o.customer?.email||o.email||"—")+'</td><td><span class="badge">'+safe(o.status||o.paymentStatus||"new")+'</span></td><td>'+money(o.total)+'</td></tr>').join("")+'</tbody></table>'}
async function orders(){const rows=await docs("orders");el("view").innerHTML='<div class="toolbar"><input id="orderSearch" placeholder="Search orders or customers"><button class="quiet" id="reloadOrders">Reload</button></div><div class="panel">'+orderTable(rows)+'</div>';el("reloadOrders").onclick=orders}
async function products(){const rows=await docs("products");el("view").innerHTML='<div class="toolbar"><input placeholder="Search products"><button class="primary" disabled title="Product editor is being migrated safely">Add product</button></div><div class="panel">'+(rows.length?'<table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Status</th></tr></thead><tbody>'+rows.map(p=>'<tr><td>'+safe(p.name||p.title||p.id)+'</td><td>'+safe(p.category||"—")+'</td><td>'+money(p.price)+'</td><td><span class="badge">'+safe(p.active===false?"Hidden":"Active")+'</span></td></tr>').join("")+'</tbody></table>':'<div class="empty">No Firestore products yet. Existing catalogue migration is required.</div>')+'</div>'}
function placeholder(v){el("view").innerHTML='<div class="panel"><h2>'+safe(v[0].toUpperCase()+v.slice(1))+'</h2><p>This workspace is separated from the customer storefront and ready for the next migration stage.</p></div>'}
