import { onAuthStateChanged,signOut } from "https://www.gstatic.com/firebasejs/9.23.0/firebase-auth.js";
import { collection,getDocs,doc,updateDoc } from "https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore.js";
import { auth,db } from "../config/firebase.js";
import { money,escapeHtml as safe,displayDate as date } from "../utils/format.js";
import { renderProductStudio } from "./product-studio.js";
import { renderCampaignStudio } from "./campaign-studio.js";
const admins=new Set(["admin@drixelsa.co.za","drixelsa@gmail.com"]);let currentView="dashboard",cache={};
const el=id=>document.getElementById(id);
async function docs(name,refresh=false){if(cache[name]&&!refresh)return cache[name];const s=await getDocs(collection(db,name));return cache[name]=s.docs.map(d=>({id:d.id,...d.data()}))}
onAuthStateChanged(auth,user=>{const email=(user?.email||"").toLowerCase();if(!user||!admins.has(email)){location.replace("../auth.html?next=admin");return}el("adminGate").hidden=true;el("adminApp").hidden=false;el("adminIdentity").textContent=user.email;render("dashboard")});
el("signOutBtn").onclick=async()=>{await signOut(auth);location.replace("../auth.html")};el("refreshBtn").onclick=()=>{cache={};render(currentView)};
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>render(b.dataset.view));
function setActive(v){document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));el("viewTitle").textContent=v[0].toUpperCase()+v.slice(1)}
async function render(v){currentView=v;setActive(v);el("view").innerHTML='<div class="panel loading">Loading workspace…</div>';try{const routes={dashboard,orders,products,inventory,customers,campaigns,discounts,newsletter,payments,shipping,settings};return await(routes[v]||placeholder)(v)}catch(e){el("view").innerHTML='<div class="panel"><h2>Unable to load</h2><p>'+safe(e.message)+'</p></div>'}}
function badge(v){return '<span class="badge">'+safe(v||"—")+'</span>'}
async function dashboard(){const [orders,products,users]=await Promise.all([docs("orders"),docs("products"),docs("users")]);const paid=orders.filter(o=>o.paymentStatus==="paid"),revenue=paid.reduce((s,o)=>s+Number(o.total||0),0),pending=orders.filter(o=>["pending","pending_verification"].includes(o.paymentStatus)).length,recent=[...orders].sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0)).slice(0,8);el("view").innerHTML='<div class="metrics"><div class="metric"><span>Revenue</span><strong>'+money(revenue)+'</strong><small>Paid orders</small></div><div class="metric"><span>Orders</span><strong>'+orders.length+'</strong><small>All time</small></div><div class="metric"><span>Customers</span><strong>'+users.length+'</strong><small>Registered</small></div><div class="metric"><span>Needs attention</span><strong>'+pending+'</strong><small>Payment review</small></div></div><div class="grid"><div class="panel"><div class="panel-head"><h2>Recent orders</h2><button class="text-btn" data-jump="orders">View all</button></div>'+orderTable(recent)+'</div><div class="panel"><div class="panel-head"><h2>Store health</h2></div><div class="health-row"><span>Catalogue</span><strong>'+products.length+' products</strong></div><div class="health-row"><span>Paid orders</span><strong>'+paid.length+'</strong></div><div class="health-row"><span>Payment review</span><strong>'+pending+'</strong></div></div></div>';document.querySelector("[data-jump]")?.addEventListener("click",()=>render("orders"))}
function orderTable(rows){if(!rows.length)return '<div class="empty">No orders yet.</div>';return '<div class="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Status</th><th>Total</th></tr></thead><tbody>'+rows.map(o=>'<tr class="order-row" data-id="'+safe(o.id)+'"><td><strong>'+safe(o.orderNumber||o.id.slice(0,8))+'</strong></td><td>'+safe(o.customer?.email||o.email||"—")+'</td><td>'+date(o.createdAt)+'</td><td>'+badge(o.status||o.paymentStatus||"new")+'</td><td>'+money(o.total)+'</td></tr>').join("")+'</tbody></table></div>'}
async function orders(){const rows=await docs("orders");el("view").innerHTML='<div class="toolbar"><div><input id="orderSearch" placeholder="Search order, customer or status"><select id="orderFilter"><option value="">All statuses</option><option>pending</option><option>paid</option><option>processing</option><option>shipped</option><option>delivered</option></select></div><span class="count">'+rows.length+' orders</span></div><div class="panel" id="ordersPanel">'+orderTable(rows)+'</div>';const draw=()=>{const q=el("orderSearch").value.toLowerCase(),f=el("orderFilter").value.toLowerCase();const filtered=rows.filter(o=>{const hay=[o.id,o.orderNumber,o.customer?.email,o.email,o.status,o.paymentStatus].join(" ").toLowerCase();return hay.includes(q)&&(!f||[o.status,o.paymentStatus].join(" ").toLowerCase().includes(f))});el("ordersPanel").innerHTML=orderTable(filtered);bindOrderRows(rows)};el("orderSearch").oninput=draw;el("orderFilter").onchange=draw;bindOrderRows(rows)}
function bindOrderRows(rows){document.querySelectorAll(".order-row").forEach(tr=>tr.onclick=()=>openOrder(rows.find(o=>o.id===tr.dataset.id)))}
function openOrder(o){if(!o)return;const customer=o.customer||{};el("view").innerHTML='<button class="back-btn" id="backOrders">← Orders</button><div class="detail-grid"><div class="panel"><p class="eyebrow">Order</p><h2>'+safe(o.orderNumber||o.id)+'</h2><div class="detail-list"><div><span>Customer</span><strong>'+safe(customer.name||[customer.firstName,customer.lastName].filter(Boolean).join(" ")||"—")+'</strong></div><div><span>Email</span><strong>'+safe(customer.email||o.email||"—")+'</strong></div><div><span>Placed</span><strong>'+date(o.createdAt)+'</strong></div><div><span>Total</span><strong>'+money(o.total)+'</strong></div><div><span>Payment</span><strong>'+safe(o.paymentStatus||"—")+'</strong></div><div><span>Fulfilment</span><strong>'+safe(o.status||"—")+'</strong></div></div></div><div class="panel"><h2>Fulfilment</h2><p>Update operational status without exposing controls on the customer storefront.</p><select id="fulfilmentStatus"><option value="processing">Processing</option><option value="packed">Packed</option><option value="ready_to_ship">Ready to ship</option><option value="shipped">Shipped</option><option value="out_for_delivery">Out for delivery</option><option value="delivered">Delivered</option></select><button class="primary block" id="saveStatus">Save status</button><p id="saveNote" class="muted"></p></div></div>';el("fulfilmentStatus").value=o.status||"processing";el("backOrders").onclick=()=>render("orders");el("saveStatus").onclick=async()=>{const btn=el("saveStatus");btn.disabled=true;try{await updateDoc(doc(db,"orders",o.id),{status:el("fulfilmentStatus").value,updatedAt:new Date().toISOString()});cache.orders=null;el("saveNote").textContent="Order updated.";o.status=el("fulfilmentStatus").value}catch(e){el("saveNote").textContent="Update failed: "+e.message}finally{btn.disabled=false}}}
async function legacyProducts(){const rows=await docs("products");el("view").innerHTML='<div class="toolbar"><div><input id="productSearch" placeholder="Search products"><select id="productCategory"><option value="">All categories</option>'+[...new Set(rows.map(p=>p.category).filter(Boolean))].sort().map(x=>'<option>'+safe(x)+'</option>').join("")+'</select></div><span class="count">'+rows.length+' products</span></div><div class="panel" id="productsPanel"></div>';const draw=()=>{const q=el("productSearch").value.toLowerCase(),cat=el("productCategory").value;const filtered=rows.filter(p=>[p.name,p.title,p.category,p.id].join(" ").toLowerCase().includes(q)&&(!cat||p.category===cat));el("productsPanel").innerHTML=productTable(filtered)};el("productSearch").oninput=draw;el("productCategory").onchange=draw;draw()}
function productTable(rows){if(!rows.length)return'<div class="empty">No matching products.</div>';return'<div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Sizes</th><th>Status</th></tr></thead><tbody>'+rows.map(p=>'<tr><td><strong>'+safe(p.name||p.title||p.id)+'</strong></td><td>'+safe(p.category||"—")+'</td><td>'+money(p.price)+'</td><td>'+safe(Array.isArray(p.sizes)?p.sizes.join(", "):"—")+'</td><td>'+badge(p.active===false?"Hidden":"Active")+'</td></tr>').join("")+'</tbody></table></div>'}
async function inventory(){const rows=await docs("products");const items=[];rows.forEach(p=>{if(Array.isArray(p.variants))p.variants.forEach(v=>items.push({product:p.name||p.title,sku:v.sku||"—",variant:[v.color,v.size].filter(Boolean).join(" / "),stock:Number(v.stock??v.quantity??0)}));else (p.sizes||[]).forEach(s=>items.push({product:p.name||p.title,sku:"Not assigned",variant:s,stock:null}))});el("view").innerHTML='<div class="panel"><div class="panel-head"><h2>Inventory</h2><span class="count">'+items.length+' variants</span></div>'+(items.length?'<table><thead><tr><th>Product</th><th>Variant</th><th>SKU</th><th>Stock</th></tr></thead><tbody>'+items.map(i=>'<tr><td>'+safe(i.product)+'</td><td>'+safe(i.variant)+'</td><td>'+safe(i.sku)+'</td><td>'+(i.stock===null?'<span class="muted">Migration needed</span>':i.stock)+'</td></tr>').join("")+'</tbody></table>':'<div class="empty">No inventory variants yet.</div>')+'</div>'}
async function customers(){const rows=await docs("users");el("view").innerHTML='<div class="panel"><div class="panel-head"><h2>Customers</h2><span class="count">'+rows.length+' registered</span></div>'+(rows.length?'<table><thead><tr><th>Customer</th><th>Email</th><th>Phone</th><th>Joined</th></tr></thead><tbody>'+rows.map(u=>'<tr><td>'+safe(u.name||u.displayName||"—")+'</td><td>'+safe(u.email||"—")+'</td><td>'+safe(u.phone||"—")+'</td><td>'+date(u.createdAt)+'</td></tr>').join("")+'</tbody></table>':'<div class="empty">No registered customers.</div>')+'</div>'}
async function campaigns(){const rows=await docs("banners");el("view").innerHTML='<div class="panel"><div class="panel-head"><h2>Campaign content</h2><span class="count">'+rows.length+' records</span></div><p class="muted">Campaigns are moving out of hard-coded homepage HTML into managed content. Existing banner records are shown here during migration.</p>'+(rows.length?'<table><thead><tr><th>Campaign</th><th>Destination</th><th>Status</th></tr></thead><tbody>'+rows.map(b=>'<tr><td>'+safe(b.title||b.name||b.id)+'</td><td>'+safe(b.link||b.url||"—")+'</td><td>'+badge(b.active===false?"Hidden":"Active")+'</td></tr>').join("")+'</tbody></table>':'<div class="empty">No campaign records yet.</div>')+'</div>'}
async function discounts(){const rows=await docs("coupons");el("view").innerHTML='<div class="panel"><div class="panel-head"><h2>Discounts</h2><span class="count">'+rows.length+' offers</span></div>'+(rows.length?'<table><thead><tr><th>Code</th><th>Value</th><th>Status</th></tr></thead><tbody>'+rows.map(x=>'<tr><td><strong>'+safe(x.code||x.id)+'</strong></td><td>'+safe(x.type==="percentage"?(x.value||x.discount)+"%":money(x.value||x.discount))+'</td><td>'+badge(x.active===false?"Inactive":"Active")+'</td></tr>').join("")+'</tbody></table>':'<div class="empty">No discounts configured.</div>')+'</div>'}
async function products(){return renderProductStudio(el("view"))}
async function newsletter(){return renderCampaignStudio(el("view"))}
async function payments(){const rows=await docs("orders");const paid=rows.filter(o=>o.paymentStatus==="paid"),pending=rows.filter(o=>["pending","pending_verification"].includes(o.paymentStatus));el("view").innerHTML='<div class="metrics two"><div class="metric"><span>Paid</span><strong>'+paid.length+'</strong></div><div class="metric"><span>Awaiting review</span><strong>'+pending.length+'</strong></div></div><div class="panel spaced">'+orderTable(pending)+'</div>';bindOrderRows(pending)}
async function shipping(){const rows=(await docs("orders")).filter(o=>["processing","packed","ready_to_ship","shipped","out_for_delivery"].includes(o.status));el("view").innerHTML='<div class="panel"><div class="panel-head"><h2>Fulfilment queue</h2><span class="count">'+rows.length+' active</span></div>'+orderTable(rows)+'</div>';bindOrderRows(rows)}
async function settings(){el("view").innerHTML='<div class="panel narrow"><h2>Store settings</h2><p class="muted">Operational configuration will be migrated here from browser localStorage. Sensitive provider credentials will remain server-side.</p><div class="detail-list"><div><span>Currency</span><strong>ZAR</strong></div><div><span>Region</span><strong>South Africa</strong></div><div><span>Email delivery</span><strong>Server-side</strong></div><div><span>Admin access</span><strong>Authenticated</strong></div></div></div>'}
async function collectionView(name,title,field){const rows=await docs(name);el("view").innerHTML='<div class="panel"><div class="panel-head"><h2>'+safe(title)+'</h2><span class="count">'+rows.length+' records</span></div>'+(rows.length?'<table><tbody>'+rows.map(x=>'<tr><td>'+safe(x[field]||x.id)+'</td><td>'+date(x.createdAt||x.timestamp)+'</td></tr>').join("")+'</tbody></table>':'<div class="empty">No records yet.</div>')+'</div>'}
function placeholder(v){el("view").innerHTML='<div class="panel"><h2>'+safe(v)+'</h2><p>This workspace is ready for migration.</p></div>'}
