import StoreErrorBoundary from './components/StoreErrorBoundary.jsx';
import React from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./app/App.jsx";
import { MarketProvider } from "./context/MarketContext.jsx";
import { WishlistProvider } from "./context/WishlistContext.jsx";
import { DialogProvider } from "./components/DialogProvider.jsx";
import "./styles/tokens.css";
import "./styles/catalogue.css";
import "./styles/storefront.css";
import "./styles/product.css";
import "./styles/cart.css";
import "./styles/checkout.css";
import "./styles/account.css";
import "./styles/auth.css";
import "./styles/order-confirmation.css";
import "./styles/react-v3.css";
import "./styles/admin-react.css";
const incomingRoute = new URLSearchParams(location.search).get('__drixel_route');
if (incomingRoute && incomingRoute.startsWith('/') && !incomingRoute.startsWith('//') && !incomingRoute.includes('\\')) history.replaceState(null, '', incomingRoute);
createRoot(document.getElementById("root")).render(<React.StrictMode><StoreErrorBoundary><BrowserRouter><MarketProvider><WishlistProvider><DialogProvider><App /></DialogProvider></WishlistProvider></MarketProvider></BrowserRouter></StoreErrorBoundary></React.StrictMode>);
